//
//  ShareCardContent.swift
//  Starcat
//
//  HOM-173 用户分享卡片：纯视觉卡片本体（"星际杂志卡 v2"布局）。
//
//  本 View 是**唯一的卡片视觉真源**，被两处复用：
//  1. `ShareCardSheet` 的 sheet 内预览（用户切主题时实时看变化）
//  2. `ShareCardExporter.render(...)` 用 `ImageRenderer` 渲染成 PNG 导出
//
//  把"卡片本体"和"sheet 容器"拆开是为了：
//  - 导出图片时不能把 sheet 的关闭按钮 / 主题选择器一起截进去
//  - 单测 / Preview 可以单独渲染卡片本体不依赖 sheet 上下文
//
//  布局规范（来自 issue HOM-173 dong4j 最终方案 + Magazine v2 image 参考）：
//  ┌─────────────────────────────────────┐
//  │ ✦ STARCAT       OPEN SOURCE · ID    │  ← 顶栏（两端对齐）
//  ├─────────────────────────────────────┤
//  │           [圆形大头像 96pt]          │  ← 头像区
//  │            dong4j                    │
//  │            @dong4j                   │
//  │           "一句签名…"                  │
//  ├─────────────────────────────────────┤
//  │   ⭐ 1.2K   👥 236   📦 4.8K          │  ← 三栏统计
//  │   Starred  Followers Following       │
//  ├─────────────────────────────────────┤
//  │  CONTRIBUTION GRAPH                  │  ← 草坪
//  │  ░▓▓░▓▓▓▓░░▓▓▓▓▓▓░▓▓▓▓               │
//  │  365 days · 1,234 contributions      │
//  ├─────────────────────────────────────┤
//  │  > Generated by Starcat · starcat.app│  ← 底部品牌注脚
//  └─────────────────────────────────────┘
//
//  尺寸：固定 400pt × 560pt（不是 520——加入 contribution 详情行后实测 520
//  会让贡献图与品牌注脚挤在一起）。导出时按 @3x → 1200×1680 PNG。
//
//  设计权衡：
//  - **不再做"按头像取主色"渐变背景**：用户最终方案明确要求三套主题保持一致，
//    每种主题颜色都是固定的（极简黑 / 热力橙 / GitHub 绿），让"主题"成为表达主体，
//    而不是头像主色。这也避免了导出图依赖 KFImage 异步取色的复杂性。
//  - **草坪只用静态版本**：贪吃蛇动画在导出图里没意义，渲染成静态草坪即可。
//    复用 `ContributionGraphView` 的格子尺寸 / 圆角风格保证 sidebar 与卡片观感一致。
//

import SwiftUI

/// 分享卡片本体（纯视觉，无任何交互）。
///
/// 用法：
/// ```swift
/// ShareCardContent(
///     user: user,
///     starredCount: viewModel.totalCount,
///     contribution: contributionService.payload,
///     theme: .githubGreen
/// )
/// .frame(width: 400, height: 560)
/// ```
struct ShareCardContent: View {

    /// 当前登录用户。
    let user: GitHubUserDTO

    /// 本地缓存的 starred 数量（来自 `HomeViewModel.totalCount`，与 sidebar 同源）。
    /// 远程 followers/following 走 `user.followers/following`（GitHub `/user` 接口返回）。
    let starredCount: Int

    /// 贡献草坪 payload。nil 时显示 7×53 占位灰格（不阻塞分享）。
    let contribution: ContributionCalendarPayload?

    /// 当前主题。
    let theme: ShareCardTheme

    /// 卡片宽度。固定 400pt，导出时通过 `ImageRenderer.scale` 放大到 @3x。
    static let canvasWidth: CGFloat = 400
    /// 卡片高度。560pt = 顶栏 36 + 头像区 200 + 统计区 64 + 草坪区 144 + 注脚 36 + 内边距。
    static let canvasHeight: CGFloat = 560

    // MARK: - 派生

    /// 当前主题色板（每个 body 计算一次，避免 View tree 内多处重复访问）。
    private var palette: ShareCardPalette { theme.palette }

    /// 卡片背景：双色线性渐变（顶部稍亮 → 底部主色），让深色卡片有微弱呼吸感。
    /// 不做 RadialGradient 是因为分享卡尺寸 400×560 矩形比例下椭圆光斑会偏中心，
    /// 顶 → 底线性更稳定，且与 `cardBackgroundSecondary` 的视觉用途（"顶部高光"）匹配。
    private var backgroundGradient: LinearGradient {
        LinearGradient(
            colors: [palette.cardBackgroundSecondary, palette.cardBackground],
            startPoint: .top,
            endPoint: .bottom
        )
    }

    var body: some View {
        VStack(spacing: 0) {
            topBar
            avatarSection
                .padding(.top, 18)
                .padding(.bottom, 18)
            divider
            statsSection
                .padding(.vertical, 18)
            divider
            contributionSection
                .padding(.vertical, 18)
            divider
            footerBar
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 20)
        .frame(width: Self.canvasWidth, height: Self.canvasHeight)
        .background(backgroundGradient)
        .overlay(
            // 极细 1pt 描边让卡片边界与外层 sheet 背景区分
            RoundedRectangle(cornerRadius: 24)
                .stroke(palette.cardBorder, lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: 24))
    }

    // MARK: - 顶栏

    /// 顶栏：左侧"✦ STARCAT" 品牌名，右侧"OPEN SOURCE · DEVELOPER ID" 副标题。
    /// 字号刻意拉小（11pt）+ 大字间距（tracking），呼应"杂志封面"质感而非 UI 标题。
    @ViewBuilder
    private var topBar: some View {
        HStack(alignment: .center, spacing: 8) {
            Text("✦ STARCAT")
                .font(.system(size: 12, weight: .black, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .tracking(2)

            Spacer()

            Text("OPEN SOURCE · DEVELOPER ID")
                .font(.system(size: 9, weight: .semibold, design: .monospaced))
                .foregroundStyle(palette.tertiaryText)
                .tracking(1.5)
        }
    }

    // MARK: - 头像 + 身份区

    /// 头像（96pt 圆形）+ 显示名 + @login + Bio。
    /// Bio 最多 2 行；nil/空串时省略不留空白。
    @ViewBuilder
    private var avatarSection: some View {
        VStack(spacing: 10) {
            // 96pt 头像 + 描边（用 accent 色 2pt 描边强化主题感）
            RemoteAvatar(urlString: user.avatarUrl, size: 96, showBorder: false)
                .overlay(
                    Circle().stroke(palette.accent, lineWidth: 2)
                )

            VStack(spacing: 2) {
                // 显示名（name 优先，缺失 fallback login）
                Text(user.name?.isEmpty == false ? user.name! : user.login)
                    .font(.system(size: 22, weight: .bold, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)

                Text("@\(user.login)")
                    .font(.system(size: 12, weight: .medium, design: .monospaced))
                    .foregroundStyle(palette.secondaryText)
                    .lineLimit(1)
            }

            // Bio：非空才渲染。Bio 中 GitHub 不渲染 @mention/markdown，原样平文本展示。
            if let bio = user.bio, !bio.isEmpty {
                Text("“\(bio)”")
                    .font(.system(size: 12, weight: .regular))
                    .italic()
                    .foregroundStyle(palette.secondaryText)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .padding(.top, 2)
                    .padding(.horizontal, 8)
            }
        }
        .frame(maxWidth: .infinity)
    }

    // MARK: - 三栏统计

    /// 三栏：Starred / Followers / Following。
    /// Starred 走本地 `starredCount`（与 sidebar 同源），followers/following 走 `/user` 字段。
    @ViewBuilder
    private var statsSection: some View {
        HStack(spacing: 0) {
            statCell(value: starredCount, labelKey: "sharecard.stats.starred", symbol: "star.fill")
            statDivider
            statCell(value: user.followers ?? 0, labelKey: "sharecard.stats.followers", symbol: "person.2.fill")
            statDivider
            statCell(value: user.following ?? 0, labelKey: "sharecard.stats.following", symbol: "person.fill")
        }
    }

    /// 三栏分隔条：高度 32pt 的细分隔线，颜色用主题 divider 色。
    private var statDivider: some View {
        Rectangle()
            .fill(palette.divider)
            .frame(width: 1, height: 32)
    }

    /// 单栏统计：图标 + 数字（大字）+ label（小字 secondary）。
    /// 数字用 SF Rounded + monospacedDigit 保证三栏对齐。
    @ViewBuilder
    private func statCell(value: Int, labelKey: LocalizedStringKey, symbol: String) -> some View {
        VStack(spacing: 4) {
            HStack(spacing: 4) {
                Image(systemName: symbol)
                    .font(.system(size: 11, weight: .semibold))
                    .foregroundStyle(palette.accent)
                Text(formatCompact(value))
                    .font(.system(size: 20, weight: .bold, design: .rounded))
                    .monospacedDigit()
                    .foregroundStyle(palette.primaryText)
            }
            Text(labelKey)
                .font(.system(size: 9, weight: .medium))
                .foregroundStyle(palette.tertiaryText)
                .tracking(1)
                .textCase(.uppercase)
        }
        .frame(maxWidth: .infinity)
    }

    /// 把整数格式化成紧凑形式（1234 → 1.2K，4823 → 4.8K，999 → 999）。
    /// 卡片宽度受限，5 位以上数字会挤占其他栏，4 位以上自动 K-suffix。
    private func formatCompact(_ n: Int) -> String {
        if n < 1000 { return String(n) }
        let k = Double(n) / 1000.0
        return String(format: "%.1fK", k)
    }

    // MARK: - 草坪

    /// 贡献草坪：53 周 × 7 天，颜色按 `theme.palette.contribution` 渲染。
    ///
    /// 不复用 `ContributionGraphView` 是因为：
    /// - 那个 view 强依赖 `@Environment(\.colorScheme)` 自动切 light/dark 调色板，
    ///   导出图需要固定主题色而不是跟随系统。
    /// - 那个 view 还挂了贪吃蛇 animator + TimelineView，导出图都不需要。
    /// - 重新写一份纯静态版本（约 30 行 Canvas）反而更轻、更可控。
    @ViewBuilder
    private var contributionSection: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("sharecard.contribution.title")
                    .font(.system(size: 9, weight: .semibold, design: .monospaced))
                    .tracking(1.5)
                    .foregroundStyle(palette.tertiaryText)
                Spacer()
                if let total = contribution?.totalContributions {
                    Text(String(format: String(localized: "sharecard.contribution.totalCount"), total))
                        .font(.system(size: 9, weight: .semibold, design: .monospaced))
                        .foregroundStyle(palette.secondaryText)
                }
            }

            ContributionStaticGrid(
                payload: contribution,
                palette: palette.contribution
            )
            .aspectRatio(53.0 / 7.0 * (10.0 / 12.0), contentMode: .fit)
            // 53 列 × 7 行 = aspect 7.57:1（10pt 宽 × 12pt 高）；
            // 卡片可用宽度 ~352pt（400 - 24×2 padding），渲染高度 ~46pt 视觉合适
        }
    }

    // MARK: - 通用元素

    /// 全宽细分隔线（顶/中/底分区用）。
    private var divider: some View {
        Rectangle()
            .fill(palette.divider)
            .frame(height: 0.7)
    }

    /// 底部品牌注脚：> Generated by Starcat · starcat.app
    /// 用等宽字 + 终端命令提示符风格，向 Gemini / Claude 方案致敬。
    @ViewBuilder
    private var footerBar: some View {
        HStack {
            Text("> Generated by Starcat")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.tertiaryText)
                .tracking(0.5)
            Spacer()
            Text("starcat.app")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.accent)
        }
    }
}

// MARK: - 静态草坪绘制（Canvas）

/// 纯静态贡献草坪。
///
/// 与 `ContributionGraphView` 的差异：
/// - 不依赖系统 colorScheme，调色板由调用方传入（保证导出图主题一致）。
/// - 不渲染贪吃蛇动画，纯静态网格。
/// - 不渲染顶部"贡献总数 + 更新于…"行（外层 `contributionSection` 已渲染）。
///
/// 单元格尺寸：横向 8pt × 纵向 10pt（aspect 0.8）；与 sidebar 内 10×14（aspect 0.71）
/// 略不同——分享卡总宽度更受限（350pt 可用），需要更扁的格子才能放下 53 列。
private struct ContributionStaticGrid: View {

    let payload: ContributionCalendarPayload?
    let palette: ContributionPalette

    /// 53 列 × 7 行的固有尺寸（基础值，外层 aspectRatio 缩放）。
    private let cellWidth: CGFloat = 10
    private let cellHeight: CGFloat = 12
    private let cellSpacing: CGFloat = 1.5
    private let cellCornerRadius: CGFloat = 1.5

    /// 整图固有尺寸——外层 aspectRatio 取这个比例。
    private var intrinsicWidth: CGFloat {
        53 * cellWidth + 52 * cellSpacing
    }
    private var intrinsicHeight: CGFloat {
        7 * cellHeight + 6 * cellSpacing
    }

    var body: some View {
        Canvas { ctx, size in
            let scale = size.width / intrinsicWidth
            drawGrid(ctx: ctx, scale: scale)
        }
    }

    /// 单遍绘制 53×7=371 格圆角矩形。
    /// 没数据时整片用 NONE 色填充作为骨架；有数据时按 weeks 数组从右对齐绘制。
    private func drawGrid(ctx: GraphicsContext, scale: CGFloat) {
        let cellW = cellWidth * scale
        let cellH = cellHeight * scale
        let spacing = cellSpacing * scale
        let corner = cellCornerRadius * scale

        guard let weeks = payload?.weeks else {
            // 占位：整面 none 色，让分享图在没拿到数据时也不空白
            for col in 0..<53 {
                for row in 0..<7 {
                    let x = CGFloat(col) * (cellW + spacing)
                    let y = CGFloat(row) * (cellH + spacing)
                    let rect = CGRect(x: x, y: y, width: cellW, height: cellH)
                    ctx.fill(Path(roundedRect: rect, cornerRadius: corner),
                             with: .color(palette.color(for: .none)))
                }
            }
            return
        }

        // 账号较新时 weeks 可能不足 53 周，与 ContributionGraphView 同款"右对齐"策略
        let startColumn = max(0, 53 - weeks.count)

        for (weekIdx, week) in weeks.enumerated() {
            let col = startColumn + weekIdx
            let x = CGFloat(col) * (cellW + spacing)
            for day in week.contributionDays {
                let y = CGFloat(day.weekday) * (cellH + spacing)
                let rect = CGRect(x: x, y: y, width: cellW, height: cellH)
                ctx.fill(
                    Path(roundedRect: rect, cornerRadius: corner),
                    with: .color(palette.color(for: day.contributionLevel))
                )
            }
        }
    }
}

// MARK: - Preview

#Preview("ShareCard - GitHub Green") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: "DONG Jianjun",
        avatarUrl: "https://avatars.githubusercontent.com/u/3380083?v=4",
        publicRepos: 48, followers: 236, following: 100,
        bio: "用代码解决真正的问题。", company: nil,
        location: "Shanghai", email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: "https://github.com/dong4j"
    )
    return ShareCardContent(
        user: mockUser, starredCount: 4823,
        contribution: nil, theme: .githubGreen
    )
    .padding()
    .background(Color.gray.opacity(0.2))
}

#Preview("ShareCard - Heat Orange") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: "DONG Jianjun",
        avatarUrl: nil,
        publicRepos: 48, followers: 236, following: 100,
        bio: "用代码解决真正的问题。", company: nil,
        location: "Shanghai", email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: nil
    )
    return ShareCardContent(
        user: mockUser, starredCount: 1284,
        contribution: nil, theme: .heatOrange
    )
    .padding()
    .background(Color.gray.opacity(0.2))
}

#Preview("ShareCard - Minimal") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: nil,
        avatarUrl: nil,
        publicRepos: 48, followers: 236, following: 100,
        bio: nil, company: nil, location: nil, email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: nil
    )
    return ShareCardContent(
        user: mockUser, starredCount: 999,
        contribution: nil, theme: .minimal
    )
    .padding()
    .background(Color.white)
}
