//
//  ShareCardContent.swift
//  Starcat
//
//  HOM-173 用户分享卡片：纯视觉卡片本体（"星际杂志卡 v2"布局）。
//
//  本 View 是**唯一的卡片视觉真源**，被两处复用：
//  1. `ShareCardSheet` 的 sheet 内预览（用户切主题时实时看变化）
//  2. `ShareCardExporter.render(...)` 用 `ImageRenderer` 渲染成 PNG 导出
//
//  把"卡片本体"和"sheet 容器"拆开是为了：
//  - 导出图片时不能把 sheet 的关闭按钮 / 主题选择器一起截进去
//  - 单测 / Preview 可以单独渲染卡片本体不依赖 sheet 上下文
//
//  布局规范（来自 issue HOM-173 dong4j 最终方案 + Magazine v2 image 参考）：
//  ┌─────────────────────────────────────┐
//  │ ✦ STARCAT       OPEN SOURCE · ID    │  ← 顶栏（两端对齐）
//  ├─────────────────────────────────────┤
//  │           [圆形大头像 96pt]          │  ← 头像区
//  │            dong4j                    │
//  │            @dong4j                   │
//  │           "一句签名…"                  │
//  ├─────────────────────────────────────┤
//  │   ⭐ 1.2K   👥 236   📦 4.8K          │  ← 三栏统计
//  │   Starred  Followers Following       │
//  ├─────────────────────────────────────┤
//  │  CONTRIBUTION GRAPH                  │  ← 草坪
//  │  ░▓▓░▓▓▓▓░░▓▓▓▓▓▓░▓▓▓▓               │
//  │  365 days · 1,234 contributions      │
//  ├─────────────────────────────────────┤
//  │  > Generated by Starcat · starcat.ink│  ← 底部品牌注脚
//  └─────────────────────────────────────┘
//
//  尺寸：固定 400pt × 560pt（不是 520——加入 contribution 详情行后实测 520
//  会让贡献图与品牌注脚挤在一起）。导出时按 @3x → 1200×1680 PNG。
//
//  设计权衡：
//  - **不再做"按头像取主色"渐变背景**：用户最终方案明确要求三套主题保持一致，
//    每种主题颜色都是固定的（极简黑 / 热力橙 / GitHub 绿），让"主题"成为表达主体，
//    而不是头像主色。这也避免了导出图依赖 KFImage 异步取色的复杂性。
//  - **草坪只用静态版本**：贪吃蛇动画在导出图里没意义，渲染成静态草坪即可。
//    复用 `ContributionGraphView` 的格子尺寸 / 圆角风格保证 sidebar 与卡片观感一致。
//

import SwiftUI
import Kingfisher

/// 分享卡片本体（纯视觉，无任何交互）。
///
/// 用法：
/// ```swift
/// ShareCardContent(
///     user: user,
///     starredCount: viewModel.totalCount,
///     contribution: contributionService.payload,
///     style: .magazine,
///     colorSet: .githubGreen,
///     isProUser: settings.isProUser
/// )
/// .frame(width: 400, height: 560)
/// ```
struct ShareCardContent: View {

    /// 当前登录用户。
    let user: GitHubUserDTO

    /// 本地缓存的 starred 数量（来自 `HomeViewModel.totalCount`，与 sidebar 同源）。
    /// 远程 followers/following 走 `user.followers/following`（GitHub `/user` 接口返回）。
    let starredCount: Int

    /// 贡献草坪 payload。nil 时显示 7×53 占位灰格（不阻塞分享）。
    let contribution: ContributionCalendarPayload?

    /// 用户自己公开仓库的开发语言统计。nil 时显示加载/空态，不回退到 starred 语言分布。
    let developerLanguages: DeveloperLanguageSnapshot?

    /// 当前版式。版式决定卡片结构，不再和颜色绑死。
    let style: ShareCardStyle

    /// 当前配色。原编号 1-5 的主题现在都映射为同一个 magazine 版式下的配色。
    let colorSet: ShareCardColorSet

    /// 当前用户是否为 Pro 用户。Pro 用户头像显示 Pro 标识。
    var isProUser: Bool = false

    /// 草坪月份标注需要跟随 App 内语言环境。这里显式读取 locale，避免导出图仍使用系统语言。
    @Environment(\.locale) private var locale

    /// 卡片宽度。固定 400pt，导出时通过 `ImageRenderer.scale` 放大到 @3x。
    static let canvasWidth: CGFloat = 400
    /// 卡片高度。560pt = 顶栏 36 + 头像区 200 + 统计区 64 + 草坪区 144 + 注脚 36 + 内边距。
    static let canvasHeight: CGFloat = 560

    // MARK: - 派生

    /// 当前色板（每个 body 计算一次，避免 View tree 内多处重复访问）。
    private var palette: ShareCardPalette { colorSet.palette }

    /// 显示名优先使用 GitHub name，缺失时回落 login；多个版式共用，避免文案分叉。
    private var displayName: String {
        user.name?.isEmpty == false ? user.name! : user.login
    }

    /// 分享卡 QR / 链接统一指向用户 GitHub 主页。
    private var profileURLString: String {
        "https://github.com/\(user.login)"
    }

    /// 第 3 套白色社交卡需要脱离纯黑白观感：头像金色、统计彩色、草坪绿色。
    /// 这里集中成一个判定，避免影响同样使用 lightCard 配色的其它版式。
    private var isSocialLightCard: Bool {
        style == .social && colorSet == .lightCard
    }

    /// 第 5 种样式的前两个浅色配色要用金色头像边框，避免原型 ring 混入黑色显脏。
    private var usesAdventureGoldAvatarRing: Bool {
        style == .adventure && (colorSet == .lightCard || colorSet == .adventureSunrise)
    }

    /// 第 5 种样式的黑暗背景变体。它们不只换图，还需要暗色文字、深色面板和定制草坪。
    private var isDarkAdventureVariant: Bool {
        style == .adventure && (colorSet == .adventureShadow || colorSet == .adventureFel)
    }

    /// 第 5 种样式按配色切换背景图；集中在一处，避免每加一个背景就复制 View 分支。
    private var adventureBackgroundAssetName: String {
        switch colorSet {
        case .adventureSunrise:
            return "ShareCardAdventureSunriseBackground"
        case .adventureShadow:
            return "ShareCardAdventureShadowBackground"
        case .adventureFel:
            return "ShareCardAdventureFelBackground"
        default:
            return "ShareCardAdventureBackground"
        }
    }

    /// 第 3 套样式所有颜色都使用语义彩色统计图标，避免只有白色主题被特殊处理。
    private var usesSocialColoredStats: Bool {
        style == .social
    }

    /// 第 4 套终端卡走像素风，外框圆角收窄；其它样式保持原来的大圆角分享卡质感。
    private var cardCornerRadius: CGFloat {
        style == .terminal ? 12 : 24
    }

    /// 卡片背景：双色线性渐变（顶部稍亮 → 底部主色），让深色卡片有微弱呼吸感。
    /// 不做 RadialGradient 是因为分享卡尺寸 400×560 矩形比例下椭圆光斑会偏中心，
    /// 顶 → 底线性更稳定，且与 `cardBackgroundSecondary` 的视觉用途（"顶部高光"）匹配。
    private var backgroundGradient: LinearGradient {
        LinearGradient(
            colors: [palette.cardBackgroundSecondary, palette.cardBackground],
            startPoint: .top,
            endPoint: .bottom
        )
    }

    var body: some View {
        // 2026-06-25：按版式走渲染路径，配色只通过 palette 注入。
        // 这样新增颜色不会复制 layout，新增 layout 也不需要复制 5 套颜色。
        Group {
            switch style {
            case .magazine:
                magazineBody
            case .idCard:
                idCardBody
            case .social:
                socialBody
            case .terminal:
                terminalBody
            case .adventure:
                adventureBody
            case .spotlight:
                spotlightBody
            }
        }
        .frame(width: Self.canvasWidth, height: Self.canvasHeight)
        .background { cardBackground }
        .overlay(
            // 极细 1pt 描边让卡片边界与外层 sheet 背景区分
            RoundedRectangle(cornerRadius: cardCornerRadius)
                .stroke(palette.cardBorder, lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: cardCornerRadius))
    }

    /// 卡片背景。magazine / adventure 使用用户给的背景图，其余样式仍走固定主题渐变。
    @ViewBuilder
    private var cardBackground: some View {
        if style == .magazine {
            Image("ShareCardMagazineBackground")
                .resizable()
                .scaledToFill()
                .frame(width: Self.canvasWidth, height: Self.canvasHeight)
                .clipped()
                .overlay {
                    // 图片本身亮度变化较大，叠固定深色遮罩让头像、链接、统计和草坪在导出图里稳定可读。
                    LinearGradient(
                        colors: [
                            palette.cardBackground.opacity(0.34),
                            palette.cardBackground.opacity(0.20),
                            palette.cardBackground.opacity(0.62)
                        ],
                        startPoint: .top,
                        endPoint: .bottom
                    )
                }
                .overlay {
                    LinearGradient(
                        colors: [
                            palette.cardBackground.opacity(0.56),
                            Color.clear,
                            palette.cardBackground.opacity(0.52)
                        ],
                        startPoint: .leading,
                        endPoint: .trailing
                    )
                }
        } else if style == .adventure {
            Image(adventureBackgroundAssetName)
                .resizable()
                .scaledToFill()
                .frame(width: Self.canvasWidth, height: Self.canvasHeight)
                .clipped()
                .overlay {
                    if isDarkAdventureVariant {
                        // 黑暗冒险图左侧留白本身很暗；这里加轻黑遮罩而非白雾，保持氛围并压住云层纹理。
                        LinearGradient(
                            colors: [
                                Color.black.opacity(0.28),
                                Color.black.opacity(0.10),
                                Color.clear
                            ],
                            startPoint: .leading,
                            endPoint: .trailing
                        )
                    } else {
                        // 浅色冒险图已经按 400×560 画布完整生成；这里只加极轻的左侧可读性遮罩。
                        LinearGradient(
                            colors: [
                                Color.white.opacity(0.18),
                                Color.white.opacity(0.04),
                                Color.clear
                            ],
                            startPoint: .leading,
                            endPoint: .trailing
                        )
                    }
                }
        } else {
            backgroundGradient
        }
    }

    // MARK: - Magazine 布局（HOM-173 v1，既有主题）

    /// 杂志卡布局：顶栏 + 头像 + 链接行（含QR） + 三栏统计 + 草坪 + 注脚。
    /// HOM-174 follow-up：链接区域右侧添加 QR 码。
    @ViewBuilder
    private var magazineBody: some View {
        VStack(spacing: 0) {
            topBar
            avatarSection
                .padding(.top, 14)
                .padding(.bottom, 10)
            // HOM-174：链接行 + QR 码
            magazineLinksSection
                .padding(.bottom, 10)
            divider
            statsSection
                .padding(.vertical, 12)
            divider
            contributionSection
                .padding(.vertical, 12)
            divider
            footerBar
                .padding(.top, 8)
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 20)
    }

    /// Magazine 布局的链接行：左侧链接列表 + 右侧 QR 码。
    @ViewBuilder
    private var magazineLinksSection: some View {
        HStack(alignment: .top, spacing: 12) {
            // 左侧链接列表
            profileLinksSection

            // 右侧 QR 码
            qrCodeView
        }
    }

    // MARK: - 顶栏

    /// 顶栏：左侧"✦ STARCAT" 品牌名，右侧"OPEN SOURCE · DEVELOPER ID" 副标题。
    /// 字号刻意拉小（11pt）+ 大字间距（tracking），呼应"杂志封面"质感而非 UI 标题。
    @ViewBuilder
    private var topBar: some View {
        HStack(alignment: .center, spacing: 8) {
            Text("✦ STARCAT")
                .font(.system(size: 13, weight: .black, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .tracking(2)

            Spacer()

            HStack(spacing: 5) {
                Image(systemName: "sparkles")
                    .font(.system(size: 8, weight: .bold))
                    .foregroundStyle(palette.accent)

                Text("sharecard.card.tagline")
                    .font(.system(size: 9, weight: .semibold, design: .monospaced))
                    .foregroundStyle(palette.secondaryText)
                    .tracking(1.2)
            }
            .padding(.horizontal, 12)
            .padding(.vertical, 6)
            .background(
                Capsule()
                    .fill(palette.cardBackgroundSecondary.opacity(0.58))
                    .overlay(
                        Capsule()
                            .stroke(palette.divider.opacity(0.85), lineWidth: 0.8)
                    )
            )
        }
    }

    // MARK: - 头像 + 身份区

    /// 头像（96pt 圆形）+ 显示名 + @login + Bio + Pro 标识。
    /// Bio 最多 2 行；nil/空串时省略不留空白。
    /// Pro 用户在头像右下角显示 Pro 徽章。
    @ViewBuilder
    private var avatarSection: some View {
        VStack(spacing: 8) {
            magazineAvatarRing

            VStack(spacing: 2) {
                // 显示名（name 优先，缺失 fallback login）
                Text(displayName)
                    .font(.system(size: 22, weight: .bold, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)

                // HOM-174：仅在 name 与 login 不同时显示 @login，避免重复（如 "dong4j" + "@dong4j"）
                if user.name?.lowercased() != user.login.lowercased() {
                    Text("@\(user.login)")
                        .font(.system(size: 12, weight: .medium, design: .monospaced))
                        .foregroundStyle(palette.secondaryText)
                        .lineLimit(1)
                }
            }

            // Bio：非空才渲染。Bio 中 GitHub 不渲染 @mention/markdown，原样平文本展示。
            if let bio = user.bio, !bio.isEmpty {
                Text("“\(bio)”")
                    .font(.system(size: 11.5, weight: .regular))
                    .italic()
                    .foregroundStyle(palette.secondaryText)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .padding(.top, 2)
                    .padding(.horizontal, 8)
            }
        }
        .frame(maxWidth: .infinity)
    }

    /// Magazine 头像外圈：内层暗色圆盘 + 蓝紫渐变双环 + 轻微 glow。
    ///
    /// 第二张参考图的重点不是换头像，而是让头像像“被光环托起”的主视觉。
    /// 这里保持头像位置和 PRO 徽章锚点不变，只加强外圈层次，避免影响下方 QR 布局。
    @ViewBuilder
    private var magazineAvatarRing: some View {
        let avatarSize: CGFloat = 96
        ZStack(alignment: .bottomTrailing) {
            ZStack {
                Circle()
                    .fill(palette.cardBackgroundSecondary.opacity(0.72))
                    .frame(width: avatarSize + 18, height: avatarSize + 18)
                    .shadow(color: palette.accent.opacity(0.28), radius: 16, y: 4)

                Circle()
                    .stroke(
                        LinearGradient(
                            colors: [
                                Color.fromHex6(0x8B5CF6),
                                palette.accent,
                                Color.fromHex6(0x38BDF8)
                            ],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        ),
                        lineWidth: 3
                    )
                    .frame(width: avatarSize + 14, height: avatarSize + 14)

                Circle()
                    .stroke(palette.primaryText.opacity(0.18), lineWidth: 1)
                    .frame(width: avatarSize + 6, height: avatarSize + 6)

                RemoteAvatar(urlString: user.avatarUrl, size: avatarSize, showBorder: false)
                    .overlay(
                        Circle()
                            .stroke(palette.cardBackground.opacity(0.88), lineWidth: 1.5)
                    )
            }

            if isProUser {
                shareCardProBadge
                    .offset(x: 10, y: 0)
            }
        }
        .frame(width: avatarSize + 20, height: avatarSize + 20)
    }

    // MARK: - 三栏统计

    /// 三栏：Starred / Followers / Following。
    /// Starred 走本地 `starredCount`（与 sidebar 同源），followers/following 走 `/user` 字段。
    @ViewBuilder
    private var statsSection: some View {
        HStack(spacing: 8) {
            statCell(
                value: starredCount,
                labelKey: "sharecard.stats.starred",
                symbol: "star.fill",
                iconColor: Color.fromHex6(0xFFD43B)
            )
            statCell(
                value: user.followers ?? 0,
                labelKey: "sharecard.stats.followers",
                symbol: "person.2.fill",
                iconColor: Color.fromHex6(0x38BDF8)
            )
            statCell(
                value: user.following ?? 0,
                labelKey: "sharecard.stats.following",
                symbol: "person.fill",
                iconColor: Color.fromHex6(0x7CFC3A)
            )
        }
    }

    /// 三栏分隔条：高度 32pt 的细分隔线，颜色用主题 divider 色。
    private var statDivider: some View {
        Rectangle()
            .fill(palette.divider)
            .frame(width: 1, height: 32)
    }

    /// 单栏统计卡：图标 + 数字（大字）+ label（小字 secondary）。
    /// 数字用 SF Rounded + monospacedDigit 保证三栏对齐。
    @ViewBuilder
    private func statCell(value: Int, labelKey: LocalizedStringKey, symbol: String, iconColor: Color) -> some View {
        VStack(spacing: 4) {
            HStack(spacing: 4) {
                Image(systemName: symbol)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(iconColor)
                Text(formatCompact(value))
                    .font(.system(size: 20, weight: .heavy, design: .rounded))
                    .monospacedDigit()
                    .foregroundStyle(palette.primaryText)
            }
            Text(labelKey)
                .font(.system(size: 9, weight: .medium))
                .foregroundStyle(palette.tertiaryText)
                .tracking(1)
                .textCase(.uppercase)
        }
        .padding(.vertical, 9)
        .frame(maxWidth: .infinity)
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(palette.cardBackgroundSecondary.opacity(0.58))
                .overlay(
                    RoundedRectangle(cornerRadius: 14)
                        .stroke(palette.divider.opacity(0.72), lineWidth: 0.8)
                )
                .shadow(color: .black.opacity(0.12), radius: 6, y: 3)
        )
    }

    /// 新版式复用的紧凑统计胶囊。
    /// 它承载真实数据，不做装饰性渐变；用 cardBackgroundSecondary 保持和当前配色同源。
    @ViewBuilder
    private func compactStatPill(symbol: String, value: Int, labelKey: LocalizedStringKey) -> some View {
        HStack(spacing: 6) {
            Image(systemName: symbol)
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(palette.accent)
            VStack(alignment: .leading, spacing: 1) {
                Text(formatCompact(value))
                    .font(.system(size: 15, weight: .bold, design: .rounded))
                    .monospacedDigit()
                    .foregroundStyle(palette.primaryText)
                Text(labelKey)
                    .font(.system(size: 7, weight: .semibold, design: .monospaced))
                    .tracking(0.5)
                    .textCase(.uppercase)
                    .foregroundStyle(palette.tertiaryText)
            }
        }
        .padding(.horizontal, 9)
        .padding(.vertical, 7)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(palette.cardBackgroundSecondary.opacity(0.72))
                .overlay(
                    RoundedRectangle(cornerRadius: 10)
                        .stroke(palette.divider, lineWidth: 0.7)
                )
        )
    }

    /// 数据看板的大号统计卡。和 compactStatPill 分开，避免一个组件塞过多参数。
    @ViewBuilder
    private func dashboardMetric(symbol: String, value: Int, labelKey: LocalizedStringKey) -> some View {
        HStack(alignment: .center, spacing: 7) {
            Image(systemName: symbol)
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(palette.accent)
                .frame(width: 14)

            VStack(alignment: .leading, spacing: 1) {
                Text(formatCompact(value))
                    .font(.system(size: 16, weight: .black, design: .rounded))
                    .monospacedDigit()
                    .foregroundStyle(palette.primaryText)
                Text(labelKey)
                    .font(.system(size: 7, weight: .semibold, design: .monospaced))
                    .tracking(0.5)
                    .textCase(.uppercase)
                    .foregroundStyle(palette.tertiaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.7)
            }
        }
        .padding(.horizontal, 10)
        .padding(.vertical, 8)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 12)
                .fill(palette.cardBackgroundSecondary.opacity(0.7))
                .overlay(
                    RoundedRectangle(cornerRadius: 12)
                        .stroke(palette.divider, lineWidth: 0.7)
                )
        )
    }

    /// 终端版式的一行键值输出。key 是固定设计文案，不走 i18n，避免导出图随语言变成伪命令。
    @ViewBuilder
    private func terminalLine(key: String, value: String) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 8) {
            Text(verbatim: "\(key):")
                .font(.system(size: 11, weight: .semibold, design: .monospaced))
                .foregroundStyle(palette.accent)
                .frame(width: 70, alignment: .leading)
            Text(verbatim: value)
                .font(.system(size: 11, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.secondaryText)
                .lineLimit(2)
                .minimumScaleFactor(0.75)
        }
    }

    /// 把整数格式化成紧凑形式（1234 → 1.2K，4823 → 4.8K，999 → 999）。
    /// 卡片宽度受限，5 位以上数字会挤占其他栏，4 位以上自动 K-suffix。
    private func formatCompact(_ n: Int) -> String {
        if n < 1000 { return String(n) }
        let k = Double(n) / 1000.0
        return String(format: "%.1fK", k)
    }

    /// Dashboard facts 里使用的紧凑 key-value 行。
    @ViewBuilder
    private func dashboardFactRow(symbol: String, labelKey: LocalizedStringKey, value: String) -> some View {
        HStack(spacing: 7) {
            Image(systemName: symbol)
                .font(.system(size: 9, weight: .bold))
                .foregroundStyle(palette.accent)
                .frame(width: 13)

            VStack(alignment: .leading, spacing: 1) {
                Text(labelKey)
                    .font(.system(size: 6.5, weight: .semibold, design: .monospaced))
                    .tracking(0.5)
                    .textCase(.uppercase)
                    .foregroundStyle(palette.tertiaryText)
                    .lineLimit(1)
                Text(value)
                    .font(.system(size: 9, weight: .semibold))
                    .foregroundStyle(palette.secondaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.75)
            }
        }
    }

    /// 从 GitHub profile 本地字段组装 Dashboard 的 Profile Facts。
    private var dashboardProfileFacts: [DashboardFact] {
        var facts: [DashboardFact] = []

        if let company = trimmed(user.company) {
            facts.append(DashboardFact(symbol: "building.2.fill", labelKey: "sharecard.dashboard.fact.company", value: company))
        }
        if let location = trimmed(user.location) {
            facts.append(DashboardFact(symbol: "location.fill", labelKey: "sharecard.dashboard.fact.location", value: location))
        }
        if let twitter = trimmed(user.twitterUsername) {
            facts.append(DashboardFact(symbol: "at", labelKey: "sharecard.dashboard.fact.x", value: "@\(twitter)"))
        }
        if let email = trimmed(user.email) {
            facts.append(DashboardFact(symbol: "envelope.fill", labelKey: "sharecard.dashboard.fact.email", value: email))
        }

        // 用户资料字段可能很少。保底放 GitHub 主页，避免整块 profile facts 只剩一行。
        if facts.count < 3 {
            facts.append(DashboardFact(
                symbol: "link",
                labelKey: "sharecard.dashboard.fact.github",
                value: user.htmlUrl ?? "github.com/\(user.login)"
            ))
        }

        return Array(facts.prefix(4))
    }

    /// 从草坪 payload 派生 Dashboard 的 Activity Facts，不额外发起网络请求。
    private var dashboardActivityFacts: [DashboardFact] {
        let days = contribution?.weeks.flatMap(\.contributionDays) ?? []
        let activeDays = days.filter { $0.contributionCount > 0 }.count
        let activeWeeks = contribution?.weeks.filter { week in
            week.contributionDays.contains { $0.contributionCount > 0 }
        }.count ?? 0
        let bestDay = days.map(\.contributionCount).max() ?? 0

        return [
            DashboardFact(symbol: "calendar", labelKey: "sharecard.dashboard.fact.activeDays", value: "\(activeDays)"),
            DashboardFact(symbol: "square.grid.3x3.fill", labelKey: "sharecard.dashboard.fact.activeWeeks", value: "\(activeWeeks)"),
            DashboardFact(symbol: "bolt.fill", labelKey: "sharecard.dashboard.fact.bestDay", value: "\(bestDay)"),
            DashboardFact(symbol: "chart.bar.fill", labelKey: "sharecard.dashboard.fact.contributions", value: formatCompact(contribution?.totalContributions ?? 0))
        ]
    }

    /// 去掉空白后的可展示字符串。放在本文件内，避免到处重复 trimming。
    private func trimmed(_ value: String?) -> String? {
        guard let value else { return nil }
        let text = value.trimmingCharacters(in: .whitespacesAndNewlines)
        return text.isEmpty ? nil : text
    }

    /// 分享卡内展示 URL 时去掉 scheme / 末尾斜杠，避免小尺寸卡片被 `https://` 占掉有效宽度。
    private func compactURLDisplay(_ value: String) -> String {
        value
            .replacingOccurrences(of: "https://", with: "")
            .replacingOccurrences(of: "http://", with: "")
            .trimmingCharacters(in: CharacterSet(charactersIn: "/"))
    }

    // MARK: - 草坪

    /// 贡献草坪：53 周 × 7 天，颜色按当前 `colorSet.palette.contribution` 渲染。
    ///
    /// 不复用 `ContributionGraphView` 是因为：
    /// - 那个 view 强依赖 `@Environment(\.colorScheme)` 自动切 light/dark 调色板，
    ///   导出图需要固定主题色而不是跟随系统。
    /// - 那个 view 还挂了贪吃蛇 animator + TimelineView，导出图都不需要。
    /// - 重新写一份纯静态版本（约 30 行 Canvas）反而更轻、更可控。
    @ViewBuilder
    private var contributionSection: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("sharecard.contribution.title")
                    .font(.system(size: 9, weight: .semibold, design: .monospaced))
                    .tracking(1.5)
                    .foregroundStyle(palette.tertiaryText)
                Spacer()
                if let total = contribution?.totalContributions {
                    Text(String(format: String.l10n("sharecard.contribution.totalCount"), total))
                        .font(.system(size: 9, weight: .semibold, design: .monospaced))
                        .foregroundStyle(palette.secondaryText)
                }
            }

            ContributionStaticGrid(
                payload: contribution,
                palette: palette.contribution,
                pixelated: style == .terminal
            )
            .aspectRatio(style == .terminal ? 53.0 / 7.0 : 53.0 / 7.0 * (10.0 / 12.0), contentMode: .fit)
            // 53 列 × 7 行 = aspect 7.57:1（10pt 宽 × 12pt 高）；
            // 卡片可用宽度 ~352pt（400 - 24×2 padding），渲染高度 ~46pt 视觉合适

            contributionMonthAxis
        }
    }

    /// 草坪月份标注：尽量从 GraphQL 返回的每周日期推导，数据为空时使用最近一年占位。
    @ViewBuilder
    private var contributionMonthAxis: some View {
        HStack {
            ForEach(contributionMonthTicks) { tick in
                Text(tick.label)
                    .font(.system(size: 8.5, weight: .medium, design: .rounded))
                    .foregroundStyle(palette.secondaryText)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
        }
        .padding(.top, 1)
    }

    /// 取 7 个近似列位置标月份，覆盖从一年前到当前月的读图路径。
    private var contributionMonthTicks: [ContributionMonthTick] {
        let columns = [0, 9, 18, 27, 36, 45, 52]
        return columns.enumerated().map { index, column in
            ContributionMonthTick(id: index, label: contributionMonthLabel(forColumn: column))
        }
    }

    private func contributionMonthLabel(forColumn column: Int) -> String {
        let date = contributionDate(forColumn: column) ?? fallbackContributionDate(forColumn: column)
        let formatter = DateFormatter()
        formatter.locale = locale
        formatter.calendar = Calendar(identifier: .gregorian)
        formatter.setLocalizedDateFormatFromTemplate("MMM")
        return formatter.string(from: date)
    }

    private func contributionDate(forColumn column: Int) -> Date? {
        guard let weeks = contribution?.weeks, !weeks.isEmpty else { return nil }

        let startColumn = max(0, 53 - weeks.count)
        let rawWeekIndex = column - startColumn
        guard rawWeekIndex >= 0 else { return nil }

        let weekIndex = min(rawWeekIndex, weeks.count - 1)
        guard let dateString = weeks[weekIndex].contributionDays.first?.date
                ?? weeks[weekIndex].contributionDays.last?.date else {
            return nil
        }
        return parseGitHubDate(dateString)
    }

    private func fallbackContributionDate(forColumn column: Int) -> Date {
        var calendar = Calendar(identifier: .gregorian)
        calendar.locale = locale
        let now = Date()
        let start = calendar.date(byAdding: .month, value: -12, to: now) ?? now
        let monthOffset = Int((Double(column) / 52.0 * 12.0).rounded())
        return calendar.date(byAdding: .month, value: monthOffset, to: start) ?? now
    }

    private func parseGitHubDate(_ value: String) -> Date? {
        let parts = value.split(separator: "-").compactMap { Int($0) }
        guard parts.count == 3 else { return nil }
        var components = DateComponents()
        components.calendar = Calendar(identifier: .gregorian)
        components.year = parts[0]
        components.month = parts[1]
        components.day = parts[2]
        return components.date
    }

    // MARK: - 链接行（HOM-174 新增）

    /// 个人主页链接行：GitHub 主页、blog、email 等。
    /// HOM-174 follow-up：
    /// - 链接改成每行一个（VStack 布局）
    /// - 图标带绿色背景
    /// - 最多显示 3 个链接
    @ViewBuilder
    private var profileLinksSection: some View {
        let links = Array(makeProfileLinks().prefix(3))
        if !links.isEmpty {
            VStack(alignment: .leading, spacing: 6) {
                ForEach(links) { link in
                    profileLinkItem(link: link)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }

    /// 单个链接项：绿色背景图标 + 文字。
    @ViewBuilder
    private func profileLinkItem(link: ShareCardLinkItem) -> some View {
        HStack(spacing: 6) {
            // 绿色背景图标
            ZStack {
                RoundedRectangle(cornerRadius: 4)
                    .fill(Color.green.opacity(0.2))
                    .frame(width: 20, height: 20)
                Image(systemName: link.symbolName)
                    .font(.system(size: 10, weight: .medium))
                    .foregroundStyle(.green)
            }
            Text(link.displayText)
                .font(.system(size: 10, weight: .medium))
                .foregroundStyle(palette.secondaryText)
                .lineLimit(1)
        }
    }

    /// 构建链接列表（用于分享卡导出图的静态展示）。
    private func makeProfileLinks() -> [ShareCardLinkItem] {
        var items: [ShareCardLinkItem] = []

        // GitHub 主页（始终显示）
        items.append(ShareCardLinkItem(
            symbolName: "link",
            displayText: user.htmlUrl ?? "github.com/\(user.login)"
        ))

        // blog / homepage
        if let blog = user.blog?.trimmingCharacters(in: .whitespacesAndNewlines), !blog.isEmpty {
            let displayText = blog.hasPrefix("http") ? blog : "https://\(blog)"
            items.append(ShareCardLinkItem(
                symbolName: "globe",
                displayText: displayText
            ))
        }

        // email
        if let email = user.email?.trimmingCharacters(in: .whitespacesAndNewlines), !email.isEmpty {
            items.append(ShareCardLinkItem(
                symbolName: "envelope",
                displayText: email
            ))
        }

        return items
    }

    // MARK: - 开发语言块（分享卡专用）

    /// 前 5 个开发语言切片。数据口径来自 DeveloperLanguageService，不回退到 starred 项目语言。
    private var languageSlices: [ShareCardLanguageSlice] {
        guard let developerLanguages, developerLanguages.totalBytes > 0 else { return [] }
        return developerLanguages.languages.prefix(5).map { entry in
            ShareCardLanguageSlice(
                name: entry.name,
                ratio: entry.ratio,
                color: LanguageColor.color(for: entry.name)
            )
        }
    }

    @ViewBuilder
    private var languageEmptyState: some View {
        let key = developerLanguages == nil ? "sharecard.languages.loading" : "sharecard.languages.empty"
        Text(LocalizedStringKey(key))
            .font(.system(size: 10, weight: .medium, design: style == .terminal ? .monospaced : .rounded))
            .foregroundStyle(palette.secondaryText)
            .lineLimit(2)
            .minimumScaleFactor(0.78)
    }

    @ViewBuilder
    private func languageStackedBar(width: CGFloat, height: CGFloat) -> some View {
        let slices = languageSlices
        let spacing: CGFloat = 2
        let visibleRatio = max(slices.reduce(0) { $0 + $1.ratio }, 0.0001)
        let availableWidth = max(0, width - CGFloat(max(0, slices.count - 1)) * spacing)

        HStack(spacing: spacing) {
            ForEach(slices) { slice in
                RoundedRectangle(cornerRadius: height / 2)
                    .fill(slice.color)
                    .frame(width: max(5, availableWidth * slice.ratio / visibleRatio), height: height)
            }
            Spacer(minLength: 0)
        }
        .frame(width: width, height: height, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: height / 2)
                .fill(palette.divider.opacity(0.45))
        )
    }

    @ViewBuilder
    private var languageLegendGrid: some View {
        let slices = languageSlices
        VStack(alignment: .leading, spacing: 5) {
            ForEach(Array(stride(from: 0, to: slices.count, by: 2)), id: \.self) { start in
                HStack(spacing: 8) {
                    languageLegendItem(slices[start])
                    if start + 1 < slices.count {
                        languageLegendItem(slices[start + 1])
                    }
                    Spacer(minLength: 0)
                }
            }
        }
    }

    @ViewBuilder
    private func languageLegendItem(_ slice: ShareCardLanguageSlice) -> some View {
        HStack(spacing: 4) {
            Circle()
                .fill(slice.color)
                .frame(width: 6, height: 6)
            Text(verbatim: "\(slice.name) \(formatPercent(slice.ratio))")
                .font(.system(size: 8.2, weight: .semibold, design: .rounded))
                .foregroundStyle(palette.secondaryText)
                .lineLimit(1)
                .minimumScaleFactor(0.55)
        }
        .frame(maxWidth: 145, alignment: .leading)
    }

    @ViewBuilder
    private func terminalLanguageRow(_ slice: ShareCardLanguageSlice) -> some View {
        let maxRatio = max(languageSlices.first?.ratio ?? slice.ratio, 0.0001)
        let segmentCount = 24
        let filledSegments = max(1, Int(ceil(Double(segmentCount) * slice.ratio / maxRatio)))

        HStack(spacing: 7) {
            Text(verbatim: slice.name)
                .font(.system(size: 8.5, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.accent)
                .lineLimit(1)
                .minimumScaleFactor(0.55)
                .frame(width: 78, alignment: .leading)

            HStack(spacing: 2) {
                ForEach(0..<segmentCount, id: \.self) { index in
                    Rectangle()
                        .fill(index < filledSegments ? slice.color : palette.accent.opacity(0.10))
                        .frame(width: 6, height: 7)
                }
            }
            .frame(width: 190, alignment: .leading)

            Text(verbatim: formatPercent(slice.ratio))
                .font(.system(size: 8.5, weight: .semibold, design: .monospaced))
                .foregroundStyle(palette.accent)
                .monospacedDigit()
                .frame(width: 42, alignment: .trailing)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    private func formatPercent(_ ratio: Double) -> String {
        String(format: "%.1f%%", max(0, ratio) * 100)
    }

    // MARK: - 通用元素

    /// Pro 用户彩虹渐变徽章。杂志卡 / ID 卡共用，由调用方决定挂载位置。
    @ViewBuilder
    private var shareCardProBadge: some View {
        Text("PRO")
            .font(.system(size: 8, weight: .black))
            .foregroundStyle(.white)
            .padding(.horizontal, 5)
            .padding(.vertical, 2)
            .background {
                Capsule()
                    .fill(
                        LinearGradient(
                            colors: [.yellow, .orange, .pink],
                            startPoint: .topLeading,
                            endPoint: .bottomTrailing
                        )
                    )
                    .shadow(color: .black.opacity(0.18), radius: 2, y: 1)
            }
            .overlay {
                Capsule()
                    .stroke(.white.opacity(0.75), lineWidth: 0.7)
            }
    }

    /// 全宽细分隔线（顶/中/底分区用）。
    private var divider: some View {
        Rectangle()
            .fill(palette.divider)
            .frame(height: 0.7)
    }

    /// 底部品牌注脚：> Generated by Starcat · starcat.ink
    /// 用等宽字 + 终端命令提示符风格，向 Gemini / Claude 方案致敬。
    @ViewBuilder
    private var footerBar: some View {
        HStack {
            Text("sharecard.card.generatedBy")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.tertiaryText)
                .tracking(0.5)
            Spacer()
            Text("starcat.ink")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.accent)
        }
    }

    // MARK: - ID Card 布局（HOM-173 v2，2026-06-06 新增）

    /// ID 卡布局：大圆角头像主图 + 用户名 + Bio + 链接行 + 底部（stats + QR + footer）。
    /// HOM-174 follow-up：
    /// - 添加链接行（每行一个，带绿色背景图标）
    /// - 底部添加 Generated by Starcat
    /// - 优化垂直间距减少空白
    ///
    /// 布局结构：
    /// - 顶部：大圆角矩形头像（卡片宽度减边距），底部加渐变带过渡到下方文字
    /// - 中部：用户名 + verified 勾 + Bio（最多 2 行，nil/空 时省略）
    /// - 链接行（GitHub / homepage / email，每行一个）
    /// - 底部：3 个 pill stat（⭐ Starred + 👥 Followers + 👥 Following）+ QR 码
    /// - 底部注脚：Generated by Starcat
    @ViewBuilder
    private var idCardBody: some View {
        VStack(spacing: 0) {
            idCardAvatar
                .padding(.top, 16)

            VStack(alignment: .leading, spacing: 4) {
                idCardIdentity
                idCardBio
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, 24)
            .padding(.top, 14)

            // 链接行
            profileLinksSection
                .padding(.horizontal, 24)
                .padding(.top, 10)

            Spacer(minLength: 8)

            idCardBottomRow
                .padding(.horizontal, 24)

            // HOM-174：底部注脚
            idCardFooter
                .padding(.horizontal, 24)
                .padding(.top, 8)
                .padding(.bottom, 16)
        }
    }

    // MARK: - Poster 布局

    /// 海报布局：大头像与名字作为第一视觉锚点，下半区放统计、草坪和 QR。
    @ViewBuilder
    private var posterBody: some View {
        VStack(spacing: 0) {
            topBar

            Spacer(minLength: 16)

            ZStack(alignment: .bottomTrailing) {
                RemoteAvatar(urlString: user.avatarUrl, size: 126, showBorder: false)
                    .overlay(Circle().stroke(palette.accent, lineWidth: 3))
                    .shadow(color: palette.accent.opacity(0.25), radius: 16, y: 6)

                // Pro 徽章跟随头像，而不是放进正文信息区，避免不同版式漏显示。
                if isProUser {
                    shareCardProBadge
                        .offset(x: 8, y: 0)
                }
            }

            VStack(spacing: 4) {
                Text(displayName)
                    .font(.system(size: 28, weight: .black, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.65)
                Text("@\(user.login)")
                    .font(.system(size: 12, weight: .medium, design: .monospaced))
                    .foregroundStyle(palette.secondaryText)
            }
            .padding(.top, 12)

            if let bio = user.bio, !bio.isEmpty {
                Text("“\(bio)”")
                    .font(.system(size: 12, weight: .regular))
                    .italic()
                    .foregroundStyle(palette.secondaryText)
                    .multilineTextAlignment(.center)
                    .lineLimit(2)
                    .padding(.horizontal, 18)
                    .padding(.top, 8)
            }

            Spacer(minLength: 18)

            posterStatsRibbon
                .padding(.bottom, 16)

            HStack(alignment: .bottom, spacing: 18) {
                contributionSection
                    .frame(maxWidth: .infinity, alignment: .leading)
                qrCodeView
            }

            Spacer(minLength: 14)

            footerBar
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 20)
    }

    /// 海报统计横幅：比 magazine 三栏更紧凑，服务于视觉扫读。
    @ViewBuilder
    private var posterStatsRibbon: some View {
        HStack(spacing: 8) {
            compactStatPill(symbol: "star.fill", value: starredCount, labelKey: "sharecard.stats.starred")
            compactStatPill(symbol: "person.2.fill", value: user.followers ?? 0, labelKey: "sharecard.stats.followers")
            compactStatPill(symbol: "person.fill", value: user.following ?? 0, labelKey: "sharecard.stats.following")
        }
    }

    // MARK: - Dashboard 布局

    /// 数据看板布局：统计卡片和草坪优先，适合强调 GitHub 资产与活跃度。
    @ViewBuilder
    private var dashboardBody: some View {
        VStack(spacing: 11) {
            topBar

            HStack(alignment: .center, spacing: 14) {
                ZStack(alignment: .bottomTrailing) {
                    RemoteAvatar(urlString: user.avatarUrl, size: 74, showBorder: false)
                        .overlay(Circle().stroke(palette.accent, lineWidth: 2))

                    if isProUser {
                        shareCardProBadge
                            .offset(x: 6, y: 0)
                    }
                }
                VStack(alignment: .leading, spacing: 4) {
                    Text(displayName)
                        .font(.system(size: 22, weight: .bold, design: .rounded))
                        .foregroundStyle(palette.primaryText)
                        .lineLimit(1)
                        .minimumScaleFactor(0.7)
                    Text("@\(user.login)")
                        .font(.system(size: 11, weight: .medium, design: .monospaced))
                        .foregroundStyle(palette.secondaryText)
                    if let bio = user.bio, !bio.isEmpty {
                        Text(bio)
                            .font(.system(size: 11, weight: .regular))
                            .foregroundStyle(palette.secondaryText)
                            .lineLimit(2)
                    }
                }
                Spacer(minLength: 8)
                qrCodeView
            }

            VStack(spacing: 8) {
                HStack(spacing: 8) {
                    dashboardMetric(symbol: "star.fill", value: starredCount, labelKey: "sharecard.stats.starred")
                    dashboardMetric(symbol: "shippingbox.fill", value: user.publicRepos ?? 0, labelKey: "sharecard.stats.repos")
                }
                HStack(spacing: 8) {
                    dashboardMetric(symbol: "chart.bar.fill", value: contribution?.totalContributions ?? 0, labelKey: "sharecard.dashboard.metric.contributions")
                    dashboardMetric(symbol: "person.2.fill", value: user.followers ?? 0, labelKey: "sharecard.stats.followers")
                }
            }

            divider

            contributionSection

            dashboardFactsPanel

            Spacer(minLength: 0)

            footerBar
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 20)
    }

    /// 数据看板的双列 facts 信息块。
    ///
    /// 第 4 种样式的核心目标是“看板”。这里尽量使用已经缓存的 profile / 草坪字段，
    /// 不为一张分享卡新增网络请求；空 profile 字段会自动跳过。
    @ViewBuilder
    private var dashboardFactsPanel: some View {
        HStack(alignment: .top, spacing: 14) {
            VStack(alignment: .leading, spacing: 7) {
                dashboardFactsTitle("sharecard.dashboard.profileFacts")
                ForEach(dashboardProfileFacts) { fact in
                    dashboardFactRow(symbol: fact.symbol, labelKey: fact.labelKey, value: fact.value)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)

            VStack(alignment: .leading, spacing: 7) {
                dashboardFactsTitle("sharecard.dashboard.activityFacts")
                ForEach(dashboardActivityFacts) { fact in
                    dashboardFactRow(symbol: fact.symbol, labelKey: fact.labelKey, value: fact.value)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .padding(12)
        .background(
            RoundedRectangle(cornerRadius: 14)
                .fill(palette.cardBackgroundSecondary.opacity(0.48))
                .overlay(
                    RoundedRectangle(cornerRadius: 14)
                        .stroke(palette.divider, lineWidth: 0.7)
                )
        )
    }

    @ViewBuilder
    private func dashboardFactsTitle(_ key: LocalizedStringKey) -> some View {
        Text(key)
            .font(.system(size: 7, weight: .bold, design: .monospaced))
            .tracking(1.2)
            .textCase(.uppercase)
            .foregroundStyle(palette.tertiaryText)
    }

    // MARK: - Pass 布局

    /// 通行证布局：身份信息像 badge 一样分栏展示，QR 是右侧固定识别点。
    @ViewBuilder
    private var passBody: some View {
        VStack(spacing: 0) {
            topBar
                .padding(.bottom, 16)

            passIdentityPanel

            passStatsBlock
                .padding(.top, 14)

            passLinkAndQRPanel
                .padding(.top, 12)

            divider
                .padding(.vertical, 14)

            contributionSection

            Spacer(minLength: 0)

            footerBar
        }
        .padding(.horizontal, 24)
        .padding(.vertical, 20)
    }

    /// 通行证身份面板：把头像与身份文本合并成一块，减少截图里“头像一块、文字一块”的割裂感。
    @ViewBuilder
    private var passIdentityPanel: some View {
        HStack(alignment: .center, spacing: 16) {
            ZStack(alignment: .bottomTrailing) {
                RemoteAvatar(urlString: user.avatarUrl, size: 104, showBorder: false)
                    .clipShape(Circle())
                    .overlay(
                        Circle()
                            .stroke(palette.accent, lineWidth: 2.2)
                    )
                    .shadow(color: palette.accent.opacity(0.20), radius: 10, y: 4)

                if isProUser {
                    shareCardProBadge
                        .offset(x: 8, y: 0)
                }
            }

            VStack(alignment: .leading, spacing: 7) {
                Text(displayName)
                    .font(.system(size: 25, weight: .black, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.65)
                Text("@\(user.login)")
                    .font(.system(size: 12, weight: .medium, design: .monospaced))
                    .foregroundStyle(palette.secondaryText)
                if let bio = user.bio, !bio.isEmpty {
                    Text(bio)
                        .font(.system(size: 12, weight: .regular))
                        .foregroundStyle(palette.secondaryText)
                        .lineLimit(3)
                }
            }

            Spacer(minLength: 0)
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 18)
                .fill(palette.cardBackgroundSecondary.opacity(0.38))
                .overlay(
                    RoundedRectangle(cornerRadius: 18)
                        .stroke(palette.divider, lineWidth: 0.7)
                )
        )
    }

    /// 通行证的链接与 QR 识别区。QR 放在链接右侧，形成“身份资料 → 可扫码验证”的连续读序。
    @ViewBuilder
    private var passLinkAndQRPanel: some View {
        HStack(alignment: .center, spacing: 14) {
            profileLinksSection
                .frame(maxWidth: .infinity, alignment: .leading)

            qrCodeView
        }
        .padding(12)
        .background(
            RoundedRectangle(cornerRadius: 16)
                .fill(palette.cardBackgroundSecondary.opacity(0.34))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .stroke(palette.divider, lineWidth: 0.7)
                )
        )
    }

    /// 通行证下方统计块：横向密度高，避免和顶部身份区抢视觉。
    @ViewBuilder
    private var passStatsBlock: some View {
        HStack(spacing: 8) {
            compactStatPill(symbol: "star.fill", value: starredCount, labelKey: "sharecard.stats.starred")
            compactStatPill(symbol: "person.2.fill", value: user.followers ?? 0, labelKey: "sharecard.stats.followers")
            compactStatPill(symbol: "person.fill", value: user.following ?? 0, labelKey: "sharecard.stats.following")
        }
    }

    // MARK: - Prototype 布局（2026-06-25 新增四类）

    /// 社交资料卡：原型 1/2 合并。深色 / 浅色差异完全由 `colorSet` 承担。
    @ViewBuilder
    private var socialBody: some View {
        VStack(spacing: 9) {
            topBar
            prototypeIdentityBlock(avatarSize: 88, showsQRCode: true)
            prototypeStatsPanel
            prototypeLanguagePanel
            prototypeContributionPanel
            footerBar
        }
        .padding(.horizontal, 20)
        .padding(.vertical, 18)
        .overlay(alignment: .topTrailing) {
            Circle()
                .fill(palette.accent.opacity(colorSet == .lightCard ? 0.10 : 0.18))
                .frame(width: 92, height: 92)
                .blur(radius: 18)
                .offset(x: 28, y: -30)
        }
    }

    /// 冒险背景卡：还原原型 5 的“左侧资料 + 右侧完整插画背景 + 底部语言面板”结构。
    ///
    /// 这套不复用 prototype 四面板布局。原型的重点是插画背景作为主视觉，
    /// 如果继续叠头像 / QR / 草坪大面板，会把背景里的猫和草地都遮掉，视觉就偏离了。
    @ViewBuilder
    private var adventureBody: some View {
        VStack(alignment: .leading, spacing: 0) {
            adventureIdentityText
                .padding(.top, 6)

            adventureStatsRow
                .padding(.top, 16)

            Spacer(minLength: 0)

            // 冒险背景右侧猫咪占据统计区右半边；底部则需要同时容纳语言与草坪卡片。
            // 这里用一组紧凑面板替代单个贴底语言卡，避免 Starred 数字压到猫身，同时补回草坪信息。
            VStack(spacing: 8) {
                adventureLanguagePanel
                prototypeContributionPanel
            }
            .padding(.bottom, 8)

            footerBar
        }
        .padding(.horizontal, 22)
        .padding(.vertical, 18)
    }

    @ViewBuilder
    private var adventureIdentityText: some View {
        VStack(alignment: .leading, spacing: 8) {
            adventureIdentityHeader
            adventureSocialLinksBlock

            Text(user.bio?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty == false
                 ? user.bio!.trimmingCharacters(in: .whitespacesAndNewlines)
                 : "Passionate developer focused on creating high-quality, impactful software.")
                .font(.system(size: 10.8, weight: .semibold, design: .rounded))
                .foregroundStyle(palette.primaryText.opacity(0.72))
                .lineSpacing(2)
                .lineLimit(2)
                .minimumScaleFactor(0.78)
        }
        .frame(width: 282, alignment: .leading)
    }

    /// 冒险样式顶部身份行：头像 + 用户名两行 + 小 QR。
    ///
    /// 顶部插画左侧留白足够，头像和 QR 放在同一行能增强识别度；
    /// 仍限制在 282pt 宽度内，避免压到右侧主视觉。
    @ViewBuilder
    private var adventureIdentityHeader: some View {
        HStack(alignment: .center, spacing: 10) {
            decoratedAvatar(size: 52, borderWidth: 1.6)

            VStack(alignment: .leading, spacing: 2) {
                Text(displayName)
                    .font(.system(size: 34, weight: .heavy, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.45)

                Text(verbatim: "@\(user.login)")
                    .font(.system(size: 18, weight: .bold, design: .rounded))
                    .foregroundStyle(palette.primaryText.opacity(0.84))
                    .lineLimit(1)
                    .minimumScaleFactor(0.65)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .layoutPriority(1)

            adventureQRCodeView
        }
        .frame(width: 282, height: 62, alignment: .leading)
    }

    /// 冒险样式社交信息：替换原先写死的 slogan，把顶部留白变成真实 profile 信息。
    ///
    /// 这里只读 `GitHubUserDTO` 已有字段，不新增网络请求；缺失字段用占位文案保留布局稳定。
    @ViewBuilder
    private var adventureSocialLinksBlock: some View {
        let location = trimmed(user.location)
        let email = trimmed(user.email)
        let homepage = trimmed(user.blog).map(compactURLDisplay)
        let social = trimmed(user.twitterUsername).map { "@\($0)" }

        VStack(alignment: .leading, spacing: 5) {
            HStack(spacing: 8) {
                adventureSocialChip(
                    symbol: "mappin.and.ellipse",
                    text: location ?? String.l10n("sharecard.social.locationPlaceholder"),
                    isPlaceholder: location == nil
                )

                adventureSocialChip(
                    symbol: "envelope.fill",
                    text: email ?? String.l10n("sharecard.social.emailPlaceholder"),
                    isPlaceholder: email == nil
                )
            }

            adventureSocialChip(
                symbol: "link",
                text: homepage ?? String.l10n("sharecard.social.homepagePlaceholder"),
                isPlaceholder: homepage == nil
            )

            adventureSocialChip(
                symbol: "at",
                text: social ?? String.l10n("sharecard.social.socialPlaceholder"),
                isPlaceholder: social == nil
            )
        }
    }

    /// 冒险样式专用小 QR。
    ///
    /// `QRCodeGenerator` 输出黑色码点 + 透明背景；这里不加外部圆角容器，只给 QR 本体
    /// 垫一张同尺寸白底，保证暗色背景可扫码，同时把空间让给可能较长的用户名。
    @ViewBuilder
    private var adventureQRCodeView: some View {
        let url = profileURLString
        let qrSize: CGFloat = 40
        let qrImage = QRCodeGenerator.generate(text: url, sizePoints: qrSize)

        ZStack {
            Rectangle()
                .fill(Color.white)
                .frame(width: qrSize, height: qrSize)

            if let qrImage {
                Image(nsImage: qrImage)
                    .interpolation(.none)
                    .resizable()
                    .frame(width: qrSize, height: qrSize)
            } else {
                Image(systemName: "qrcode")
                    .font(.system(size: 24, weight: .regular))
                    .foregroundStyle(Color.black)
            }
        }
        .frame(width: qrSize, height: qrSize)
        .accessibilityLabel(Text(verbatim: url))
    }

    @ViewBuilder
    private func adventureSocialChip(symbol: String, text: String, isPlaceholder: Bool) -> some View {
        HStack(spacing: 4) {
            Image(systemName: symbol)
                .font(.system(size: 8.5, weight: .bold))
                .foregroundStyle(isDarkAdventureVariant ? palette.accent : Color.fromHex6(0xD97706))
                .frame(width: 12)

            Text(verbatim: text)
                .font(.system(size: 8.6, weight: .bold, design: .rounded))
                .foregroundStyle(palette.primaryText.opacity(isPlaceholder ? 0.46 : 0.72))
                .lineLimit(1)
                .minimumScaleFactor(0.55)
        }
        .frame(height: 15)
    }

    @ViewBuilder
    private var adventureStatsRow: some View {
        HStack(spacing: 8) {
            adventureStatItem(symbol: "shippingbox.fill",
                              value: user.publicRepos ?? 0,
                              labelKey: "sharecard.stats.repos",
                              color: Color.fromHex6(0x2AA7B8))
            adventureStatItem(symbol: "person.2.fill",
                              value: user.followers ?? 0,
                              labelKey: "sharecard.stats.followers",
                              color: Color.fromHex6(0x34B981))
            adventureStatItem(symbol: "person.2.fill",
                              value: user.following ?? 0,
                              labelKey: "sharecard.stats.following",
                              color: Color.fromHex6(0x3B82F6))
            adventureStatItem(symbol: "star.fill",
                              value: starredCount,
                              labelKey: "sharecard.stats.starred",
                              color: Color.fromHex6(0xF59E0B))
        }
        .frame(width: 248, alignment: .leading)
        .offset(x: -6)
    }

    @ViewBuilder
    private func adventureStatItem(symbol: String, value: Int, labelKey: LocalizedStringKey, color: Color) -> some View {
        VStack(spacing: 5) {
            Image(systemName: symbol)
                .font(.system(size: 16, weight: .bold))
                .foregroundStyle(color)
                .frame(width: 24, height: 24)
                .shadow(color: color.opacity(0.22), radius: 5, y: 2)

            Text(formatCompact(value))
                .font(.system(size: 17, weight: .bold, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .monospacedDigit()
                .lineLimit(1)
                .minimumScaleFactor(0.7)

            Text(labelKey)
                .font(.system(size: 8.2, weight: .semibold, design: .rounded))
                .foregroundStyle(palette.primaryText.opacity(0.68))
                .lineLimit(1)
                .minimumScaleFactor(0.55)
        }
        .frame(width: 56)
    }

    @ViewBuilder
    private var adventureLanguagePanel: some View {
        VStack(alignment: .leading, spacing: 7) {
            Text("sharecard.languages.title")
                .font(.system(size: 12, weight: .bold, design: .rounded))
                .foregroundStyle(palette.primaryText.opacity(0.82))

            if languageSlices.isEmpty {
                languageEmptyState
                    .frame(maxWidth: .infinity, minHeight: 40, alignment: .leading)
            } else {
                languageStackedBar(width: 326, height: 9)
                adventureLanguageLegendRow
            }
        }
        .padding(.horizontal, 12)
        .padding(.vertical, 8)
        .frame(width: 356, height: 82, alignment: .topLeading)
        .background { adventureGlassPanelBackground }
    }

    @ViewBuilder
    private var adventureLanguageLegendRow: some View {
        HStack(spacing: 7) {
            ForEach(languageSlices.prefix(5)) { slice in
                HStack(spacing: 3.5) {
                    Circle()
                        .fill(slice.color)
                        .frame(width: 6, height: 6)
                    Text(verbatim: "\(slice.name) \(formatPercent(slice.ratio))")
                        .font(.system(size: 7.4, weight: .semibold, design: .rounded))
                        .foregroundStyle(palette.primaryText.opacity(0.72))
                        .lineLimit(1)
                        .minimumScaleFactor(0.48)
                }
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }

    /// 聚光海报卡：原型 4/5 的渐变海报版本，布局与 adventure 同构但视觉更偏社交传播。
    @ViewBuilder
    private var spotlightBody: some View {
        ZStack {
            decorativeSpotlightOrnaments

            VStack(spacing: 10) {
                prototypeIdentityBlock(avatarSize: 84, showsQRCode: true)
                prototypeStatsPanel
                prototypeLanguagePanel
                prototypeContributionPanel
                footerBar
            }
            .padding(.horizontal, 20)
            .padding(.vertical, 18)
        }
    }

    /// 终端布局：原型 3，保留命令行视觉，但同样按“身份 / 统计 / 语言 / 草坪”四段组织。
    @ViewBuilder
    private var terminalBody: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack(spacing: 8) {
                Text(verbatim: "> \(displayName)")
                    .font(.system(size: 22, weight: .bold, design: .monospaced))
                    .foregroundStyle(palette.accent)
                    .lineLimit(1)
                    .minimumScaleFactor(0.72)
                Spacer()
                Text(verbatim: "GitHub")
                    .font(.system(size: 12, weight: .semibold, design: .monospaced))
                    .foregroundStyle(palette.accent)
            }

            terminalIdentityBlock
            terminalStatsBlock
            terminalLanguagePanel
            prototypeContributionPanel

            HStack {
                Text(verbatim: "$ github.com/\(user.login)")
                    .font(.system(size: 9, weight: .medium, design: .monospaced))
                    .foregroundStyle(palette.accent)
                    .lineLimit(1)
                Spacer()
                Text("sharecard.card.generatedBy")
                    .font(.system(size: 9, weight: .medium, design: .monospaced))
                    .foregroundStyle(palette.tertiaryText)
            }
        }
        .overlay(terminalPixelOverlay)
        .padding(.horizontal, 24)
        .padding(.vertical, 18)
    }

    /// 原型头像 + 基础信息块。右侧 QR 仅在空间足够的新版式中展示。
    @ViewBuilder
    private func prototypeIdentityBlock(avatarSize: CGFloat, showsQRCode: Bool) -> some View {
        HStack(alignment: .center, spacing: 12) {
            decoratedAvatar(size: avatarSize, borderWidth: 2)

            VStack(alignment: .leading, spacing: 5) {
                Text(displayName)
                    .font(.system(size: 27, weight: .heavy, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)
                    .minimumScaleFactor(0.65)

                Text(verbatim: "@\(user.login)")
                    .font(.system(size: 14, weight: .semibold, design: .rounded))
                    .foregroundStyle(palette.secondaryText)
                    .lineLimit(1)

                if let bio = user.bio?.trimmingCharacters(in: .whitespacesAndNewlines), !bio.isEmpty {
                    Text(bio)
                        .font(.system(size: 10.5, weight: .medium))
                        .foregroundStyle(palette.secondaryText)
                        .lineLimit(2)
                        .minimumScaleFactor(0.82)
                } else {
                    Text(verbatim: "Code · Explore · Build")
                        .font(.system(size: 10.5, weight: .semibold))
                        .foregroundStyle(palette.accent)
                        .lineLimit(1)
                }
            }

            Spacer(minLength: 0)

            if showsQRCode {
                compactQRCodeView
            }
        }
        .padding(12)
        .frame(height: 116)
        .background(prototypePanelBackground(cornerRadius: 18, opacity: style == .adventure ? 0.62 : 0.72))
    }

    /// 终端身份块：头像 + 命令输出 + 小 QR。
    @ViewBuilder
    private var terminalIdentityBlock: some View {
        HStack(spacing: 12) {
            decoratedAvatar(size: 74, borderWidth: 2)

            VStack(alignment: .leading, spacing: 5) {
                terminalLine(key: "login", value: "@\(user.login)")
                if let bio = user.bio?.trimmingCharacters(in: .whitespacesAndNewlines), !bio.isEmpty {
                    terminalLine(key: "bio", value: bio)
                } else {
                    terminalLine(key: "role", value: "open-source developer")
                }
            }

            Spacer(minLength: 0)
            compactQRCodeView
        }
        .padding(10)
        .frame(height: 96)
        .background(prototypePanelBackground(cornerRadius: 8, opacity: 0.80))
    }

    /// 后四类共享的四项统计块。
    @ViewBuilder
    private var prototypeStatsPanel: some View {
        HStack(spacing: 0) {
            prototypeStatTile(
                symbol: "shippingbox.fill",
                value: user.publicRepos ?? 0,
                labelKey: "sharecard.stats.repos",
                iconColor: Color.fromHex6(0x2563EB)
            )
            prototypeStatDivider
            prototypeStatTile(
                symbol: "star.fill",
                value: starredCount,
                labelKey: "sharecard.stats.starred",
                iconColor: Color.fromHex6(0xF59E0B)
            )
            prototypeStatDivider
            prototypeStatTile(
                symbol: "person.2.fill",
                value: user.followers ?? 0,
                labelKey: "sharecard.stats.followers",
                iconColor: Color.fromHex6(0x06B6D4)
            )
            prototypeStatDivider
            prototypeStatTile(
                symbol: "person.fill",
                value: user.following ?? 0,
                labelKey: "sharecard.stats.following",
                iconColor: Color.fromHex6(0x22C55E)
            )
        }
        .padding(.horizontal, 8)
        .padding(.vertical, usesSocialColoredStats ? 12 : 10)
        .frame(height: usesSocialColoredStats ? 82 : 70)
        .background(prototypePanelBackground(cornerRadius: 16, opacity: style == .adventure ? 0.66 : 0.76))
    }

    @ViewBuilder
    private func prototypeStatTile(
        symbol: String,
        value: Int,
        labelKey: LocalizedStringKey,
        iconColor: Color
    ) -> some View {
        let renderedIconColor = usesSocialColoredStats ? iconColor : palette.accent

        VStack(spacing: usesSocialColoredStats ? 6 : 5) {
            Image(systemName: symbol)
                .font(.system(size: usesSocialColoredStats ? 12 : 13, weight: .bold))
                .foregroundStyle(renderedIconColor)
                .frame(width: usesSocialColoredStats ? 24 : 14, height: usesSocialColoredStats ? 24 : 14)
                .background {
                    if usesSocialColoredStats {
                        Circle()
                            .fill(renderedIconColor.opacity(0.13))
                    }
                }

            Text(formatCompact(value))
                .font(.system(size: usesSocialColoredStats ? 17 : 16, weight: .heavy, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .monospacedDigit()
                .lineLimit(1)
                .minimumScaleFactor(0.7)

            Text(labelKey)
                .font(.system(size: 8, weight: .semibold))
                .foregroundStyle(palette.secondaryText)
                .lineLimit(1)
                .minimumScaleFactor(0.55)
        }
        .frame(maxWidth: .infinity)
    }

    private var prototypeStatDivider: some View {
        Rectangle()
            .fill(palette.divider.opacity(usesSocialColoredStats ? 0.62 : (style == .adventure ? 0.55 : 0.85)))
            .frame(width: 0.7, height: usesSocialColoredStats ? 50 : 42)
    }

    /// 后四类共享的 Top Languages 块，数据来自用户自有公开仓库语言统计。
    @ViewBuilder
    private var prototypeLanguagePanel: some View {
        VStack(alignment: .leading, spacing: 8) {
            prototypeSectionHeader(titleKey: "sharecard.languages.title", symbol: "chevron.left.forwardslash.chevron.right")

            if languageSlices.isEmpty {
                languageEmptyState
                    .frame(maxWidth: .infinity, minHeight: 44, alignment: .leading)
            } else {
                languageStackedBar(width: 316, height: 10)
                languageLegendGrid
            }
        }
        .padding(12)
        .frame(height: 100)
        .background(prototypePanelBackground(cornerRadius: 16, opacity: style == .adventure ? 0.66 : 0.76))
    }

    /// 终端语言块用行式进度条，更贴近原型 3。
    @ViewBuilder
    private var terminalLanguagePanel: some View {
        VStack(alignment: .leading, spacing: 6) {
            Text(verbatim: "TOP LANGUAGES")
                .font(.system(size: 9, weight: .bold, design: .monospaced))
                .foregroundStyle(palette.accent)
                .tracking(1.0)

            if languageSlices.isEmpty {
                languageEmptyState
                    .frame(maxWidth: .infinity, minHeight: 54, alignment: .leading)
            } else {
                VStack(spacing: 4) {
                    ForEach(languageSlices.prefix(5)) { slice in
                        terminalLanguageRow(slice)
                    }
                }
            }
        }
        .padding(12)
        .frame(height: 112)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(prototypePanelBackground(cornerRadius: 8, opacity: 0.80))
    }

    /// 后四类共享的草坪块。
    @ViewBuilder
    private var prototypeContributionPanel: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 6) {
                Image(systemName: "square.grid.3x3.fill")
                    .font(.system(size: 10, weight: .bold))
                    .foregroundStyle(palette.accent)
                Text("sharecard.contribution.title")
                    .font(.system(size: 10, weight: .bold, design: .rounded))
                    .foregroundStyle(palette.primaryText)
                    .lineLimit(1)

                Spacer(minLength: 8)

                if let total = contribution?.totalContributions {
                    Text(String(format: String.l10n("sharecard.contribution.totalCount"), total))
                        .font(.system(size: 9, weight: .semibold, design: .monospaced))
                        .foregroundStyle(palette.secondaryText)
                        .lineLimit(1)
                        .minimumScaleFactor(0.72)
                }
            }

            ContributionStaticGrid(
                payload: contribution,
                palette: palette.contribution,
                pixelated: style == .terminal
            )
            .aspectRatio(style == .terminal ? 53.0 / 7.0 : 53.0 / 7.0 * (10.0 / 12.0), contentMode: .fit)

            contributionMonthAxis
        }
        .padding(12)
        .frame(height: 120)
        .background {
            if style == .adventure {
                adventureGlassPanelBackground
            } else {
                prototypePanelBackground(cornerRadius: style == .terminal ? 8 : 16, opacity: 0.76)
            }
        }
    }

    /// 冒险样式的暖色玻璃面板背景。
    ///
    /// Top Languages 与贡献草坪叠在同一张插画草地上，背景色必须一致，
    /// 否则底部会出现一暖一白两块卡片割裂。黑暗变体则切到深色面板，避免浅黄玻璃
    /// 在黑暗背景上突兀发灰。其它样式继续走共享 prototype 面板背景。
    @ViewBuilder
    private var adventureGlassPanelBackground: some View {
        if isDarkAdventureVariant {
            RoundedRectangle(cornerRadius: 16)
                .fill(palette.cardBackgroundSecondary.opacity(0.68))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .stroke(palette.accent.opacity(0.34), lineWidth: 0.8)
                )
                .shadow(color: Color.black.opacity(0.22), radius: 12, y: 6)
        } else {
            RoundedRectangle(cornerRadius: 16)
                .fill(Color.fromHex6(0xFFE8A6).opacity(0.42))
                .overlay(
                    RoundedRectangle(cornerRadius: 16)
                        .stroke(Color.white.opacity(0.52), lineWidth: 0.8)
                )
                .shadow(color: Color.fromHex6(0xB7791F).opacity(0.10), radius: 10, y: 5)
        }
    }

    @ViewBuilder
    private func prototypeSectionHeader(titleKey: LocalizedStringKey, symbol: String) -> some View {
        HStack(spacing: 6) {
            Image(systemName: symbol)
                .font(.system(size: 10, weight: .bold))
                .foregroundStyle(palette.accent)
            Text(titleKey)
                .font(.system(size: 10, weight: .bold, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .lineLimit(1)
            Spacer(minLength: 0)
        }
    }

    @ViewBuilder
    private func decoratedAvatar(size: CGFloat, borderWidth: CGFloat) -> some View {
        let usesGoldRing = isSocialLightCard || usesAdventureGoldAvatarRing
        let avatarAccent = usesGoldRing ? Color.fromHex6(0xF59E0B) : palette.accent
        let avatarRingColors = usesGoldRing
            ? [Color.fromHex6(0xFDE68A), Color.fromHex6(0xF59E0B), Color.fromHex6(0xD97706)]
            : [palette.accent, palette.primaryText.opacity(0.72)]

        ZStack(alignment: .bottomTrailing) {
            RemoteAvatar(urlString: user.avatarUrl, size: size, showBorder: false)
                .background(
                    Circle()
                        .fill(avatarAccent.opacity(style == .adventure ? 0.18 : 0.26))
                        .blur(radius: usesGoldRing ? 12 : 10)
                )
                .overlay(
                    Circle()
                        .stroke(
                            LinearGradient(
                                colors: avatarRingColors,
                                startPoint: .topLeading,
                                endPoint: .bottomTrailing
                            ),
                            lineWidth: borderWidth
                        )
                )
                .shadow(color: avatarAccent.opacity(style == .adventure ? 0.16 : 0.28), radius: 10, y: 4)

            if isProUser {
                shareCardProBadge
                    .offset(x: size * 0.08, y: size * 0.02)
            }
        }
    }

    @ViewBuilder
    private func prototypePanelBackground(cornerRadius: CGFloat, opacity: Double) -> some View {
        let fillOpacity = isSocialLightCard ? max(opacity, 0.96) : opacity
        let strokeOpacity = isSocialLightCard ? 0.95 : (style == .terminal ? 0.62 : (style == .adventure ? 0.52 : 0.78))
        let shadowOpacity = isSocialLightCard ? 0.08 : (style == .terminal ? 0.10 : (style == .adventure ? 0.08 : 0.18))

        if style == .terminal {
            Rectangle()
                .fill(prototypePanelFill.opacity(max(fillOpacity, 0.90)))
                .overlay {
                    terminalPanelTexture
                }
                .overlay(
                    Rectangle()
                        .stroke(palette.cardBorder.opacity(strokeOpacity), lineWidth: 1)
                )
                .overlay {
                    // 外层再压一圈像素风虚线，强调“屏幕面板”而不是普通卡片。
                    Rectangle()
                        .stroke(
                            palette.accent.opacity(0.28),
                            style: StrokeStyle(lineWidth: 1, dash: [3, 3])
                        )
                }
                .shadow(color: .black.opacity(shadowOpacity), radius: 4, y: 2)
        } else {
            RoundedRectangle(cornerRadius: cornerRadius)
                .fill(prototypePanelFill.opacity(fillOpacity))
                .overlay(
                    RoundedRectangle(cornerRadius: cornerRadius)
                        .stroke(palette.cardBorder.opacity(strokeOpacity), lineWidth: 0.7)
                )
                .shadow(color: .black.opacity(shadowOpacity), radius: 10, y: 4)
        }
    }

    private var prototypePanelFill: Color {
        switch style {
        case .adventure:
            return Color.white
        case .terminal:
            return palette.cardBackgroundSecondary
        case .social where colorSet == .lightCard:
            return Color.white
        default:
            return palette.cardBackgroundSecondary
        }
    }

    @ViewBuilder
    private var decorativeSpotlightOrnaments: some View {
        ZStack {
            Circle()
                .fill(palette.accent.opacity(0.18))
                .frame(width: 180, height: 180)
                .blur(radius: 28)
                .offset(x: 130, y: -170)
            Circle()
                .fill(palette.primaryText.opacity(0.10))
                .frame(width: 130, height: 130)
                .blur(radius: 22)
                .offset(x: -160, y: 170)
        }
        .allowsHitTesting(false)
    }

    /// 终端样式的轻量像素纹理。只叠在内容层，不参与命中测试，也不改变布局尺寸。
    @ViewBuilder
    private var terminalPixelOverlay: some View {
        Canvas { context, size in
            let step: CGFloat = 10
            let dotSize: CGFloat = 1.3
            let dotColor = palette.accent.opacity(0.14)
            let scanlineColor = palette.accent.opacity(0.045)

            var y: CGFloat = 0
            while y <= size.height {
                if Int(y / step).isMultiple(of: 2) {
                    context.fill(
                        Path(CGRect(x: 0, y: y, width: size.width, height: 1)),
                        with: .color(scanlineColor)
                    )
                }

                var x: CGFloat = 0
                while x <= size.width {
                    let rect = CGRect(x: x, y: y, width: dotSize, height: dotSize)
                    context.fill(Path(rect), with: .color(dotColor))
                    x += step
                }
                y += step
            }
        }
        .blendMode(.screen)
        .allowsHitTesting(false)
    }

    /// 终端面板内部的扫描线和网格。与 body 纹理分开，是为了让每张小卡片自己有像素屏边界。
    @ViewBuilder
    private var terminalPanelTexture: some View {
        Canvas { context, size in
            let lineColor = palette.accent.opacity(0.055)
            let verticalColor = palette.accent.opacity(0.035)
            var y: CGFloat = 4
            while y < size.height {
                context.fill(
                    Path(CGRect(x: 0, y: y, width: size.width, height: 1)),
                    with: .color(lineColor)
                )
                y += 8
            }

            var x: CGFloat = 6
            while x < size.width {
                context.fill(
                    Path(CGRect(x: x, y: 0, width: 1, height: size.height)),
                    with: .color(verticalColor)
                )
                x += 12
            }
        }
        .allowsHitTesting(false)
    }

    /// 终端版式的四项统计输出。
    @ViewBuilder
    private var terminalStatsBlock: some View {
        HStack(spacing: 0) {
            terminalMetric(symbol: "shippingbox.fill",
                           label: "REPOS",
                           value: user.publicRepos ?? 0,
                           iconColor: Color.fromHex6(0x60A5FA))
            terminalDivider
            terminalMetric(symbol: "star.fill",
                           label: "STARS",
                           value: starredCount,
                           iconColor: Color.fromHex6(0xFBBF24))
            terminalDivider
            terminalMetric(symbol: "person.2.fill",
                           label: "FOLLOWERS",
                           value: user.followers ?? 0,
                           iconColor: Color.fromHex6(0x22D3EE))
            terminalDivider
            terminalMetric(symbol: "person.fill",
                           label: "FOLLOWING",
                           value: user.following ?? 0,
                           iconColor: Color.fromHex6(0x4ADE80))
        }
        .padding(.horizontal, 8)
        .padding(.vertical, 8)
        .frame(height: 78)
        .background(prototypePanelBackground(cornerRadius: 8, opacity: 0.80))
    }

    @ViewBuilder
    private func terminalMetric(symbol: String, label: String, value: Int, iconColor: Color) -> some View {
        VStack(spacing: 4) {
            HStack(spacing: 4) {
                Image(systemName: symbol)
                    .font(.system(size: 9, weight: .bold))
                    .foregroundStyle(iconColor)
                    .frame(width: 16, height: 16)
                    .background(
                        Rectangle()
                            .fill(iconColor.opacity(0.14))
                            .overlay(
                                Rectangle()
                                    .stroke(iconColor.opacity(0.46), lineWidth: 1)
                            )
                    )
                Text(verbatim: label)
                    .font(.system(size: 7.2, weight: .bold, design: .monospaced))
                    .foregroundStyle(palette.accent.opacity(0.82))
                    .lineLimit(1)
                    .minimumScaleFactor(0.5)
            }

            Text(formatCompact(value))
                .font(.system(size: 17, weight: .bold, design: .monospaced))
                .foregroundStyle(palette.accent)
                .lineLimit(1)
                .minimumScaleFactor(0.68)
        }
        .frame(maxWidth: .infinity)
    }

    private var terminalDivider: some View {
        Rectangle()
            .fill(palette.accent.opacity(0.32))
            .frame(width: 0.7, height: 38)
    }

    /// ID 卡顶部头像区。
    /// 圆角矩形头像（不是圆形）+ 底部渐变虚化，模拟设计图里头像填充上半部分的视觉。
    @ViewBuilder
    private var idCardAvatar: some View {
        // 卡片宽 400 - 左右 padding 20 = 360pt 头像方块；高度按 0.78 比例避免太占垂直空间
        let avatarSide: CGFloat = Self.canvasWidth - 40
        let avatarHeight: CGFloat = avatarSide * 0.78
        ZStack(alignment: .bottom) {
            avatarFillView
                .frame(width: avatarSide, height: avatarHeight)
                .clipShape(RoundedRectangle(cornerRadius: 18))
                .overlay(
                    RoundedRectangle(cornerRadius: 18)
                        .stroke(palette.cardBorder, lineWidth: 0.5)
                )

            // 头像底部 → 卡片底色的淡入渐变带，让头像和下方文字区无硬边过渡
            LinearGradient(
                colors: [palette.cardBackground.opacity(0.0),
                         palette.cardBackground.opacity(0.55)],
                startPoint: .top, endPoint: .bottom
            )
            .frame(width: avatarSide, height: 60)
            .clipShape(
                UnevenRoundedRectangle(
                    bottomLeadingRadius: 18,
                    bottomTrailingRadius: 18
                )
            )
        }
        .frame(width: avatarSide, height: avatarHeight)
        .overlay(alignment: .topTrailing) {
            // ID 卡大圆角头像：Pro 徽章挂在右上角（杂志卡圆形头像在右下角）
            if isProUser {
                shareCardProBadge
                    .offset(x: -10, y: 10)
            }
        }
        .frame(maxWidth: .infinity)
    }

    /// 头像填充视图。设计图里头像几乎覆盖卡片上半部分，需要"方形填充"——
    /// 不能用 `RemoteAvatar`（强制 Circle clip 会丢四角），改直接用 KFImage scaledToFill。
    ///
    /// **2026-06-06 性能修复（dong4j 反馈 idCard 主题之间切换偶尔卡顿）**：
    /// idCard 布局这块头像是 360×280 的大图，原写法把 KFImage 直接放在 `avatarFillView`
    /// computed property 里——主题切换时 palette 中任意 Color 字段变化都让外层
    /// `ShareCardContent.body` 重算，KFImage 这棵子树会被重新构造（SwiftUI 视图
    /// 是值类型 struct，每次 body 都生成新实例）。Kingfisher 内存缓存命中所以
    /// 不会重新下载，但**重新走 resample 把 cache 里的源图缩到 360×280** 仍然
    /// 是同步主线程工作，叠加 0.18s 主题切换动画期间会让主线程卡顿。
    ///
    /// 修复：把 KFImage 那一支抽成 `Equatable` 子视图（仅按 url 判等，不比较
    /// palette 占位色）。SwiftUI diff 看到 url 没变就直接跳过重渲染，KFImage
    /// 内部 ImageBinder 状态保留，零 resample。占位渐变那一支保留原写法
    /// （只在 `user.avatarUrl == nil` 时走，几乎走不到）。
    @ViewBuilder
    private var avatarFillView: some View {
        if let urlString = user.avatarUrl,
           !urlString.isEmpty,
           let url = URL(string: urlString) {
            // 用 EquatableView wrapper：urlString 不变 → SwiftUI 跳过重渲染。
            CachedShareCardAvatar(
                url: url,
                placeholderBg: palette.cardBackgroundSecondary,
                placeholderFg: palette.tertiaryText
            )
            .equatable()
        } else {
            // 无 avatarUrl：渐变占位 + person 图标
            ZStack {
                LinearGradient(
                    colors: [palette.cardBackgroundSecondary, palette.cardBackground],
                    startPoint: .topLeading, endPoint: .bottomTrailing
                )
                Image(systemName: "person.fill")
                    .font(.system(size: 80, weight: .light))
                    .foregroundStyle(palette.tertiaryText)
            }
        }
    }

    /// ID 卡身份行：用户名 + verified 勾。
    @ViewBuilder
    private var idCardIdentity: some View {
        HStack(alignment: .center, spacing: 8) {
            Text(displayName)
                .font(.system(size: 26, weight: .bold, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .lineLimit(1)
                .minimumScaleFactor(0.6)

            // verified 勾——白卡用黑勾、黑卡用白勾，与设计图视觉等价
            Image(systemName: "checkmark.seal.fill")
                .font(.system(size: 18))
                .foregroundStyle(palette.accent)
        }
    }

    /// ID 卡 Bio 行。空 / nil 时不渲染。
    @ViewBuilder
    private var idCardBio: some View {
        if let bio = user.bio, !bio.isEmpty {
            Text(bio)
                .font(.system(size: 13, weight: .regular))
                .foregroundStyle(palette.secondaryText)
                .lineLimit(2)
                .multilineTextAlignment(.leading)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    /// ID 卡底部行：左侧 3 个 pill stats，右侧 QR 码。
    ///
    /// HOM-174 follow-up：改为 3 个 stat（Starred + Followers + Following），
    /// 与 magazine 布局的前 3 个主题保持一致。
    @ViewBuilder
    private var idCardBottomRow: some View {
        HStack(alignment: .center) {
            VStack(alignment: .leading, spacing: 8) {
                idCardStatPill(symbol: "star.fill",
                               value: starredCount,
                               labelKey: "sharecard.stats.starred")
                idCardStatPill(symbol: "person.2.fill",
                               value: user.followers ?? 0,
                               labelKey: "sharecard.stats.followers")
                idCardStatPill(symbol: "person.fill",
                               value: user.following ?? 0,
                               labelKey: "sharecard.stats.following")
            }

            Spacer()

            qrCodeView
        }
    }

    /// 单个 stat pill：圆形 accent 底图标 + 数字 + 小标签。
    @ViewBuilder
    private func idCardStatPill(symbol: String, value: Int, labelKey: LocalizedStringKey) -> some View {
        HStack(spacing: 8) {
            ZStack {
                Circle()
                    .fill(palette.accent)
                    .frame(width: 22, height: 22)
                Image(systemName: symbol)
                    .font(.system(size: 11, weight: .bold))
                    .foregroundStyle(palette.onAccent)
            }
            Text(formatCompact(value))
                .font(.system(size: 14, weight: .semibold, design: .rounded))
                .foregroundStyle(palette.primaryText)
                .monospacedDigit()
            Text(labelKey)
                .font(.system(size: 10, weight: .medium))
                .foregroundStyle(palette.tertiaryText)
                .textCase(.uppercase)
                .tracking(0.5)
        }
    }

    /// QR 码视图。内容：用户 GitHub 主页 URL（`https://github.com/{login}`）。
    ///
    /// 视觉：64pt QR + 6pt 容器内边距 = 76pt 容器；容器底色 = onAccent（与 stats pill 反色一致）。
    /// 白卡：黑容器 + 白 QR；黑卡：白容器 + 黑 QR——两种模式都保证扫码对比度。
    ///
    /// HOM-174 follow-up：QR 码不使用 template rendering，直接显示原生黑白图像
    /// （QR 需要高对比度，template tinting 会导致扫码失败）。
    @ViewBuilder
    private var qrCodeView: some View {
        let url = profileURLString
        let qrImage = QRCodeGenerator.generate(text: url, sizePoints: 64)

        ZStack {
            RoundedRectangle(cornerRadius: 14)
                .fill(palette.onAccent)
                .frame(width: 76, height: 76)

            if let qrImage {
                // QR码直接显示，不使用template模式以保持高对比度
                Image(nsImage: qrImage)
                    .interpolation(.none)
                    .resizable()
                    .frame(width: 64, height: 64)
            } else {
                // 极端兜底：QR 生成失败时显示 SF Symbol qrcode 图标
                Image(systemName: "qrcode")
                    .font(.system(size: 36, weight: .regular))
                    .foregroundStyle(palette.accent)
            }
        }
            .accessibilityLabel(Text(verbatim: url))
    }

    /// 新版原型卡右侧使用的小二维码，避免 76pt QR 把第一块信息挤窄。
    @ViewBuilder
    private var compactQRCodeView: some View {
        let url = profileURLString
        let qrImage = QRCodeGenerator.generate(text: url, sizePoints: 48)

        ZStack {
            RoundedRectangle(cornerRadius: 12)
                .fill(palette.onAccent)
                .frame(width: 58, height: 58)

            if let qrImage {
                Image(nsImage: qrImage)
                    .interpolation(.none)
                    .resizable()
                    .frame(width: 48, height: 48)
            } else {
                Image(systemName: "qrcode")
                    .font(.system(size: 28, weight: .regular))
                    .foregroundStyle(palette.accent)
            }
        }
        .accessibilityLabel(Text(verbatim: url))
    }

    /// ID 卡底部注脚：Generated by Starcat · starcat.ink
    @ViewBuilder
    private var idCardFooter: some View {
        HStack {
            Text("sharecard.card.generatedBy")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(palette.tertiaryText)
                .tracking(0.5)
            Spacer()
            Text("starcat.ink")
                .font(.system(size: 9, weight: .medium, design: .monospaced))
                .foregroundStyle(.green)
        }
    }
}

// MARK: - 链接数据模型

/// 分享卡链接项（用于导出图片的静态展示）。
private struct ShareCardLinkItem: Identifiable {
    let symbolName: String
    let displayText: String

    var id: String { displayText }
}

/// 分享卡语言条的展示切片。
private struct ShareCardLanguageSlice: Identifiable {
    let name: String
    let ratio: Double
    let color: Color

    var id: String { name }
}

/// Magazine 草坪月份刻度。
private struct ContributionMonthTick: Identifiable {
    let id: Int
    let label: String
}

/// 数据看板 facts 区的一行静态数据。
private struct DashboardFact: Identifiable {
    let symbol: String
    let labelKey: LocalizedStringKey
    let value: String

    var id: String { "\(symbol)-\(value)" }
}

// MARK: - ID 卡大头像（Equatable 缓存）

/// idCard 布局的 360×280 大头像 KFImage 容器，**仅按 URL 判等**。
///
/// 为什么需要单独包一层：
/// - 主题切换时 palette 中所有 Color 字段会变（cardBackgroundSecondary、
///   tertiaryText 等），外层 `ShareCardContent.body` 整棵 view tree 重新构造。
/// - SwiftUI struct 视图本身重建是廉价的，但 KFImage 在 body 重算时会让内部
///   `ImageBinder` 重新对 cache 命中的源图做 resample 缩到 360×280——这是
///   主线程同步工作，叠加主题切换动画时帧抖动明显。
/// - 用 `Equatable` + `.equatable()` 让 SwiftUI 在 url 没变时跳过整棵子树
///   diff，KFImage 状态保留 → 零 resample。
///
/// 占位色（`placeholderBg` / `placeholderFg`）虽然存了但**不参与 ==**：
/// - 只在 Kingfisher cache miss + 首次解码期间出现一瞬间
/// - 之后画面就是已解码的头像图，占位色与否用户看不到
/// - 用户切主题想"改色"→ 等图加载好之后切是预期路径；首次切（cache 还没好）
///   即使占位不变也只闪一帧，体感无感
private struct CachedShareCardAvatar: View, Equatable {
    let url: URL
    let placeholderBg: Color
    let placeholderFg: Color

    /// 仅比较 URL：palette 颜色变化不触发重渲染（占位色滞后是可接受代价）。
    static func == (lhs: CachedShareCardAvatar, rhs: CachedShareCardAvatar) -> Bool {
        lhs.url == rhs.url
    }

    var body: some View {
        KFImage(url)
            .resizable()
            .placeholder {
                Rectangle()
                    .fill(placeholderBg)
                    .overlay(
                        Image(systemName: "person.fill")
                            .font(.system(size: 60))
                            .foregroundStyle(placeholderFg)
                    )
            }
            .fade(duration: 0.15)
            .scaledToFill()
    }
}

// MARK: - 静态草坪绘制（Canvas）

/// 纯静态贡献草坪。
///
/// 与 `ContributionGraphView` 的差异：
/// - 不依赖系统 colorScheme，调色板由调用方传入（保证导出图主题一致）。
/// - 不渲染贪吃蛇动画，纯静态网格。
/// - 不渲染顶部"贡献总数 + 更新于…"行（外层 `contributionSection` 已渲染）。
///
/// 默认单元格保持横向略扁的分享卡草坪；第 4 套终端卡使用正方形无圆角像素块。
/// 这两个模式共用数据和调色板，只分离绘制几何，避免后续修贡献数据时改漏某个样式。
private struct ContributionStaticGrid: View {

    let payload: ContributionCalendarPayload?
    let palette: ContributionPalette
    let pixelated: Bool

    /// 53 列 × 7 行的固有尺寸（基础值，外层 aspectRatio 缩放）。
    /// 第 4 套终端卡要像素块观感：方形、无圆角、间距略大；其它卡片沿用长圆角草坪。
    private var cellWidth: CGFloat { 10 }
    private var cellHeight: CGFloat { pixelated ? 10 : 12 }
    private var cellSpacing: CGFloat { pixelated ? 2 : 1.5 }
    private var cellCornerRadius: CGFloat { pixelated ? 0 : 1.5 }

    /// 整图固有尺寸——外层 aspectRatio 取这个比例。
    private var intrinsicWidth: CGFloat {
        53 * cellWidth + 52 * cellSpacing
    }
    private var intrinsicHeight: CGFloat {
        7 * cellHeight + 6 * cellSpacing
    }

    var body: some View {
        Canvas { ctx, size in
            let scale = size.width / intrinsicWidth
            drawGrid(ctx: ctx, scale: scale)
        }
    }

    /// 单遍绘制 53×7=371 格圆角矩形。
    /// 没数据时整片用 NONE 色填充作为骨架；有数据时按 weeks 数组从右对齐绘制。
    private func drawGrid(ctx: GraphicsContext, scale: CGFloat) {
        let cellW = cellWidth * scale
        let cellH = cellHeight * scale
        let spacing = cellSpacing * scale
        let corner = cellCornerRadius * scale

        guard let weeks = payload?.weeks else {
            // 占位：整面 none 色，让分享图在没拿到数据时也不空白
            for col in 0..<53 {
                for row in 0..<7 {
                    let x = CGFloat(col) * (cellW + spacing)
                    let y = CGFloat(row) * (cellH + spacing)
                    let rect = CGRect(x: x, y: y, width: cellW, height: cellH)
                    ctx.fill(Path(roundedRect: rect, cornerRadius: corner),
                             with: .color(palette.color(for: .none)))
                }
            }
            return
        }

        // 账号较新时 weeks 可能不足 53 周，与 ContributionGraphView 同款"右对齐"策略
        let startColumn = max(0, 53 - weeks.count)

        for (weekIdx, week) in weeks.enumerated() {
            let col = startColumn + weekIdx
            let x = CGFloat(col) * (cellW + spacing)
            for day in week.contributionDays {
                let y = CGFloat(day.weekday) * (cellH + spacing)
                let rect = CGRect(x: x, y: y, width: cellW, height: cellH)
                ctx.fill(
                    Path(roundedRect: rect, cornerRadius: corner),
                    with: .color(palette.color(for: day.contributionLevel))
                )
            }
        }
    }
}

// MARK: - Preview

private func makeMockDeveloperLanguages() -> DeveloperLanguageSnapshot {
    DeveloperLanguageSnapshot(
        login: "dong4j",
        fetchedAt: Date(),
        repositoryCount: 48,
        totalBytes: 100_000,
        languages: [
            DeveloperLanguageEntry(name: "Swift", bytes: 42_300, ratio: 0.423),
            DeveloperLanguageEntry(name: "TypeScript", bytes: 28_700, ratio: 0.287),
            DeveloperLanguageEntry(name: "Python", bytes: 16_400, ratio: 0.164),
            DeveloperLanguageEntry(name: "Go", bytes: 7_600, ratio: 0.076),
            DeveloperLanguageEntry(name: "HTML", bytes: 5_000, ratio: 0.050)
        ]
    )
}

#Preview("ShareCard - GitHub Green") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: "DONG Jianjun",
        avatarUrl: "https://avatars.githubusercontent.com/u/3380083?v=4",
        publicRepos: 48, followers: 236, following: 100,
        bio: "用代码解决真正的问题。", company: nil,
        location: "Shanghai", email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: "https://github.com/dong4j"
    )
    return ShareCardContent(
        user: mockUser, starredCount: 4823,
        contribution: nil, developerLanguages: makeMockDeveloperLanguages(),
        style: .magazine, colorSet: .githubGreen
    )
    .padding()
    .background(Color.gray.opacity(0.2))
}

#Preview("ShareCard - Heat Orange") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: "DONG Jianjun",
        avatarUrl: nil,
        publicRepos: 48, followers: 236, following: 100,
        bio: "用代码解决真正的问题。", company: nil,
        location: "Shanghai", email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: nil
    )
    return ShareCardContent(
        user: mockUser, starredCount: 1284,
        contribution: nil, developerLanguages: makeMockDeveloperLanguages(),
        style: .spotlight, colorSet: .berryPurple
    )
    .padding()
    .background(Color.gray.opacity(0.2))
}

#Preview("ShareCard - Minimal") {
    let mockUser = GitHubUserDTO(
        id: 1, login: "dong4j", name: nil,
        avatarUrl: nil,
        publicRepos: 48, followers: 236, following: 100,
        bio: nil, company: nil, location: nil, email: nil, blog: nil,
        twitterUsername: nil, htmlUrl: nil
    )
    return ShareCardContent(
        user: mockUser, starredCount: 999,
        contribution: nil, developerLanguages: makeMockDeveloperLanguages(),
        style: .terminal, colorSet: .githubGreen
    )
    .padding()
    .background(Color.white)
}
