import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/base.css";
// 主题 token 必须在 base.css 之后导入：同特异性下后者胜，
// 这样主题的 --stage-pad-* / --r-card / --dur-* 才不会被 base 默认值覆盖。
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/animations.css";

import { useCallback, useState } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAudioPreload, cachedAudioSrc } from "./hooks/useAudioPreload";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

/**
 * Estimate spoken duration of a Chinese narration string. Native pace
 * ≈ 4 char/s → 250ms per char. Used as Auto-mode fallback ONLY when the
 * audio file is missing / fails / the narration is empty. When audio plays
 * normally, this value is unused — auto-advance fires on `audio.ended`.
 */
function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";
  const stepKey = `${ch.id}:${stepper.cursor.step}`;

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();

  // Warm every mp3 into blob URLs on mount → per-step play() is instant.
  useAudioPreload(CHAPTERS);

  // Audio path follows the convention: /audio/<chapter-id>/<step+1>.mp3
  // (1-indexed file names match what `extract-narrations.ts` outputs.)
  // Empty narration → no audio src, Auto mode falls back to estimate.
  const rawSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;
  const audioSrc = rawSrc ? cachedAudioSrc(rawSrc) : null;

  // ── 声画帧级锁 ──
  // A step whose narration has audio mounts FROZEN (`.is-hold` pauses all
  // CSS keyframe animations) and only unfreezes when useAudioPlayer reports
  // the voice actually playing. This makes animation t=0 coincide with the
  // first audible sample instead of with React's commit.
  // Computed synchronously from cursor — no effect flicker between renders.
  const [releasedKey, setReleasedKey] = useState<string | null>(null);
  const waitingForAudio =
    audioSrc !== null && !(mode === "auto" && !autoStarted);
  const hold = waitingForAudio && releasedKey !== stepKey;

  const onAudioStart = useCallback(() => setReleasedKey(stepKey), [stepKey]);
  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 100,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
    onStart: onAudioStart,
  });

  return (
    <>
      <Stage onAdvance={stepper.next}>
        <div key={ch.id} className={`scene${hold ? " is-hold" : ""}`}>
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
