#!/usr/bin/env bash
# =============================================================================
# sync-production-api-keys-from-env.sh
# =============================================================================
#
# 从 supports/starcat-*-api/.env 的 API_KEYS 读取各服务 production key（取逗号分隔
# 的第一个），写入 Configs/Secrets.xcconfig，供 Xcode 编译期注入 Info.plist。
#
# 与 fly-secrets-sync.sh 对称：后者推 Fly secrets，本脚本配 Starcat 客户端 baked-in。
# 各服务允许使用不同的 sk-starcat-... key。
#
# 用法（Starcat 主仓库根目录）：
#   bash scripts/sync-production-api-keys-from-env.sh
#   make setup-production-api-keys
# =============================================================================

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SUPPORTS_DIR="${ROOT_DIR}/supports"
CONFIG="${ROOT_DIR}/Configs/Secrets.xcconfig"

KEY_RE='^sk-starcat-[A-Z2-7]{32}$'

read_first_api_key() {
  local env_file="$1"
  local line val first
  if [[ ! -f "${env_file}" ]]; then
    echo "Error: missing ${env_file}" >&2
    return 1
  fi
  line="$(grep -E '^API_KEYS=' "${env_file}" | head -1 || true)"
  if [[ -z "${line}" ]]; then
    echo "Error: ${env_file} has no API_KEYS=" >&2
    return 1
  fi
  val="${line#API_KEYS=}"
  val="$(printf '%s' "${val}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  first="${val%%,*}"
  first="$(printf '%s' "${first}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
  if [[ -z "${first}" ]]; then
    echo "Error: ${env_file} API_KEYS is empty" >&2
    return 1
  fi
  if ! printf '%s' "${first}" | grep -qE "${KEY_RE}"; then
    echo "Error: invalid API_KEYS in ${env_file} (want sk-starcat- + 32 base32 chars)" >&2
    return 1
  fi
  printf '%s' "${first}"
}

echo ">>> 从 supports/*/.env 同步 production API keys -> Configs/Secrets.xcconfig"

KEY_TRENDING="$(read_first_api_key "${SUPPORTS_DIR}/starcat-trending-api/.env")"
KEY_WEEKLY="$(read_first_api_key "${SUPPORTS_DIR}/starcat-weekly-api/.env")"
KEY_SHARING="$(read_first_api_key "${SUPPORTS_DIR}/starcat-sharing-api/.env")"
KEY_WIKI="$(read_first_api_key "${SUPPORTS_DIR}/starcat-wiki-api/.env")"
KEY_RECOMMEND="$(read_first_api_key "${SUPPORTS_DIR}/starcat-recommend-api/.env")"

# 整文件重写，避免 sed 匹配 template 空行失败；注释行仅供人读，不参与编译逻辑。
cat > "${CONFIG}" <<EOF
// Generated by scripts/sync-production-api-keys-from-env.sh — do not commit.
// Re-run: make setup-production-api-keys

STARCAT_PRODUCTION_API_KEY_TRENDING = ${KEY_TRENDING}
STARCAT_PRODUCTION_API_KEY_WEEKLY = ${KEY_WEEKLY}
STARCAT_PRODUCTION_API_KEY_SHARING = ${KEY_SHARING}
STARCAT_PRODUCTION_API_KEY_WIKI = ${KEY_WIKI}
STARCAT_PRODUCTION_API_KEY_RECOMMEND = ${KEY_RECOMMEND}
EOF

echo "  ok STARCAT_PRODUCTION_API_KEY_TRENDING <- starcat-trending-api/.env"
echo "  ok STARCAT_PRODUCTION_API_KEY_WEEKLY <- starcat-weekly-api/.env"
echo "  ok STARCAT_PRODUCTION_API_KEY_SHARING <- starcat-sharing-api/.env"
echo "  ok STARCAT_PRODUCTION_API_KEY_WIKI <- starcat-wiki-api/.env"
echo "  ok STARCAT_PRODUCTION_API_KEY_RECOMMEND <- starcat-recommend-api/.env"
echo "ok 五个服务的 production API key 已写入 Configs/Secrets.xcconfig"
echo "  下一步: xcodegen generate && 重新 build App（make run / make build-dmg）"
