//
//  LanguageIcon.swift
//  Starcat
//
//  编程语言图标解析器。
//
//  设计约束：
//  - 图标来源：Devicon (MIT) - 本地存储在 Assets.xcassets/Devicons
//  - 语言元数据：GitHub Linguist (MIT) - 用于颜色和别名
//  - Fallback：使用 Linguist color + 首字母渲染彩色圆形
//
//  优先级：
//  1. 本地 Devicon SVG 资源 → 2. ColorBadge fallback (Linguist color + 首字母)
//
//  Devicon 许可证：MIT - https://github.com/devicons/devicon
//

import SwiftUI

// MARK: - 数据模型

/// 语言元数据，来源：GitHub Linguist languages.yml
struct LanguageMeta: Codable, Equatable {
    let type: String           // "programming" | "markup" | "data" | "prose"
    let color: String?        // Hex color, e.g. "#f1e05a"
    let aliases: [String]

    init(type: String, color: String?, aliases: [String] = []) {
        self.type = type
        self.color = color
        self.aliases = aliases
    }
}

/// 语言图标解析结果
struct LanguageIconResult {
    enum IconType {
        case localSVG(assetName: String)  // 本地 asset catalog 中的 SVG 资源名
        case badge(colorHex: String, label: String)  // 彩色圆形 + 首字母
    }

    let type: IconType
    let languageName: String

    /// 获取本地资源名（如果是本地 SVG 的话）
    var localAssetName: String? {
        if case .localSVG(let name) = type {
            return name
        }
        return nil
    }

    /// 是否使用 badge
    var isBadge: Bool {
        if case .badge = type { return true }
        return false
    }

    /// Badge 背景色 hex
    var badgeColorHex: String? {
        if case .badge(let colorHex, _) = type {
            return colorHex
        }
        return nil
    }

    /// Badge 标签（首字母）
    var badgeLabel: String? {
        if case .badge(_, let label) = type {
            return label
        }
        return nil
    }
}

// MARK: - Devicon 图标名称解析

/// Devicon 特殊映射表（Linguist 语言名 → Devicon 资源名）
/// 仅包含名称不直接匹配的特殊情况
private let deviconSpecialMap: [String: String] = [
    "Shell": "bash",
    "C++": "cplusplus",
    "C#": "csharp",
    "HTML": "html5",
    "CSS": "css3",
    "Vue": "vuejs",
    "F#": "fsharp",
    "TeX": "latex",
    "Assembly": "nasm",
]

/// Devicon asset catalog 中所有有效的资源名集合
/// 由 scripts/generate_devicons_set.py 自动生成
private let validDeviconAssets: Set<String> = [
    "aarch64", "adonisjs", "aerospike", "aframe", "aftereffects", "akka", "algolia", "almalinux",
    "alpinejs", "anaconda", "android", "androidstudio", "angular", "angularjs", "angular_material",
    "ansible", "ansys", "antdesign", "apache", "apacheairflow", "apachekafka", "apachespark",
    "apex", "apl", "apollographql", "appcelerator", "apple", "appwrite", "archlinux", "arduino",
    "argocd", "artixlinux", "astro", "atom", "awk", "azure", "azuredevops", "azuresqldatabase",
    "babel", "babylonjs", "backbonejs", "ballerina", "bamboo", "bash", "bazel", "beats", "behance",
    "bevyengine", "biome", "bitbucket", "blazor", "blender", "bootstrap", "bower", "browserstack",
    "bun", "c", "cairo", "cakephp", "canva", "capacitor", "carbon", "cassandra", "centos", "ceylon",
    "chakraui", "chartjs", "chrome", "clarity", "clickhouse", "clion", "clojure", "clojurescript",
    "cloudflare", "cloudflareworkers", "cloudrun", "cmake", "cobol", "codeac", "codepen",
    "coffeescript", "composer", "confluence", "consul", "contao", "corejs", "cosmosdb",
    "couchbase", "couchdb", "cpanel", "cplusplus", "crystal", "csharp", "css3", "cypressio",
    "d3js", "dart", "datadog", "datagrip", "dataspell", "datatables", "dbeaver", "debian",
    "delphi", "denojs", "devicon", "digitalocean", "discloud", "discordjs", "djangorest", "docker",
    "doctrine", "dot-net", "dotnetcore", "dovecot", "dreamweaver", "dropwizard", "drupal",
    "duckdb", "dyalog", "dynamodb", "dynatrace", "eclipse", "ecto", "elasticsearch", "electron",
    "eleventy", "elixir", "elm", "emacs", "embeddedc", "ember", "entityframeworkcore", "envoy",
    "erlang", "eslint", "expo", "express", "facebook", "fastapi", "fastify", "faunadb", "feathersjs",
    "fedora", "fiber", "figma", "filamentphp", "filezilla", "firebase", "firebird", "firefox", "flask",
    "flutter", "forgejo", "fortran", "foundation", "framermotion", "framework7", "fsharp", "fusion",
    "gardener", "gatling", "gatsby", "gazebo", "gcc", "gentoo", "ghost", "gimp", "git", "gitbook",
    "github", "githubactions", "githubcodespaces", "gitkraken", "gitlab", "gitpod", "gleam", "glitch",
    "go", "godot", "goland", "google", "googlecloud", "googlecolab", "gradle", "grafana", "grails",
    "groovy", "grpc", "grunt", "hadoop", "handlebars", "harbor", "hardhat", "harvester", "haskell",
    "haxe", "helm", "heroku", "hibernate", "homebrew", "hoppscotch", "html5", "htmx", "hugo",
    "hyperv", "ie10", "ifttt", "illustrator", "inertiajs", "influxdb", "inkscape", "insomnia",
    "intellij", "ionic", "jaegertracing", "jamstack", "jasmine", "java", "javascript", "jeet",
    "jekyll", "jenkins", "jetbrains", "jetpackcompose", "jhipster", "jira", "jiraalign",
    "jquery", "json", "jule", "julia", "junit", "jupyter", "k3os", "k3s", "k6", "kaggle",
    "kaldi", "kalilinux", "karatelabs", "karma", "kdeneon", "keras", "kibana", "knexjs", "kotlin",
    "krakenjs", "ktor", "kubeflow", "kubernetes", "labview", "laminas", "laravel", "laraveljetstream",
    "latex", "leetcode", "libgdx", "linkedin", "linux", "linuxmint", "liquibase", "livewire",
    "llvm", "lodash", "logstash", "love2d", "lua", "lumen", "magento", "mapbox", "mariadb",
    "markdown", "materializecss", "materialui", "matlab", "matplotlib", "mattermost", "maven",
    "maya", "memcached", "mercurial", "meteor", "microsoftsqlserver", "mithril", "mobx", "mocha",
    "modx", "moleculer", "mongodb", "mongoose", "monogame", "moodle", "msdos", "mysql", "nano",
    "nats", "neo4j", "neovim", "nestjs", "netbeans", "netbox", "netlify", "networkx", "newrelic",
    "nextjs", "nginx", "ngrok", "ngrx", "nhibernate", "nim", "nimble", "nixos", "nodejs", "nodemon",
    "nodered", "nodewebkit", "nomad", "norg", "notion", "npm", "npss", "nuget", "numpy", "nuxt",
    "nuxtjs", "oauth", "ocaml", "ohmyzsh", "okta", "openal", "openapi", "opencl", "opencv",
    "opengl", "openstack", "opensuse", "opentelemetry", "opera", "oracle", "ory", "p5js", "packer",
    "pandas", "passport", "perl", "pfsense", "phalcon", "phoenix", "photonengine", "photoshop",
    "php", "phpstorm", "pixijs", "playwright", "plotly", "pm2", "pnpm", "podman", "poetry",
    "polygon", "portainer", "postcss", "postgresql", "postman", "powershell", "premierepro", "primeng",
    "prisma", "processing", "processwire", "prolog", "prometheus", "protractor", "proxmox", "pug",
    "pulsar", "pulumi", "puppeteer", "purescript", "putty", "pycharm", "pypi", "pytest", "python",
    "pytorch", "qodana", "qt", "qtest", "quarkus", "quasar", "qwik", "r", "rabbitmq", "racket",
    "radstudio", "railway", "rancher", "raspberrypi", "reach", "react", "reactbootstrap", "reactnative",
    "reactnavigation", "reactrouter", "readthedocs", "realm", "rect", "redhat", "redis", "redux",
    "reflex", "remix", "renpy", "replit", "rexx", "rider", "rocksdb", "rockylinux", "rollup",
    "ros", "rspec", "rstudio", "ruby", "rubymine", "rust", "rxjs", "safari", "salesforce",
    "sanity", "sass", "scala", "scalingo", "scikitlearn", "sdl", "selenium", "sema", "sentry",
    "sequelize", "shopware", "shotgrid", "sketch", "slack", "socketio", "solidity", "solidjs",
    "sonarqube", "sourceengine", "sourcetree", "spack", "spicedb", "spring", "spss", "spyder",
    "sqlalchemy", "sqldeveloper", "sqlite", "ssh", "stackblitz", "stackoverflow", "stenciljs",
    "storybook", "streamlit", "styledcomponents", "stylus", "subversion", "sulu", "supabase",
    "surrealdb", "svelte", "svgo", "swagger", "swift", "swiper", "symfony", "tailwindcss",
    "talos", "tauri", "teleport", "tensorflow", "terraform", "terramate", "tex", "thealgorithms",
    "threedsmax", "threejs", "thymeleaf", "titaniumsdk", "tmux", "tomcat", "tortoisegit", "towergit",
    "traefikmesh", "traefikproxy", "travis", "trello", "trpc", "turbo", "twilio", "twitter",
    "typescript", "typo3", "ubuntu", "unifiedmodelinglanguage", "unity", "unix", "unrealengine",
    "uwsgi", "v8", "vaadin", "vagrant", "vala", "vault", "veevalidate", "vercel", "vertx",
    "vim", "visualbasic", "visualstudio", "vite", "vitejs", "vitess", "vitest", "vscode",
    "vscodium", "vsphere", "vuejs", "vuestorefront", "vuetify", "vulkan", "vyper", "waku",
    "wasm", "web3js", "webflow", "webgpu", "weblate", "webpack", "webstorm", "windows11",
    "windows8", "wolfram", "woocommerce", "wordpress", "xamarin", "xcode", "xd", "xml",
    "yaml", "yarn", "yii", "yugabytedb", "yunohost", "zend", "zig", "zsh", "zustand"
]

/// 根据语言名解析 Devicon 资源名（仅当 asset 实际存在时返回）
/// 优先顺序：1. 特殊映射 2. 大小写不敏感直接匹配（去空格后 lowercase）
private func deviconAssetName(for language: String) -> String? {
    // 1. 特殊映射
    if let special = deviconSpecialMap[language], validDeviconAssets.contains(special) {
        return special
    }

    // 2. 大小写不敏感直接匹配（去空格后 lowercase）
    let normalized = language.lowercased().replacingOccurrences(of: " ", with: "")
    if validDeviconAssets.contains(normalized) {
        return normalized
    }

    return nil
}

// Generated from https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml
// Run: python3 scripts/generate_linguist_metadata.py to regenerate
private let linguistLanguages: [String: LanguageMeta] = [
    "1C Enterprise": LanguageMeta(type: "programming", color: "#814CCC", aliases: []),
    "2-Dimensional Array": LanguageMeta(type: "data", color: "#38761D", aliases: []),
    "4D": LanguageMeta(type: "programming", color: "#004289", aliases: []),
    "ABAP": LanguageMeta(type: "programming", color: "#E8274B", aliases: []),
    "ABAP CDS": LanguageMeta(type: "programming", color: "#555e25", aliases: []),
    "ABNF": LanguageMeta(type: "data", color: nil, aliases: []),
    "AGS Script": LanguageMeta(type: "programming", color: "#B9D9FF", aliases: ["ags"]),
    "AIDL": LanguageMeta(type: "programming", color: "#34EB6B", aliases: []),
    "AL": LanguageMeta(type: "programming", color: "#3AA2B5", aliases: []),
    "ALGOL": LanguageMeta(type: "programming", color: "#D1E0DB", aliases: []),
    "AMPL": LanguageMeta(type: "programming", color: "#E6EFBB", aliases: []),
    "ANTLR": LanguageMeta(type: "programming", color: "#9DC3FF", aliases: []),
    "API Blueprint": LanguageMeta(type: "markup", color: "#2ACCA8", aliases: []),
    "APL": LanguageMeta(type: "programming", color: "#5A8164", aliases: []),
    "ASL": LanguageMeta(type: "programming", color: nil, aliases: []),
    "ASN.1": LanguageMeta(type: "data", color: nil, aliases: []),
    "ASP.NET": LanguageMeta(type: "programming", color: "#9400ff", aliases: ["aspx", "aspx-vb"]),
    "ATS": LanguageMeta(type: "programming", color: "#1ac620", aliases: ["ats2"]),
    "ActionScript": LanguageMeta(type: "programming", color: "#882B0F", aliases: ["actionscript 3", "actionscript3", "as3"]),
    "Ada": LanguageMeta(type: "programming", color: "#02f88c", aliases: ["ada95", "ada2005"]),
    "Adblock Filter List": LanguageMeta(type: "data", color: "#800000", aliases: ["ad block filters", "ad block", "adb", "adblock"]),
    "Adobe Font Metrics": LanguageMeta(type: "data", color: "#fa0f00", aliases: ["acfm", "adobe composite font metrics", "adobe multiple font metrics", "amfm"]),
    "Agda": LanguageMeta(type: "programming", color: "#315665", aliases: []),
    "Aiken": LanguageMeta(type: "programming", color: "#640ff8", aliases: []),
    "Alloy": LanguageMeta(type: "programming", color: "#64C800", aliases: []),
    "Alpine Abuild": LanguageMeta(type: "programming", color: "#0D597F", aliases: ["abuild", "apkbuild"]),
    "Altium Designer": LanguageMeta(type: "data", color: "#A89663", aliases: ["altium"]),
    "AngelScript": LanguageMeta(type: "programming", color: "#C7D7DC", aliases: []),
    "Answer Set Programming": LanguageMeta(type: "programming", color: "#A9CC29", aliases: []),
    "Ant Build System": LanguageMeta(type: "data", color: "#A9157E", aliases: []),
    "Antlers": LanguageMeta(type: "markup", color: "#ff269e", aliases: []),
    "ApacheConf": LanguageMeta(type: "data", color: "#d12127", aliases: ["aconf", "apache"]),
    "Apex": LanguageMeta(type: "programming", color: "#1797c0", aliases: []),
    "Apollo Guidance Computer": LanguageMeta(type: "programming", color: "#0B3D91", aliases: []),
    "AppleScript": LanguageMeta(type: "programming", color: "#101F1F", aliases: ["apples", "osascript"]),
    "Arc": LanguageMeta(type: "programming", color: "#aa2afe", aliases: []),
    "AsciiDoc": LanguageMeta(type: "prose", color: "#73a0c5", aliases: []),
    "AspectJ": LanguageMeta(type: "programming", color: "#a957b0", aliases: []),
    "Assembly": LanguageMeta(type: "programming", color: "#6E4C13", aliases: ["asm", "nasm"]),
    "Astro": LanguageMeta(type: "markup", color: "#ff5a03", aliases: []),
    "Asymptote": LanguageMeta(type: "programming", color: "#ff0000", aliases: []),
    "Augeas": LanguageMeta(type: "programming", color: "#9CC134", aliases: []),
    "AutoHotkey": LanguageMeta(type: "programming", color: "#6594b9", aliases: ["ahk"]),
    "AutoIt": LanguageMeta(type: "programming", color: "#1C3552", aliases: ["au3", "AutoIt3", "AutoItScript"]),
    "Awk": LanguageMeta(type: "programming", color: "#c30e9b", aliases: []),
    "B (Formal Method)": LanguageMeta(type: "programming", color: "#8aa8c5", aliases: []),
    "B4X": LanguageMeta(type: "programming", color: "#00e4ff", aliases: ["basic for android"]),
    "BASIC": LanguageMeta(type: "programming", color: "#ff0000", aliases: []),
    "BQN": LanguageMeta(type: "programming", color: "#2b7067", aliases: []),
    "Ballerina": LanguageMeta(type: "programming", color: "#FF5000", aliases: []),
    "Batchfile": LanguageMeta(type: "programming", color: "#C1F12E", aliases: ["bat", "batch", "dosbatch", "winbatch"]),
    "Beef": LanguageMeta(type: "programming", color: "#a52f4e", aliases: []),
    "Befunge": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Berry": LanguageMeta(type: "programming", color: "#15A13C", aliases: ["be"]),
    "BibTeX": LanguageMeta(type: "markup", color: "#778899", aliases: []),
    "BibTeX Style": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Bicep": LanguageMeta(type: "programming", color: "#519aba", aliases: []),
    "Bikeshed": LanguageMeta(type: "markup", color: "#5562ac", aliases: []),
    "Bison": LanguageMeta(type: "programming", color: "#6A463F", aliases: []),
    "BitBake": LanguageMeta(type: "programming", color: "#00bce4", aliases: []),
    "Blade": LanguageMeta(type: "markup", color: "#f7523f", aliases: []),
    "BlitzBasic": LanguageMeta(type: "programming", color: "#00FFAE", aliases: ["b3d", "blitz3d", "blitzplus", "bplus"]),
    "BlitzMax": LanguageMeta(type: "programming", color: "#cd6400", aliases: ["bmax"]),
    "Bluespec": LanguageMeta(type: "programming", color: "#12223c", aliases: ["bluespec bsv", "bsv"]),
    "Bluespec BH": LanguageMeta(type: "programming", color: "#12223c", aliases: ["bh", "bluespec classic"]),
    "Boo": LanguageMeta(type: "programming", color: "#d4bec1", aliases: []),
    "Boogie": LanguageMeta(type: "programming", color: "#c80fa0", aliases: []),
    "Brainfuck": LanguageMeta(type: "programming", color: "#2F2530", aliases: []),
    "BrighterScript": LanguageMeta(type: "programming", color: "#66AABB", aliases: []),
    "Brightscript": LanguageMeta(type: "programming", color: "#662D91", aliases: []),
    "Browserslist": LanguageMeta(type: "data", color: "#ffd539", aliases: []),
    "Bru": LanguageMeta(type: "markup", color: "#F4AA41", aliases: []),
    "BuildStream": LanguageMeta(type: "data", color: "#006bff", aliases: []),
    "C": LanguageMeta(type: "programming", color: "#555555", aliases: []),
    "C#": LanguageMeta(type: "programming", color: "#178600", aliases: ["csharp", "cake", "cakescript"]),
    "C++": LanguageMeta(type: "programming", color: "#f34b7d", aliases: ["cpp"]),
    "C-ObjDump": LanguageMeta(type: "data", color: nil, aliases: []),
    "C2hs Haskell": LanguageMeta(type: "programming", color: nil, aliases: ["c2hs"]),
    "C3": LanguageMeta(type: "programming", color: "#2563eb", aliases: []),
    "CAP CDS": LanguageMeta(type: "programming", color: "#0092d1", aliases: ["cds"]),
    "CIL": LanguageMeta(type: "data", color: nil, aliases: []),
    "CLIPS": LanguageMeta(type: "programming", color: "#00A300", aliases: []),
    "CMake": LanguageMeta(type: "programming", color: "#DA3434", aliases: []),
    "COBOL": LanguageMeta(type: "programming", color: nil, aliases: []),
    "CODEOWNERS": LanguageMeta(type: "data", color: nil, aliases: []),
    "COLLADA": LanguageMeta(type: "data", color: "#F1A42B", aliases: []),
    "CQL": LanguageMeta(type: "programming", color: "#006091", aliases: []),
    "CSON": LanguageMeta(type: "data", color: "#244776", aliases: []),
    "CSS": LanguageMeta(type: "markup", color: "#663399", aliases: []),
    "CSV": LanguageMeta(type: "data", color: "#237346", aliases: []),
    "CUE": LanguageMeta(type: "programming", color: "#5886E1", aliases: []),
    "CWeb": LanguageMeta(type: "programming", color: "#00007a", aliases: []),
    "Cabal Config": LanguageMeta(type: "data", color: "#483465", aliases: ["Cabal"]),
    "Caddyfile": LanguageMeta(type: "data", color: "#22b638", aliases: ["Caddy"]),
    "Cadence": LanguageMeta(type: "programming", color: "#00ef8b", aliases: []),
    "Cairo": LanguageMeta(type: "programming", color: "#ff4a48", aliases: []),
    "Cairo Zero": LanguageMeta(type: "programming", color: "#ff4a48", aliases: []),
    "CameLIGO": LanguageMeta(type: "programming", color: "#3be133", aliases: []),
    "Cangjie": LanguageMeta(type: "programming", color: "#00868B", aliases: []),
    "Cap'n Proto": LanguageMeta(type: "programming", color: "#c42727", aliases: []),
    "Carbon": LanguageMeta(type: "programming", color: "#222222", aliases: []),
    "CartoCSS": LanguageMeta(type: "programming", color: nil, aliases: ["Carto"]),
    "Ceylon": LanguageMeta(type: "programming", color: "#dfa535", aliases: []),
    "Chapel": LanguageMeta(type: "programming", color: "#8dc63f", aliases: ["chpl"]),
    "Charity": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Checksums": LanguageMeta(type: "data", color: nil, aliases: ["checksum", "hash", "hashes", "sum", "sums"]),
    "ChucK": LanguageMeta(type: "programming", color: "#3f8000", aliases: []),
    "Circom": LanguageMeta(type: "programming", color: "#707575", aliases: []),
    "Cirru": LanguageMeta(type: "programming", color: "#ccccff", aliases: []),
    "Clarion": LanguageMeta(type: "programming", color: "#db901e", aliases: []),
    "Clarity": LanguageMeta(type: "programming", color: "#5546ff", aliases: []),
    "Classic ASP": LanguageMeta(type: "programming", color: "#6a40fd", aliases: ["asp"]),
    "Clean": LanguageMeta(type: "programming", color: "#3F85AF", aliases: []),
    "Click": LanguageMeta(type: "programming", color: "#E4E6F3", aliases: []),
    "Clojure": LanguageMeta(type: "programming", color: "#db5855", aliases: []),
    "Closure Templates": LanguageMeta(type: "markup", color: "#0d948f", aliases: ["soy"]),
    "Cloud Firestore Security Rules": LanguageMeta(type: "data", color: "#FFA000", aliases: []),
    "Clue": LanguageMeta(type: "programming", color: "#0009b5", aliases: []),
    "CoNLL-U": LanguageMeta(type: "data", color: nil, aliases: ["CoNLL", "CoNLL-X"]),
    "CodeQL": LanguageMeta(type: "programming", color: "#140f46", aliases: ["ql"]),
    "CoffeeScript": LanguageMeta(type: "programming", color: "#244776", aliases: ["coffee", "coffee-script"]),
    "ColdFusion": LanguageMeta(type: "programming", color: "#ed2cd6", aliases: ["cfm", "cfml", "coldfusion html"]),
    "ColdFusion CFC": LanguageMeta(type: "programming", color: "#ed2cd6", aliases: ["cfc"]),
    "Common Lisp": LanguageMeta(type: "programming", color: "#3fb68b", aliases: ["lisp"]),
    "Common Workflow Language": LanguageMeta(type: "programming", color: "#B5314C", aliases: ["cwl"]),
    "Component Pascal": LanguageMeta(type: "programming", color: "#B0CE4E", aliases: []),
    "Cooklang": LanguageMeta(type: "markup", color: "#E15A29", aliases: []),
    "Cool": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Cpp-ObjDump": LanguageMeta(type: "data", color: nil, aliases: ["c++-objdump"]),
    "Creole": LanguageMeta(type: "prose", color: nil, aliases: []),
    "Crystal": LanguageMeta(type: "programming", color: "#000100", aliases: []),
    "Csound": LanguageMeta(type: "programming", color: "#1a1a1a", aliases: ["csound-orc"]),
    "Csound Document": LanguageMeta(type: "programming", color: "#1a1a1a", aliases: ["csound-csd"]),
    "Csound Score": LanguageMeta(type: "programming", color: "#1a1a1a", aliases: ["csound-sco"]),
    "Cuda": LanguageMeta(type: "programming", color: "#3A4E3A", aliases: []),
    "Cue Sheet": LanguageMeta(type: "data", color: nil, aliases: []),
    "Curry": LanguageMeta(type: "programming", color: "#531242", aliases: []),
    "Cycript": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Cylc": LanguageMeta(type: "data", color: "#00b3fd", aliases: []),
    "Cypher": LanguageMeta(type: "programming", color: "#34c0eb", aliases: []),
    "Cython": LanguageMeta(type: "programming", color: "#fedf5b", aliases: ["pyrex"]),
    "D": LanguageMeta(type: "programming", color: "#ba595e", aliases: ["Dlang"]),
    "D-ObjDump": LanguageMeta(type: "data", color: nil, aliases: []),
    "D2": LanguageMeta(type: "markup", color: "#526ee8", aliases: ["d2lang"]),
    "DIGITAL Command Language": LanguageMeta(type: "programming", color: nil, aliases: ["dcl"]),
    "DM": LanguageMeta(type: "programming", color: "#447265", aliases: ["byond"]),
    "DNS Zone": LanguageMeta(type: "data", color: nil, aliases: []),
    "DTrace": LanguageMeta(type: "programming", color: nil, aliases: ["dtrace-script"]),
    "Dafny": LanguageMeta(type: "programming", color: "#FFEC25", aliases: []),
    "Darcs Patch": LanguageMeta(type: "data", color: "#8eff23", aliases: ["dpatch"]),
    "Dart": LanguageMeta(type: "programming", color: "#00B4AB", aliases: []),
    "Daslang": LanguageMeta(type: "programming", color: "#d3d3d3", aliases: []),
    "DataWeave": LanguageMeta(type: "programming", color: "#003a52", aliases: []),
    "Debian Package Control File": LanguageMeta(type: "data", color: "#D70751", aliases: []),
    "DenizenScript": LanguageMeta(type: "programming", color: "#FBEE96", aliases: []),
    "Dhall": LanguageMeta(type: "programming", color: "#dfafff", aliases: []),
    "Diff": LanguageMeta(type: "data", color: nil, aliases: ["udiff"]),
    "DirectX 3D File": LanguageMeta(type: "data", color: "#aace60", aliases: []),
    "Dockerfile": LanguageMeta(type: "programming", color: "#384d54", aliases: ["Containerfile"]),
    "Dogescript": LanguageMeta(type: "programming", color: "#cca760", aliases: []),
    "Dotenv": LanguageMeta(type: "data", color: "#e5d559", aliases: []),
    "Dune": LanguageMeta(type: "programming", color: "#89421e", aliases: []),
    "Dylan": LanguageMeta(type: "programming", color: "#6c616e", aliases: []),
    "E": LanguageMeta(type: "programming", color: "#ccce35", aliases: []),
    "E-mail": LanguageMeta(type: "data", color: nil, aliases: ["email", "eml", "mail", "mbox"]),
    "EBNF": LanguageMeta(type: "data", color: nil, aliases: []),
    "ECL": LanguageMeta(type: "programming", color: "#8a1267", aliases: []),
    "ECLiPSe": LanguageMeta(type: "programming", color: "#001d9d", aliases: []),
    "EJS": LanguageMeta(type: "markup", color: "#a91e50", aliases: []),
    "EQ": LanguageMeta(type: "programming", color: "#a78649", aliases: []),
    "Eagle": LanguageMeta(type: "data", color: nil, aliases: []),
    "Earthly": LanguageMeta(type: "programming", color: "#2af0ff", aliases: ["Earthfile"]),
    "Easybuild": LanguageMeta(type: "data", color: "#069406", aliases: []),
    "Ecere Projects": LanguageMeta(type: "data", color: "#913960", aliases: []),
    "Ecmarkup": LanguageMeta(type: "markup", color: "#eb8131", aliases: ["ecmarkdown"]),
    "Edge": LanguageMeta(type: "markup", color: "#0dffe0", aliases: []),
    "EdgeQL": LanguageMeta(type: "programming", color: "#31A7FF", aliases: ["esdl"]),
    "EditorConfig": LanguageMeta(type: "data", color: "#fff1f2", aliases: ["editor-config"]),
    "Edje Data Collection": LanguageMeta(type: "data", color: nil, aliases: []),
    "Eiffel": LanguageMeta(type: "programming", color: "#4d6977", aliases: []),
    "Elixir": LanguageMeta(type: "programming", color: "#6e4a7e", aliases: []),
    "Elm": LanguageMeta(type: "programming", color: "#60B5CC", aliases: []),
    "Elvish": LanguageMeta(type: "programming", color: "#55BB55", aliases: []),
    "Elvish Transcript": LanguageMeta(type: "programming", color: "#55BB55", aliases: []),
    "Emacs Lisp": LanguageMeta(type: "programming", color: "#c065db", aliases: ["cask", "eask", "elisp", "emacs"]),
    "EmberScript": LanguageMeta(type: "programming", color: "#FFF4F3", aliases: []),
    "Erlang": LanguageMeta(type: "programming", color: "#B83998", aliases: []),
    "Euphoria": LanguageMeta(type: "programming", color: "#FF790B", aliases: []),
    "F#": LanguageMeta(type: "programming", color: "#b845fc", aliases: ["fsharp"]),
    "F*": LanguageMeta(type: "programming", color: "#572e30", aliases: ["fstar"]),
    "FIGlet Font": LanguageMeta(type: "data", color: "#FFDDBB", aliases: ["FIGfont"]),
    "FIRRTL": LanguageMeta(type: "programming", color: "#2f632f", aliases: []),
    "FLUX": LanguageMeta(type: "programming", color: "#88ccff", aliases: []),
    "Factor": LanguageMeta(type: "programming", color: "#636746", aliases: []),
    "Fancy": LanguageMeta(type: "programming", color: "#7b9db4", aliases: []),
    "Fantom": LanguageMeta(type: "programming", color: "#14253c", aliases: []),
    "Faust": LanguageMeta(type: "programming", color: "#c37240", aliases: []),
    "Fennel": LanguageMeta(type: "programming", color: "#fff3d7", aliases: []),
    "Filebench WML": LanguageMeta(type: "programming", color: "#F6B900", aliases: []),
    "Filterscript": LanguageMeta(type: "programming", color: nil, aliases: []),
    "FlatBuffers": LanguageMeta(type: "data", color: "#ed284a", aliases: []),
    "Flix": LanguageMeta(type: "programming", color: "#d44a45", aliases: []),
    "Fluent": LanguageMeta(type: "programming", color: "#ffcc33", aliases: []),
    "Formatted": LanguageMeta(type: "data", color: nil, aliases: []),
    "Forth": LanguageMeta(type: "programming", color: "#341708", aliases: []),
    "Fortran": LanguageMeta(type: "programming", color: "#4d41b1", aliases: []),
    "Fortran Free Form": LanguageMeta(type: "programming", color: "#4d41b1", aliases: []),
    "FreeBASIC": LanguageMeta(type: "programming", color: "#141AC9", aliases: ["fb"]),
    "FreeMarker": LanguageMeta(type: "programming", color: "#0050b2", aliases: ["ftl"]),
    "Frege": LanguageMeta(type: "programming", color: "#00cafe", aliases: []),
    "Futhark": LanguageMeta(type: "programming", color: "#5f021f", aliases: []),
    "G-code": LanguageMeta(type: "programming", color: "#D08CF2", aliases: []),
    "GAML": LanguageMeta(type: "programming", color: "#FFC766", aliases: []),
    "GAMS": LanguageMeta(type: "programming", color: "#f49a22", aliases: []),
    "GAP": LanguageMeta(type: "programming", color: "#0000cc", aliases: []),
    "GCC Machine Description": LanguageMeta(type: "programming", color: "#FFCFAB", aliases: []),
    "GDB": LanguageMeta(type: "programming", color: nil, aliases: []),
    "GDScript": LanguageMeta(type: "programming", color: "#355570", aliases: []),
    "GDShader": LanguageMeta(type: "programming", color: "#478CBF", aliases: []),
    "GEDCOM": LanguageMeta(type: "data", color: "#003058", aliases: []),
    "GLSL": LanguageMeta(type: "programming", color: "#5686a5", aliases: []),
    "GN": LanguageMeta(type: "data", color: nil, aliases: []),
    "GSC": LanguageMeta(type: "programming", color: "#FF6800", aliases: []),
    "Game Maker Language": LanguageMeta(type: "programming", color: "#71b417", aliases: []),
    "Gemfile.lock": LanguageMeta(type: "data", color: "#701516", aliases: []),
    "Gemini": LanguageMeta(type: "prose", color: "#ff6900", aliases: ["gemtext"]),
    "Genero 4gl": LanguageMeta(type: "programming", color: "#63408e", aliases: []),
    "Genero per": LanguageMeta(type: "markup", color: "#d8df39", aliases: []),
    "Genie": LanguageMeta(type: "programming", color: "#fb855d", aliases: []),
    "Genshi": LanguageMeta(type: "programming", color: "#951531", aliases: ["xml+genshi", "xml+kid"]),
    "Gentoo Ebuild": LanguageMeta(type: "programming", color: "#9400ff", aliases: []),
    "Gentoo Eclass": LanguageMeta(type: "programming", color: "#9400ff", aliases: []),
    "Gerber Image": LanguageMeta(type: "data", color: "#d20b00", aliases: ["rs-274x"]),
    "Gettext Catalog": LanguageMeta(type: "prose", color: nil, aliases: ["pot"]),
    "Gherkin": LanguageMeta(type: "programming", color: "#5B2063", aliases: ["cucumber"]),
    "Git Attributes": LanguageMeta(type: "data", color: "#F44D27", aliases: ["gitattributes"]),
    "Git Commit": LanguageMeta(type: "data", color: "#F44D27", aliases: ["commit"]),
    "Git Config": LanguageMeta(type: "data", color: "#F44D27", aliases: ["gitconfig", "gitmodules"]),
    "Git Revision List": LanguageMeta(type: "data", color: "#F44D27", aliases: ["Git Blame Ignore Revs"]),
    "Gleam": LanguageMeta(type: "programming", color: "#ffaff3", aliases: []),
    "Glimmer JS": LanguageMeta(type: "programming", color: "#F5835F", aliases: ["gjs"]),
    "Glimmer TS": LanguageMeta(type: "programming", color: "#3178c6", aliases: ["gts"]),
    "Glyph": LanguageMeta(type: "programming", color: "#c1ac7f", aliases: []),
    "Glyph Bitmap Distribution Format": LanguageMeta(type: "data", color: nil, aliases: []),
    "Gnuplot": LanguageMeta(type: "programming", color: "#f0a9f0", aliases: []),
    "Go": LanguageMeta(type: "programming", color: "#00ADD8", aliases: ["golang"]),
    "Go Checksums": LanguageMeta(type: "data", color: "#00ADD8", aliases: ["go.sum", "go sum", "go.work.sum", "go work sum"]),
    "Go Module": LanguageMeta(type: "data", color: "#00ADD8", aliases: ["go.mod", "go mod"]),
    "Go Template": LanguageMeta(type: "markup", color: "#00ADD8", aliases: ["gotmpl"]),
    "Go Workspace": LanguageMeta(type: "data", color: "#00ADD8", aliases: ["go.work", "go work"]),
    "Godot Resource": LanguageMeta(type: "data", color: "#355570", aliases: []),
    "Golo": LanguageMeta(type: "programming", color: "#88562A", aliases: []),
    "Gosu": LanguageMeta(type: "programming", color: "#82937f", aliases: []),
    "Grace": LanguageMeta(type: "programming", color: "#615f8b", aliases: []),
    "Gradle": LanguageMeta(type: "data", color: "#02303a", aliases: []),
    "Gradle Kotlin DSL": LanguageMeta(type: "data", color: "#02303a", aliases: []),
    "Grammatical Framework": LanguageMeta(type: "programming", color: "#ff0000", aliases: ["gf"]),
    "Graph Modeling Language": LanguageMeta(type: "data", color: nil, aliases: []),
    "GraphQL": LanguageMeta(type: "data", color: "#e10098", aliases: []),
    "Graphviz (DOT)": LanguageMeta(type: "data", color: "#2596be", aliases: []),
    "Groovy": LanguageMeta(type: "programming", color: "#4298b8", aliases: []),
    "Groovy Server Pages": LanguageMeta(type: "programming", color: "#4298b8", aliases: ["gsp", "java server page"]),
    "HAProxy": LanguageMeta(type: "data", color: "#106da9", aliases: []),
    "HCL": LanguageMeta(type: "programming", color: "#844FBA", aliases: ["HashiCorp Configuration Language", "opentofu", "terraform"]),
    "HIP": LanguageMeta(type: "programming", color: "#4F3A4F", aliases: []),
    "HLSL": LanguageMeta(type: "programming", color: "#aace60", aliases: []),
    "HOCON": LanguageMeta(type: "data", color: "#9ff8ee", aliases: []),
    "HTML": LanguageMeta(type: "markup", color: "#e34c26", aliases: ["xhtml"]),
    "HTML+ECR": LanguageMeta(type: "markup", color: "#2e1052", aliases: ["ecr"]),
    "HTML+EEX": LanguageMeta(type: "markup", color: "#6e4a7e", aliases: ["eex", "heex", "leex"]),
    "HTML+ERB": LanguageMeta(type: "markup", color: "#701516", aliases: ["erb", "rhtml", "html+ruby"]),
    "HTML+PHP": LanguageMeta(type: "markup", color: "#4f5d95", aliases: []),
    "HTML+Razor": LanguageMeta(type: "markup", color: "#512be4", aliases: ["razor"]),
    "HTTP": LanguageMeta(type: "data", color: "#005C9C", aliases: []),
    "HXML": LanguageMeta(type: "data", color: "#f68712", aliases: []),
    "Hack": LanguageMeta(type: "programming", color: "#878787", aliases: []),
    "Haml": LanguageMeta(type: "markup", color: "#ece2a9", aliases: []),
    "Handlebars": LanguageMeta(type: "markup", color: "#f7931e", aliases: ["hbs", "htmlbars"]),
    "Harbour": LanguageMeta(type: "programming", color: "#0e60e3", aliases: []),
    "Hare": LanguageMeta(type: "programming", color: "#9d7424", aliases: []),
    "Haskell": LanguageMeta(type: "programming", color: "#5e5086", aliases: []),
    "Haxe": LanguageMeta(type: "programming", color: "#df7900", aliases: []),
    "HiveQL": LanguageMeta(type: "programming", color: "#dce200", aliases: []),
    "HolyC": LanguageMeta(type: "programming", color: "#ffefaf", aliases: []),
    "Hosts File": LanguageMeta(type: "data", color: "#308888", aliases: ["hosts"]),
    "Hurl": LanguageMeta(type: "programming", color: "#FF0288", aliases: []),
    "Hy": LanguageMeta(type: "programming", color: "#7790B2", aliases: ["hylang"]),
    "HyPhy": LanguageMeta(type: "programming", color: nil, aliases: []),
    "IDL": LanguageMeta(type: "programming", color: "#a3522f", aliases: []),
    "IGOR Pro": LanguageMeta(type: "programming", color: "#0000cc", aliases: ["igor", "igorpro"]),
    "IL Assembly": LanguageMeta(type: "programming", color: "#512BD4", aliases: ["ilasm", "msil"]),
    "INI": LanguageMeta(type: "data", color: "#d1dbe0", aliases: ["dosini"]),
    "IRC log": LanguageMeta(type: "data", color: nil, aliases: ["irc", "irc logs"]),
    "ISPC": LanguageMeta(type: "programming", color: "#2D68B1", aliases: []),
    "Idris": LanguageMeta(type: "programming", color: "#b30000", aliases: []),
    "Ignore List": LanguageMeta(type: "data", color: "#000000", aliases: ["ignore", "gitignore", "git-ignore"]),
    "ImageJ Macro": LanguageMeta(type: "programming", color: "#99AAFF", aliases: ["ijm"]),
    "Imba": LanguageMeta(type: "programming", color: "#16cec6", aliases: []),
    "Inform 7": LanguageMeta(type: "programming", color: nil, aliases: ["i7", "inform7"]),
    "Ink": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Inno Setup": LanguageMeta(type: "programming", color: "#264b99", aliases: []),
    "Io": LanguageMeta(type: "programming", color: "#a9188d", aliases: []),
    "Ioke": LanguageMeta(type: "programming", color: "#078193", aliases: []),
    "Isabelle": LanguageMeta(type: "programming", color: "#FEFE00", aliases: []),
    "Isabelle ROOT": LanguageMeta(type: "programming", color: "#FEFE00", aliases: []),
    "J": LanguageMeta(type: "programming", color: "#9EEDFF", aliases: []),
    "JAR Manifest": LanguageMeta(type: "data", color: "#b07219", aliases: []),
    "JCL": LanguageMeta(type: "programming", color: "#d90e09", aliases: []),
    "JFlex": LanguageMeta(type: "programming", color: "#DBCA00", aliases: []),
    "JSON": LanguageMeta(type: "data", color: "#292929", aliases: ["geojson", "jsonl", "sarif", "topojson"]),
    "JSON with Comments": LanguageMeta(type: "data", color: "#292929", aliases: ["jsonc"]),
    "JSON5": LanguageMeta(type: "data", color: "#267CB9", aliases: []),
    "JSONLD": LanguageMeta(type: "data", color: "#0c479c", aliases: []),
    "JSONiq": LanguageMeta(type: "programming", color: "#40d47e", aliases: []),
    "Jac": LanguageMeta(type: "programming", color: "#FC792D", aliases: []),
    "Jai": LanguageMeta(type: "programming", color: "#ab8b4b", aliases: []),
    "Janet": LanguageMeta(type: "programming", color: "#0886a5", aliases: []),
    "Jasmin": LanguageMeta(type: "programming", color: "#d03600", aliases: []),
    "Java": LanguageMeta(type: "programming", color: "#b07219", aliases: []),
    "Java Properties": LanguageMeta(type: "data", color: "#2A6277", aliases: []),
    "Java Server Pages": LanguageMeta(type: "programming", color: "#2A6277", aliases: ["jsp"]),
    "Java Template Engine": LanguageMeta(type: "programming", color: "#2A6277", aliases: ["jte"]),
    "JavaScript": LanguageMeta(type: "programming", color: "#f1e05a", aliases: ["js", "node"]),
    "JavaScript+ERB": LanguageMeta(type: "programming", color: "#f1e05a", aliases: []),
    "Jest Snapshot": LanguageMeta(type: "data", color: "#15c213", aliases: []),
    "JetBrains MPS": LanguageMeta(type: "programming", color: "#21D789", aliases: ["mps"]),
    "Jinja": LanguageMeta(type: "markup", color: "#a52a22", aliases: ["django", "html+django", "html+jinja", "htmldjango"]),
    "Jison": LanguageMeta(type: "programming", color: "#56b3cb", aliases: []),
    "Jison Lex": LanguageMeta(type: "programming", color: "#56b3cb", aliases: []),
    "Jolie": LanguageMeta(type: "programming", color: "#843179", aliases: []),
    "Jsonnet": LanguageMeta(type: "programming", color: "#0064bd", aliases: []),
    "Julia": LanguageMeta(type: "programming", color: "#a270ba", aliases: []),
    "Julia REPL": LanguageMeta(type: "programming", color: "#a270ba", aliases: []),
    "Jupyter Notebook": LanguageMeta(type: "markup", color: "#DA5B0B", aliases: ["IPython Notebook"]),
    "Just": LanguageMeta(type: "programming", color: "#384d54", aliases: ["Justfile"]),
    "KCL": LanguageMeta(type: "programming", color: "#7ABABF", aliases: []),
    "KDL": LanguageMeta(type: "data", color: "#ffb3b3", aliases: []),
    "KFramework": LanguageMeta(type: "programming", color: "#4195c5", aliases: []),
    "KRL": LanguageMeta(type: "programming", color: "#28430A", aliases: []),
    "Kaitai Struct": LanguageMeta(type: "programming", color: "#773b37", aliases: ["ksy"]),
    "KakouneScript": LanguageMeta(type: "programming", color: "#6f8042", aliases: ["kak", "kakscript"]),
    "KerboScript": LanguageMeta(type: "programming", color: "#41adf0", aliases: []),
    "KiCad Layout": LanguageMeta(type: "data", color: "#2f4aab", aliases: ["pcbnew"]),
    "KiCad Legacy Layout": LanguageMeta(type: "data", color: "#2f4aab", aliases: []),
    "KiCad Schematic": LanguageMeta(type: "data", color: "#2f4aab", aliases: ["eeschema schematic"]),
    "Kickstart": LanguageMeta(type: "data", color: nil, aliases: []),
    "Kit": LanguageMeta(type: "markup", color: nil, aliases: []),
    "KoLmafia ASH": LanguageMeta(type: "programming", color: "#B9D9B9", aliases: []),
    "Koka": LanguageMeta(type: "programming", color: "#215166", aliases: []),
    "Kotlin": LanguageMeta(type: "programming", color: "#A97BFF", aliases: []),
    "Kusto": LanguageMeta(type: "data", color: nil, aliases: []),
    "LFE": LanguageMeta(type: "programming", color: "#4C3023", aliases: []),
    "LLVM": LanguageMeta(type: "programming", color: "#185619", aliases: []),
    "LOLCODE": LanguageMeta(type: "programming", color: "#cc9900", aliases: []),
    "LSL": LanguageMeta(type: "programming", color: "#3d9970", aliases: []),
    "LTspice Symbol": LanguageMeta(type: "data", color: nil, aliases: []),
    "LabVIEW": LanguageMeta(type: "programming", color: "#fede06", aliases: []),
    "Lambdapi": LanguageMeta(type: "programming", color: "#8027a3", aliases: []),
    "Langium": LanguageMeta(type: "programming", color: "#2c8c87", aliases: []),
    "Lark": LanguageMeta(type: "data", color: "#2980B9", aliases: []),
    "Lasso": LanguageMeta(type: "programming", color: "#999999", aliases: ["lassoscript"]),
    "Latte": LanguageMeta(type: "markup", color: "#f2a542", aliases: []),
    "Lean": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Lean 4": LanguageMeta(type: "programming", color: nil, aliases: ["lean4"]),
    "Leo": LanguageMeta(type: "programming", color: "#C4FFC2", aliases: []),
    "Less": LanguageMeta(type: "markup", color: "#1d365d", aliases: ["less-css"]),
    "Lex": LanguageMeta(type: "programming", color: "#DBCA00", aliases: ["flex"]),
    "LigoLANG": LanguageMeta(type: "programming", color: "#0e74ff", aliases: []),
    "LilyPond": LanguageMeta(type: "programming", color: "#9ccc7c", aliases: []),
    "Limbo": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Linear Programming": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Linker Script": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Linux Kernel Module": LanguageMeta(type: "data", color: nil, aliases: []),
    "Liquid": LanguageMeta(type: "markup", color: "#67b8de", aliases: []),
    "Liquidsoap": LanguageMeta(type: "programming", color: "#990066", aliases: []),
    "Literate Agda": LanguageMeta(type: "programming", color: "#315665", aliases: []),
    "Literate CoffeeScript": LanguageMeta(type: "programming", color: "#244776", aliases: ["litcoffee"]),
    "Literate Haskell": LanguageMeta(type: "programming", color: "#5e5086", aliases: ["lhaskell", "lhs"]),
    "LiveCode Script": LanguageMeta(type: "programming", color: "#0c5ba5", aliases: []),
    "LiveScript": LanguageMeta(type: "programming", color: "#499886", aliases: ["live-script", "ls"]),
    "Logos": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Logtalk": LanguageMeta(type: "programming", color: "#295b9a", aliases: []),
    "LookML": LanguageMeta(type: "programming", color: "#652B81", aliases: []),
    "LoomScript": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Lua": LanguageMeta(type: "programming", color: "#000080", aliases: []),
    "Luau": LanguageMeta(type: "programming", color: "#00A2FF", aliases: []),
    "M": LanguageMeta(type: "programming", color: nil, aliases: ["mumps"]),
    "M3U": LanguageMeta(type: "data", color: "#179C7D", aliases: ["hls playlist", "m3u playlist"]),
    "M4": LanguageMeta(type: "programming", color: nil, aliases: []),
    "M4Sugar": LanguageMeta(type: "programming", color: nil, aliases: ["autoconf"]),
    "MATLAB": LanguageMeta(type: "programming", color: "#e16737", aliases: ["octave"]),
    "MAXScript": LanguageMeta(type: "programming", color: "#00a6a6", aliases: []),
    "MDX": LanguageMeta(type: "markup", color: "#fcb32c", aliases: []),
    "MLIR": LanguageMeta(type: "programming", color: "#5EC8DB", aliases: []),
    "MQL4": LanguageMeta(type: "programming", color: "#62A8D6", aliases: []),
    "MQL5": LanguageMeta(type: "programming", color: "#4A76B8", aliases: []),
    "MTML": LanguageMeta(type: "markup", color: "#b7e1f4", aliases: []),
    "MUF": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Macaulay2": LanguageMeta(type: "programming", color: "#d8ffff", aliases: ["m2"]),
    "Makefile": LanguageMeta(type: "programming", color: "#427819", aliases: ["bsdmake", "make", "mf"]),
    "Mako": LanguageMeta(type: "programming", color: "#7e858d", aliases: []),
    "Markdown": LanguageMeta(type: "prose", color: "#083fa1", aliases: ["md", "pandoc"]),
    "Marko": LanguageMeta(type: "markup", color: "#42bff2", aliases: ["markojs"]),
    "Mask": LanguageMeta(type: "markup", color: "#f97732", aliases: []),
    "Mathematical Programming System": LanguageMeta(type: "programming", color: "#0530ad", aliases: []),
    "Maven POM": LanguageMeta(type: "data", color: nil, aliases: []),
    "Max": LanguageMeta(type: "programming", color: "#c4a79c", aliases: ["max/msp", "maxmsp"]),
    "MeTTa": LanguageMeta(type: "programming", color: "#6a5acd", aliases: []),
    "Mercury": LanguageMeta(type: "programming", color: "#ff2b2b", aliases: []),
    "Mermaid": LanguageMeta(type: "markup", color: "#ff3670", aliases: ["mermaid example"]),
    "Meson": LanguageMeta(type: "programming", color: "#007800", aliases: []),
    "Metal": LanguageMeta(type: "programming", color: "#8f14e9", aliases: []),
    "Microsoft Developer Studio Project": LanguageMeta(type: "data", color: nil, aliases: []),
    "Microsoft Visual Studio Solution": LanguageMeta(type: "data", color: nil, aliases: []),
    "MiniD": LanguageMeta(type: "programming", color: nil, aliases: []),
    "MiniYAML": LanguageMeta(type: "data", color: "#ff1111", aliases: []),
    "MiniZinc": LanguageMeta(type: "programming", color: "#06a9e6", aliases: []),
    "MiniZinc Data": LanguageMeta(type: "data", color: nil, aliases: []),
    "Mint": LanguageMeta(type: "programming", color: "#02b046", aliases: []),
    "Mirah": LanguageMeta(type: "programming", color: "#c7a938", aliases: []),
    "Modelica": LanguageMeta(type: "programming", color: "#de1d31", aliases: []),
    "Modula-2": LanguageMeta(type: "programming", color: "#10253f", aliases: []),
    "Modula-3": LanguageMeta(type: "programming", color: "#223388", aliases: []),
    "Module Management System": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Mojo": LanguageMeta(type: "programming", color: "#ff4c1f", aliases: []),
    "Monkey": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Monkey C": LanguageMeta(type: "programming", color: "#8D6747", aliases: []),
    "Moocode": LanguageMeta(type: "programming", color: nil, aliases: []),
    "MoonBit": LanguageMeta(type: "programming", color: "#b92381", aliases: []),
    "MoonScript": LanguageMeta(type: "programming", color: "#ff4585", aliases: []),
    "Motoko": LanguageMeta(type: "programming", color: "#fbb03b", aliases: []),
    "Motorola 68K Assembly": LanguageMeta(type: "programming", color: "#005daa", aliases: ["m68k"]),
    "Move": LanguageMeta(type: "programming", color: "#4a137a", aliases: []),
    "Muse": LanguageMeta(type: "prose", color: nil, aliases: ["amusewiki", "emacs muse"]),
    "Mustache": LanguageMeta(type: "markup", color: "#724b3b", aliases: []),
    "Myghty": LanguageMeta(type: "programming", color: nil, aliases: []),
    "NASL": LanguageMeta(type: "programming", color: nil, aliases: []),
    "NCL": LanguageMeta(type: "programming", color: "#28431f", aliases: []),
    "NEON": LanguageMeta(type: "data", color: nil, aliases: ["nette object notation", "ne-on"]),
    "NL": LanguageMeta(type: "data", color: nil, aliases: []),
    "NMODL": LanguageMeta(type: "programming", color: "#00356B", aliases: []),
    "NPM Config": LanguageMeta(type: "data", color: "#cb3837", aliases: ["npmrc"]),
    "NSIS": LanguageMeta(type: "programming", color: nil, aliases: []),
    "NWScript": LanguageMeta(type: "programming", color: "#111522", aliases: []),
    "Nasal": LanguageMeta(type: "programming", color: "#1d2c4e", aliases: []),
    "Nearley": LanguageMeta(type: "programming", color: "#990000", aliases: []),
    "Nemerle": LanguageMeta(type: "programming", color: "#3d3c6e", aliases: []),
    "NetLinx": LanguageMeta(type: "programming", color: "#0aa0ff", aliases: []),
    "NetLinx+ERB": LanguageMeta(type: "programming", color: "#747faa", aliases: []),
    "NetLogo": LanguageMeta(type: "programming", color: "#ff6375", aliases: []),
    "NewLisp": LanguageMeta(type: "programming", color: "#87AED7", aliases: []),
    "Nextflow": LanguageMeta(type: "programming", color: "#3ac486", aliases: []),
    "Nginx": LanguageMeta(type: "data", color: "#009639", aliases: ["nginx configuration file"]),
    "Nickel": LanguageMeta(type: "programming", color: "#E0C3FC", aliases: []),
    "Nim": LanguageMeta(type: "programming", color: "#ffc200", aliases: []),
    "Ninja": LanguageMeta(type: "data", color: nil, aliases: []),
    "Nit": LanguageMeta(type: "programming", color: "#009917", aliases: []),
    "Nix": LanguageMeta(type: "programming", color: "#7e7eff", aliases: ["nixos"]),
    "Noir": LanguageMeta(type: "programming", color: "#2f1f49", aliases: ["nargo"]),
    "Nu": LanguageMeta(type: "programming", color: "#c9df40", aliases: ["nush"]),
    "NumPy": LanguageMeta(type: "programming", color: "#9C8AF9", aliases: []),
    "Nunjucks": LanguageMeta(type: "markup", color: "#3d8137", aliases: ["njk"]),
    "Nushell": LanguageMeta(type: "programming", color: "#4E9906", aliases: ["nu-script", "nushell-script"]),
    "OASv2-json": LanguageMeta(type: "data", color: "#85ea2d", aliases: []),
    "OASv2-yaml": LanguageMeta(type: "data", color: "#85ea2d", aliases: []),
    "OASv3-json": LanguageMeta(type: "data", color: "#85ea2d", aliases: []),
    "OASv3-yaml": LanguageMeta(type: "data", color: "#85ea2d", aliases: []),
    "OCaml": LanguageMeta(type: "programming", color: "#ef7a08", aliases: []),
    "OMNeT++ MSG": LanguageMeta(type: "programming", color: "#a0e0a0", aliases: ["omnetpp-msg"]),
    "OMNeT++ NED": LanguageMeta(type: "programming", color: "#08607c", aliases: ["omnetpp-ned"]),
    "Oberon": LanguageMeta(type: "programming", color: nil, aliases: []),
    "ObjDump": LanguageMeta(type: "data", color: nil, aliases: []),
    "Object Data Instance Notation": LanguageMeta(type: "data", color: nil, aliases: []),
    "ObjectScript": LanguageMeta(type: "programming", color: "#424893", aliases: []),
    "Objective-C": LanguageMeta(type: "programming", color: "#438eff", aliases: ["obj-c", "objc", "objectivec"]),
    "Objective-C++": LanguageMeta(type: "programming", color: "#6866fb", aliases: ["obj-c++", "objc++", "objectivec++"]),
    "Objective-J": LanguageMeta(type: "programming", color: "#ff0c5a", aliases: ["obj-j", "objectivej", "objj"]),
    "Odin": LanguageMeta(type: "programming", color: "#60AFFE", aliases: ["odinlang", "odin-lang"]),
    "Omgrofl": LanguageMeta(type: "programming", color: "#cabbff", aliases: []),
    "Opa": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Opal": LanguageMeta(type: "programming", color: "#f7ede0", aliases: []),
    "Open Policy Agent": LanguageMeta(type: "programming", color: "#7d9199", aliases: []),
    "OpenAPI Specification v2": LanguageMeta(type: "data", color: "#85ea2d", aliases: ["oasv2"]),
    "OpenAPI Specification v3": LanguageMeta(type: "data", color: "#85ea2d", aliases: ["oasv3"]),
    "OpenCL": LanguageMeta(type: "programming", color: "#ed2e2d", aliases: []),
    "OpenEdge ABL": LanguageMeta(type: "programming", color: "#5ce600", aliases: ["progress", "openedge", "abl"]),
    "OpenQASM": LanguageMeta(type: "programming", color: "#AA70FF", aliases: []),
    "OpenRC runscript": LanguageMeta(type: "programming", color: nil, aliases: ["openrc"]),
    "OpenSCAD": LanguageMeta(type: "programming", color: "#e5cd45", aliases: []),
    "OpenStep Property List": LanguageMeta(type: "data", color: nil, aliases: []),
    "OpenType Feature File": LanguageMeta(type: "data", color: nil, aliases: ["AFDKO"]),
    "Option List": LanguageMeta(type: "data", color: "#476732", aliases: ["opts", "ackrc"]),
    "Org": LanguageMeta(type: "prose", color: "#77aa99", aliases: []),
    "OverpassQL": LanguageMeta(type: "programming", color: "#cce2aa", aliases: []),
    "Ox": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Oxygene": LanguageMeta(type: "programming", color: "#cdd0e3", aliases: []),
    "Oz": LanguageMeta(type: "programming", color: "#fab738", aliases: []),
    "P4": LanguageMeta(type: "programming", color: "#7055b5", aliases: []),
    "PDDL": LanguageMeta(type: "programming", color: "#0d00ff", aliases: []),
    "PEG.js": LanguageMeta(type: "programming", color: "#234d6b", aliases: []),
    "PHP": LanguageMeta(type: "programming", color: "#4F5D95", aliases: ["inc"]),
    "PLSQL": LanguageMeta(type: "programming", color: "#dad8d8", aliases: []),
    "PLpgSQL": LanguageMeta(type: "programming", color: "#336790", aliases: []),
    "POV-Ray SDL": LanguageMeta(type: "programming", color: "#6bac65", aliases: ["pov-ray", "povray"]),
    "Pact": LanguageMeta(type: "programming", color: "#F7A8B8", aliases: []),
    "Pan": LanguageMeta(type: "programming", color: "#cc0000", aliases: []),
    "Papyrus": LanguageMeta(type: "programming", color: "#6600cc", aliases: []),
    "Parrot": LanguageMeta(type: "programming", color: "#f3ca0a", aliases: []),
    "Parrot Assembly": LanguageMeta(type: "programming", color: nil, aliases: ["pasm"]),
    "Parrot Internal Representation": LanguageMeta(type: "programming", color: nil, aliases: ["pir"]),
    "Pascal": LanguageMeta(type: "programming", color: "#E3F171", aliases: ["delphi", "objectpascal"]),
    "Pawn": LanguageMeta(type: "programming", color: "#dbb284", aliases: []),
    "Pep8": LanguageMeta(type: "programming", color: "#C76F5B", aliases: []),
    "Perl": LanguageMeta(type: "programming", color: "#0298c3", aliases: ["cperl"]),
    "Pic": LanguageMeta(type: "markup", color: nil, aliases: ["pikchr"]),
    "Pickle": LanguageMeta(type: "data", color: nil, aliases: []),
    "PicoLisp": LanguageMeta(type: "programming", color: "#6067af", aliases: []),
    "PigLatin": LanguageMeta(type: "programming", color: "#fcd7de", aliases: []),
    "Pike": LanguageMeta(type: "programming", color: "#005390", aliases: []),
    "Pip Requirements": LanguageMeta(type: "data", color: "#FFD343", aliases: []),
    "Pkl": LanguageMeta(type: "programming", color: "#6b9543", aliases: []),
    "PlantUML": LanguageMeta(type: "data", color: "#fbbd16", aliases: []),
    "Pod": LanguageMeta(type: "prose", color: nil, aliases: []),
    "Pod 6": LanguageMeta(type: "prose", color: nil, aliases: []),
    "PogoScript": LanguageMeta(type: "programming", color: "#d80074", aliases: []),
    "Polar": LanguageMeta(type: "programming", color: "#ae81ff", aliases: []),
    "Pony": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Portugol": LanguageMeta(type: "programming", color: "#f8bd00", aliases: []),
    "PostCSS": LanguageMeta(type: "markup", color: "#dc3a0c", aliases: []),
    "PostScript": LanguageMeta(type: "markup", color: "#da291c", aliases: ["postscr"]),
    "PowerBuilder": LanguageMeta(type: "programming", color: "#8f0f8d", aliases: []),
    "PowerShell": LanguageMeta(type: "programming", color: "#012456", aliases: ["posh", "pwsh"]),
    "Praat": LanguageMeta(type: "programming", color: "#c8506d", aliases: []),
    "Prisma": LanguageMeta(type: "data", color: "#0c344b", aliases: []),
    "Processing": LanguageMeta(type: "programming", color: "#0096D8", aliases: []),
    "Procfile": LanguageMeta(type: "programming", color: "#3B2F63", aliases: []),
    "Proguard": LanguageMeta(type: "data", color: nil, aliases: []),
    "Prolog": LanguageMeta(type: "programming", color: "#74283c", aliases: []),
    "Promela": LanguageMeta(type: "programming", color: "#de0000", aliases: []),
    "Propeller Spin": LanguageMeta(type: "programming", color: "#7fa2a7", aliases: []),
    "Protocol Buffer": LanguageMeta(type: "data", color: nil, aliases: ["proto", "protobuf", "Protocol Buffers"]),
    "Protocol Buffer Text Format": LanguageMeta(type: "data", color: nil, aliases: ["text proto", "protobuf text format"]),
    "Public Key": LanguageMeta(type: "data", color: nil, aliases: []),
    "Pug": LanguageMeta(type: "markup", color: "#a86454", aliases: []),
    "Puppet": LanguageMeta(type: "programming", color: "#302B6D", aliases: []),
    "Pure Data": LanguageMeta(type: "data", color: nil, aliases: []),
    "PureBasic": LanguageMeta(type: "programming", color: "#5a6986", aliases: []),
    "PureScript": LanguageMeta(type: "programming", color: "#1D222D", aliases: []),
    "Pyret": LanguageMeta(type: "programming", color: "#ee1e10", aliases: []),
    "Python": LanguageMeta(type: "programming", color: "#3572A5", aliases: ["py", "py3", "python3", "rusthon"]),
    "Python console": LanguageMeta(type: "programming", color: "#3572A5", aliases: ["pycon"]),
    "Python traceback": LanguageMeta(type: "data", color: "#3572A5", aliases: []),
    "Q#": LanguageMeta(type: "programming", color: "#fed659", aliases: ["qsharp"]),
    "QML": LanguageMeta(type: "programming", color: "#44a51c", aliases: []),
    "QMake": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Qt Script": LanguageMeta(type: "programming", color: "#00b841", aliases: []),
    "Quake": LanguageMeta(type: "programming", color: "#882233", aliases: []),
    "QuakeC": LanguageMeta(type: "programming", color: "#975777", aliases: []),
    "QuickBASIC": LanguageMeta(type: "programming", color: "#008080", aliases: ["qb", "qbasic", "qb64", "classic qbasic", "classic quickbasic"]),
    "Quint": LanguageMeta(type: "programming", color: "#9d6ce5", aliases: []),
    "R": LanguageMeta(type: "programming", color: "#198CE7", aliases: ["Rscript", "splus"]),
    "RAML": LanguageMeta(type: "markup", color: "#77d9fb", aliases: []),
    "RAScript": LanguageMeta(type: "programming", color: "#2C97FA", aliases: []),
    "RBS": LanguageMeta(type: "data", color: "#701516", aliases: []),
    "RDoc": LanguageMeta(type: "prose", color: "#701516", aliases: []),
    "REALbasic": LanguageMeta(type: "programming", color: nil, aliases: []),
    "REXX": LanguageMeta(type: "programming", color: "#d90e09", aliases: ["arexx"]),
    "RMarkdown": LanguageMeta(type: "prose", color: "#198ce7", aliases: []),
    "RON": LanguageMeta(type: "data", color: "#a62c00", aliases: []),
    "ROS Interface": LanguageMeta(type: "data", color: "#22314e", aliases: ["rosmsg"]),
    "RPC": LanguageMeta(type: "programming", color: nil, aliases: ["rpcgen", "oncrpc", "xdr"]),
    "RPGLE": LanguageMeta(type: "programming", color: "#2BDE21", aliases: ["ile rpg", "sqlrpgle"]),
    "RPM Spec": LanguageMeta(type: "data", color: nil, aliases: ["specfile"]),
    "RUNOFF": LanguageMeta(type: "markup", color: "#665a4e", aliases: []),
    "Racket": LanguageMeta(type: "programming", color: "#3c5caa", aliases: []),
    "Ragel": LanguageMeta(type: "programming", color: "#9d5200", aliases: ["ragel-rb", "ragel-ruby"]),
    "Raku": LanguageMeta(type: "programming", color: "#0000fb", aliases: ["perl6", "perl-6"]),
    "Rascal": LanguageMeta(type: "programming", color: "#fffaa0", aliases: []),
    "Raw token data": LanguageMeta(type: "data", color: nil, aliases: ["raw"]),
    "ReScript": LanguageMeta(type: "programming", color: "#ed5051", aliases: []),
    "Readline Config": LanguageMeta(type: "data", color: nil, aliases: ["inputrc", "readline"]),
    "Reason": LanguageMeta(type: "programming", color: "#ff5847", aliases: []),
    "ReasonLIGO": LanguageMeta(type: "programming", color: "#ff5847", aliases: []),
    "Rebol": LanguageMeta(type: "programming", color: "#358a5b", aliases: []),
    "Record Jar": LanguageMeta(type: "data", color: "#0673ba", aliases: []),
    "Red": LanguageMeta(type: "programming", color: "#f50000", aliases: ["red/system"]),
    "Redcode": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Redirect Rules": LanguageMeta(type: "data", color: nil, aliases: ["redirects"]),
    "Regular Expression": LanguageMeta(type: "data", color: "#009a00", aliases: ["regexp", "regex"]),
    "Ren'Py": LanguageMeta(type: "programming", color: "#ff7f7f", aliases: ["renpy"]),
    "RenderScript": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Rez": LanguageMeta(type: "programming", color: "#FFDAB3", aliases: []),
    "Rich Text Format": LanguageMeta(type: "markup", color: nil, aliases: []),
    "Ring": LanguageMeta(type: "programming", color: "#2D54CB", aliases: []),
    "Riot": LanguageMeta(type: "markup", color: "#A71E49", aliases: []),
    "RobotFramework": LanguageMeta(type: "programming", color: "#00c0b5", aliases: []),
    "Roc": LanguageMeta(type: "programming", color: "#7c38f5", aliases: []),
    "Rocq Prover": LanguageMeta(type: "programming", color: "#d0b68c", aliases: ["coq", "rocq"]),
    "Roff": LanguageMeta(type: "markup", color: "#ecdebe", aliases: ["groff", "man", "manpage", "man page", "man-page", "mdoc", "nroff", "troff"]),
    "Roff Manpage": LanguageMeta(type: "markup", color: "#ecdebe", aliases: []),
    "Rouge": LanguageMeta(type: "programming", color: "#cc0088", aliases: []),
    "RouterOS Script": LanguageMeta(type: "programming", color: "#DE3941", aliases: []),
    "Ruby": LanguageMeta(type: "programming", color: "#701516", aliases: ["jruby", "macruby", "rake", "rb", "rbx"]),
    "Rust": LanguageMeta(type: "programming", color: "#dea584", aliases: ["rs"]),
    "SAS": LanguageMeta(type: "programming", color: "#B34936", aliases: []),
    "SCSS": LanguageMeta(type: "markup", color: "#c6538c", aliases: []),
    "SELinux Policy": LanguageMeta(type: "data", color: nil, aliases: ["SELinux Kernel Policy Language", "sepolicy"]),
    "SMT": LanguageMeta(type: "programming", color: nil, aliases: []),
    "SPARQL": LanguageMeta(type: "data", color: "#0C4597", aliases: []),
    "SQF": LanguageMeta(type: "programming", color: "#3F3F3F", aliases: []),
    "SQL": LanguageMeta(type: "data", color: "#e38c00", aliases: []),
    "SQLPL": LanguageMeta(type: "programming", color: "#e38c00", aliases: []),
    "SRecode Template": LanguageMeta(type: "markup", color: "#348a34", aliases: []),
    "SSH Config": LanguageMeta(type: "data", color: nil, aliases: ["sshconfig", "sshdconfig", "ssh_config", "sshd_config"]),
    "STAR": LanguageMeta(type: "data", color: nil, aliases: []),
    "STL": LanguageMeta(type: "data", color: "#373b5e", aliases: ["ascii stl", "stla"]),
    "STON": LanguageMeta(type: "data", color: nil, aliases: []),
    "SVG": LanguageMeta(type: "data", color: "#ff9900", aliases: []),
    "SWIG": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Sage": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Sail": LanguageMeta(type: "programming", color: "#259dd5", aliases: []),
    "SaltStack": LanguageMeta(type: "programming", color: "#646464", aliases: ["saltstate", "salt"]),
    "Sass": LanguageMeta(type: "markup", color: "#a53b70", aliases: []),
    "Scala": LanguageMeta(type: "programming", color: "#c22d40", aliases: []),
    "Scaml": LanguageMeta(type: "markup", color: "#bd181a", aliases: []),
    "Scenic": LanguageMeta(type: "programming", color: "#fdc700", aliases: []),
    "Scheme": LanguageMeta(type: "programming", color: "#1e4aec", aliases: []),
    "Scilab": LanguageMeta(type: "programming", color: "#ca0f21", aliases: []),
    "Self": LanguageMeta(type: "programming", color: "#0579aa", aliases: []),
    "ShaderLab": LanguageMeta(type: "programming", color: "#222c37", aliases: []),
    "Shell": LanguageMeta(type: "programming", color: "#89e051", aliases: ["sh", "shell-script", "bash", "zsh", "envrc"]),
    "ShellCheck Config": LanguageMeta(type: "data", color: "#cecfcb", aliases: ["shellcheckrc"]),
    "ShellSession": LanguageMeta(type: "programming", color: nil, aliases: ["bash session", "console"]),
    "Shen": LanguageMeta(type: "programming", color: "#120F14", aliases: []),
    "Sieve": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Simple File Verification": LanguageMeta(type: "data", color: "#C9BFED", aliases: ["sfv"]),
    "Singularity": LanguageMeta(type: "programming", color: "#64E6AD", aliases: []),
    "Slang": LanguageMeta(type: "programming", color: "#1fbec9", aliases: []),
    "Slash": LanguageMeta(type: "programming", color: "#007eff", aliases: []),
    "Slice": LanguageMeta(type: "programming", color: "#003fa2", aliases: []),
    "Slim": LanguageMeta(type: "markup", color: "#2b2b2b", aliases: []),
    "Slint": LanguageMeta(type: "markup", color: "#2379F4", aliases: []),
    "SmPL": LanguageMeta(type: "programming", color: "#c94949", aliases: ["coccinelle"]),
    "Smali": LanguageMeta(type: "programming", color: nil, aliases: []),
    "Smalltalk": LanguageMeta(type: "programming", color: "#596706", aliases: ["squeak"]),
    "Smarty": LanguageMeta(type: "programming", color: "#f0c040", aliases: []),
    "Smithy": LanguageMeta(type: "programming", color: "#c44536", aliases: []),
    "Snakemake": LanguageMeta(type: "programming", color: "#419179", aliases: ["snakefile"]),
    "Solidity": LanguageMeta(type: "programming", color: "#AA6746", aliases: []),
    "Soong": LanguageMeta(type: "data", color: nil, aliases: []),
    "SourcePawn": LanguageMeta(type: "programming", color: "#f69e1d", aliases: ["sourcemod"]),
    "SpiceDB Schema": LanguageMeta(type: "data", color: "#a5318a", aliases: []),
    "Spline Font Database": LanguageMeta(type: "data", color: nil, aliases: []),
    "Squirrel": LanguageMeta(type: "programming", color: "#800000", aliases: []),
    "Stan": LanguageMeta(type: "programming", color: "#b2011d", aliases: []),
    "Standard ML": LanguageMeta(type: "programming", color: "#dc566d", aliases: ["sml"]),
    "Starlark": LanguageMeta(type: "programming", color: "#76d275", aliases: ["bazel", "bzl"]),
    "Stata": LanguageMeta(type: "programming", color: "#1a5f91", aliases: []),
    "StringTemplate": LanguageMeta(type: "markup", color: "#3fb34f", aliases: []),
    "Stylus": LanguageMeta(type: "markup", color: "#ff6347", aliases: []),
    "SubRip Text": LanguageMeta(type: "data", color: "#9e0101", aliases: []),
    "SugarSS": LanguageMeta(type: "markup", color: "#2fcc9f", aliases: []),
    "SuperCollider": LanguageMeta(type: "programming", color: "#46390b", aliases: []),
    "SurrealQL": LanguageMeta(type: "programming", color: "#ff00a0", aliases: ["surql"]),
    "Survex data": LanguageMeta(type: "data", color: "#ffcc99", aliases: []),
    "Svelte": LanguageMeta(type: "markup", color: "#ff3e00", aliases: []),
    "Sway": LanguageMeta(type: "programming", color: "#00F58C", aliases: []),
    "Sweave": LanguageMeta(type: "prose", color: "#198ce7", aliases: []),
    "Swift": LanguageMeta(type: "programming", color: "#F05138", aliases: []),
    "SystemVerilog": LanguageMeta(type: "programming", color: "#DAE1C2", aliases: []),
    "TI Program": LanguageMeta(type: "programming", color: "#A0AA87", aliases: []),
    "TL-Verilog": LanguageMeta(type: "programming", color: "#C40023", aliases: []),
    "TLA": LanguageMeta(type: "programming", color: "#4b0079", aliases: []),
    "TMDL": LanguageMeta(type: "data", color: "#f0c913", aliases: ["Tabular Model Definition Language"]),
    "TOML": LanguageMeta(type: "data", color: "#9c4221", aliases: []),
    "TSPLIB data": LanguageMeta(type: "data", color: nil, aliases: ["travelling salesman problem", "traveling salesman problem"]),
    "TSQL": LanguageMeta(type: "programming", color: "#e38c00", aliases: []),
    "TSV": LanguageMeta(type: "data", color: "#237346", aliases: ["tab-seperated values"]),
    "TSX": LanguageMeta(type: "programming", color: "#3178c6", aliases: ["typescriptreact"]),
    "TXL": LanguageMeta(type: "programming", color: "#0178b8", aliases: []),
    "Tact": LanguageMeta(type: "programming", color: "#48b5ff", aliases: []),
    "Talon": LanguageMeta(type: "programming", color: "#333333", aliases: []),
    "Tcl": LanguageMeta(type: "programming", color: "#e4cc98", aliases: ["sdc", "xdc"]),
    "Tcsh": LanguageMeta(type: "programming", color: nil, aliases: []),
    "TeX": LanguageMeta(type: "markup", color: "#3D6117", aliases: ["latex"]),
    "Tea": LanguageMeta(type: "markup", color: nil, aliases: []),
    "Teal": LanguageMeta(type: "programming", color: "#00B1BC", aliases: []),
    "Terra": LanguageMeta(type: "programming", color: "#00004c", aliases: []),
    "Terraform Template": LanguageMeta(type: "markup", color: "#7b42bb", aliases: []),
    "Texinfo": LanguageMeta(type: "prose", color: nil, aliases: []),
    "Text": LanguageMeta(type: "prose", color: nil, aliases: ["fundamental", "plain text"]),
    "TextGrid": LanguageMeta(type: "data", color: "#c8506d", aliases: []),
    "TextMate Properties": LanguageMeta(type: "data", color: "#df66e4", aliases: ["tm-properties"]),
    "Textile": LanguageMeta(type: "prose", color: "#ffe7ac", aliases: []),
    "Thrift": LanguageMeta(type: "programming", color: "#D12127", aliases: []),
    "Toit": LanguageMeta(type: "programming", color: "#c2c9fb", aliases: []),
    "Tor Config": LanguageMeta(type: "data", color: "#59316b", aliases: ["torrc"]),
    "Tree-sitter Query": LanguageMeta(type: "programming", color: "#8ea64c", aliases: ["tsq"]),
    "Turing": LanguageMeta(type: "programming", color: "#cf142b", aliases: []),
    "Turtle": LanguageMeta(type: "data", color: nil, aliases: []),
    "Twig": LanguageMeta(type: "markup", color: "#c1d026", aliases: []),
    "Type Language": LanguageMeta(type: "data", color: nil, aliases: ["tl"]),
    "TypeScript": LanguageMeta(type: "programming", color: "#3178c6", aliases: ["ts"]),
    "TypeSpec": LanguageMeta(type: "programming", color: "#4A3665", aliases: ["tsp"]),
    "Typst": LanguageMeta(type: "programming", color: "#239dad", aliases: ["typ"]),
    "Unified Parallel C": LanguageMeta(type: "programming", color: "#4e3617", aliases: []),
    "Unity3D Asset": LanguageMeta(type: "data", color: "#222c37", aliases: []),
    "Unix Assembly": LanguageMeta(type: "programming", color: nil, aliases: ["gas", "gnu asm", "unix asm"]),
    "Uno": LanguageMeta(type: "programming", color: "#9933cc", aliases: []),
    "UnrealScript": LanguageMeta(type: "programming", color: "#a54c4d", aliases: []),
    "Untyped Plutus Core": LanguageMeta(type: "programming", color: "#36adbd", aliases: []),
    "UrWeb": LanguageMeta(type: "programming", color: "#ccccee", aliases: ["Ur/Web", "Ur"]),
    "V": LanguageMeta(type: "programming", color: "#4f87c4", aliases: ["vlang"]),
    "VBA": LanguageMeta(type: "programming", color: "#867db1", aliases: ["visual basic for applications"]),
    "VBScript": LanguageMeta(type: "programming", color: "#15dcdc", aliases: []),
    "VCL": LanguageMeta(type: "programming", color: "#148AA8", aliases: []),
    "VHDL": LanguageMeta(type: "programming", color: "#adb2cb", aliases: []),
    "Vala": LanguageMeta(type: "programming", color: "#a56de2", aliases: []),
    "Valve Data Format": LanguageMeta(type: "data", color: "#f26025", aliases: ["keyvalues", "vdf"]),
    "Velocity Template Language": LanguageMeta(type: "markup", color: "#507cff", aliases: ["vtl", "velocity"]),
    "Vento": LanguageMeta(type: "markup", color: "#ff0080", aliases: []),
    "Verilog": LanguageMeta(type: "programming", color: "#b2b7f8", aliases: []),
    "Vim Help File": LanguageMeta(type: "prose", color: "#199f4b", aliases: ["help", "vimhelp"]),
    "Vim Script": LanguageMeta(type: "programming", color: "#199f4b", aliases: ["vim", "viml", "nvim", "vimscript"]),
    "Vim Snippet": LanguageMeta(type: "markup", color: "#199f4b", aliases: ["SnipMate", "UltiSnip", "UltiSnips", "NeoSnippet"]),
    "Visual Basic .NET": LanguageMeta(type: "programming", color: "#945db7", aliases: ["visual basic", "vbnet", "vb .net", "vb.net"]),
    "Visual Basic 6.0": LanguageMeta(type: "programming", color: "#2c6353", aliases: ["vb6", "vb 6", "visual basic 6", "visual basic classic", "classic visual basic"]),
    "Volt": LanguageMeta(type: "programming", color: "#1F1F1F", aliases: []),
    "Vue": LanguageMeta(type: "markup", color: "#41b883", aliases: []),
    "Vyper": LanguageMeta(type: "programming", color: "#9F4CF2", aliases: []),
    "WDL": LanguageMeta(type: "programming", color: "#42f1f4", aliases: ["Workflow Description Language"]),
    "WGSL": LanguageMeta(type: "programming", color: "#1a5e9a", aliases: []),
    "Wavefront Material": LanguageMeta(type: "data", color: nil, aliases: []),
    "Wavefront Object": LanguageMeta(type: "data", color: nil, aliases: []),
    "Web Ontology Language": LanguageMeta(type: "data", color: "#5b70bd", aliases: []),
    "WebAssembly": LanguageMeta(type: "programming", color: "#04133b", aliases: ["wast", "wasm"]),
    "WebAssembly Interface Type": LanguageMeta(type: "data", color: "#6250e7", aliases: ["wit"]),
    "WebIDL": LanguageMeta(type: "programming", color: nil, aliases: []),
    "WebVTT": LanguageMeta(type: "data", color: nil, aliases: ["vtt"]),
    "Wget Config": LanguageMeta(type: "data", color: nil, aliases: ["wgetrc"]),
    "Whiley": LanguageMeta(type: "programming", color: "#d5c397", aliases: []),
    "Wikitext": LanguageMeta(type: "prose", color: "#fc5757", aliases: ["mediawiki", "wiki"]),
    "Win32 Message File": LanguageMeta(type: "data", color: nil, aliases: []),
    "Windows Registry Entries": LanguageMeta(type: "data", color: "#52d5ff", aliases: []),
    "Witcher Script": LanguageMeta(type: "programming", color: "#ff0000", aliases: []),
    "Wolfram Language": LanguageMeta(type: "programming", color: "#dd1100", aliases: ["mathematica", "mma", "wolfram", "wolfram lang", "wl"]),
    "Wollok": LanguageMeta(type: "programming", color: "#a23738", aliases: []),
    "World of Warcraft Addon Data": LanguageMeta(type: "data", color: "#f7e43f", aliases: []),
    "Wren": LanguageMeta(type: "programming", color: "#383838", aliases: ["wrenlang"]),
    "X BitMap": LanguageMeta(type: "data", color: nil, aliases: ["xbm"]),
    "X Font Directory Index": LanguageMeta(type: "data", color: nil, aliases: []),
    "X PixMap": LanguageMeta(type: "data", color: nil, aliases: ["xpm"]),
    "X10": LanguageMeta(type: "programming", color: "#4B6BEF", aliases: ["xten"]),
    "XC": LanguageMeta(type: "programming", color: "#99DA07", aliases: []),
    "XCompose": LanguageMeta(type: "data", color: nil, aliases: []),
    "XML": LanguageMeta(type: "data", color: "#0060ac", aliases: ["rss", "xsd", "wsdl"]),
    "XML Property List": LanguageMeta(type: "data", color: "#0060ac", aliases: []),
    "XPages": LanguageMeta(type: "data", color: nil, aliases: []),
    "XProc": LanguageMeta(type: "programming", color: nil, aliases: []),
    "XQuery": LanguageMeta(type: "programming", color: "#5232e7", aliases: []),
    "XS": LanguageMeta(type: "programming", color: nil, aliases: []),
    "XSLT": LanguageMeta(type: "programming", color: "#EB8CEB", aliases: ["xsl"]),
    "Xmake": LanguageMeta(type: "programming", color: "#22a079", aliases: []),
    "Xojo": LanguageMeta(type: "programming", color: "#81bd41", aliases: []),
    "Xonsh": LanguageMeta(type: "programming", color: "#285EEF", aliases: []),
    "Xtend": LanguageMeta(type: "programming", color: "#24255d", aliases: []),
    "YAML": LanguageMeta(type: "data", color: "#cb171e", aliases: ["yml"]),
    "YANG": LanguageMeta(type: "data", color: nil, aliases: []),
    "YARA": LanguageMeta(type: "programming", color: "#220000", aliases: []),
    "YASnippet": LanguageMeta(type: "markup", color: "#32AB90", aliases: ["snippet", "yas"]),
    "Yacc": LanguageMeta(type: "programming", color: "#4B6C4B", aliases: []),
    "Yul": LanguageMeta(type: "programming", color: "#794932", aliases: []),
    "ZAP": LanguageMeta(type: "programming", color: "#0d665e", aliases: []),
    "ZIL": LanguageMeta(type: "programming", color: "#dc75e5", aliases: []),
    "Zeek": LanguageMeta(type: "programming", color: nil, aliases: ["bro"]),
    "ZenScript": LanguageMeta(type: "programming", color: "#00BCD1", aliases: []),
    "Zephir": LanguageMeta(type: "programming", color: "#118f9e", aliases: []),
    "Zig": LanguageMeta(type: "programming", color: "#ec915c", aliases: []),
    "Zimpl": LanguageMeta(type: "programming", color: "#d67711", aliases: []),
    "Zmodel": LanguageMeta(type: "data", color: "#ff7100", aliases: []),
    "cURL Config": LanguageMeta(type: "data", color: nil, aliases: ["curlrc"]),
    "crontab": LanguageMeta(type: "data", color: "#ead7ac", aliases: ["cron", "cron table"]),
    "desktop": LanguageMeta(type: "data", color: nil, aliases: []),
    "dircolors": LanguageMeta(type: "data", color: nil, aliases: []),
    "eC": LanguageMeta(type: "programming", color: "#913960", aliases: []),
    "edn": LanguageMeta(type: "data", color: nil, aliases: []),
    "fish": LanguageMeta(type: "programming", color: "#4aae47", aliases: []),
    "hoon": LanguageMeta(type: "programming", color: "#00b171", aliases: []),
    "iCalendar": LanguageMeta(type: "data", color: "#ec564c", aliases: ["iCal"]),
    "jq": LanguageMeta(type: "programming", color: "#c7254e", aliases: []),
    "kvlang": LanguageMeta(type: "markup", color: "#1da6e0", aliases: []),
    "mIRC Script": LanguageMeta(type: "programming", color: "#3d57c3", aliases: []),
    "mcfunction": LanguageMeta(type: "programming", color: "#E22837", aliases: []),
    "mdsvex": LanguageMeta(type: "markup", color: "#5f9ea0", aliases: []),
    "mupad": LanguageMeta(type: "programming", color: "#244963", aliases: []),
    "nanorc": LanguageMeta(type: "data", color: "#2d004d", aliases: []),
    "nesC": LanguageMeta(type: "programming", color: "#94B0C7", aliases: []),
    "ooc": LanguageMeta(type: "programming", color: "#b0b77e", aliases: []),
    "q": LanguageMeta(type: "programming", color: "#0040cd", aliases: []),
    "reStructuredText": LanguageMeta(type: "prose", color: "#141414", aliases: ["rst"]),
    "robots.txt": LanguageMeta(type: "data", color: nil, aliases: ["robots", "robots txt"]),
    "sed": LanguageMeta(type: "programming", color: "#64b970", aliases: []),
    "templ": LanguageMeta(type: "markup", color: "#66D0DD", aliases: []),
    "vCard": LanguageMeta(type: "data", color: "#ee2647", aliases: ["virtual contact file", "electronic business card"]),
    "wisp": LanguageMeta(type: "programming", color: "#7582D1", aliases: []),
    "xBase": LanguageMeta(type: "programming", color: "#403a40", aliases: ["advpl", "clipper", "foxpro"]),
]

// MARK: - 语言图标解析器

/// 语言图标解析器
/// 解析 GitHub 语言名 → 本地 Devicon SVG 或 Badge fallback
enum LanguageIconResolver {

    /// 解析语言名对应的图标结果
    /// 优先级: 本地 Devicon SVG → ColorBadge fallback
    static func resolve(language: String) -> LanguageIconResult {
        // Step 1: 尝试本地 Devicon SVG
        if let assetName = deviconAssetName(for: language) {
            return LanguageIconResult(
                type: .localSVG(assetName: assetName),
                languageName: language
            )
        }

        // Step 2: Fallback - 使用 Linguist color 或默认灰色 + 首字母
        let meta = linguistLanguages[language]
        let color = meta?.color ?? "#808080"  // 默认灰色
        let label = String(language.prefix(1)).uppercased()

        return LanguageIconResult(
            type: .badge(colorHex: color, label: label),
            languageName: language
        )
    }

    /// 获取语言对应的颜色（用于 RepoRowView 的 LanguageColor 兼容）
    static func color(for language: String) -> Color {
        linguistLanguages[language]?.color
            .flatMap { Color(hex: $0) }
            ?? .gray
    }

    /// 检查是否有本地 SVG 图标
    static func hasLocalSVG(language: String) -> Bool {
        deviconAssetName(for: language) != nil
    }
}

// MARK: - SwiftUI 视图

/// 语言图标视图：显示语言 logo 或 fallback badge
/// 使用场景：SidebarView 的 Languages 列表行
struct LanguageIconView: View {
    let language: String
    let size: CGFloat

    init(language: String, size: CGFloat = 20) {
        self.language = language
        self.size = size
    }

    var body: some View {
        let result = LanguageIconResolver.resolve(language: language)

        switch result.type {
        case .localSVG(let assetName):
            Image(assetName)
                .resizable()
                .scaledToFill()
                .frame(width: size, height: size)
                .clipped()

        case .badge(let colorHex, _):
            // Fallback: 只显示彩色圆形，不显示字母
            let color = Color(hex: colorHex) ?? .gray
            Circle()
                .fill(color)
                .frame(width: size, height: size)
        }
    }
}
