// ⚠️ 自动生成的文件，请勿手动修改
// 运行: python3 scripts/generate_linguist_metadata.py 更新
//
// 数据来源: https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml
// 生成时间: 2026-05-31
// 语言数量: 807

import Foundation

/// GitHub Linguist 语言元数据
/// 来源: https://github.com/github/linguist
public struct LinguistLanguage: Codable, Equatable {
    public let type: String
    public let color: String?
    public let aliases: [String]

    public init(type: String, color: String?, aliases: [String] = []) {
        self.type = type
        self.color = color
        self.aliases = aliases
    }
}

/// GitHub Linguist 语言元数据表
/// key: 语言名, value: LinguistLanguage
public let linguistLanguages: [String: LinguistLanguage] = [
    "1C Enterprise": LinguistLanguage(type: "programming", color: "#814CCC", aliases: []),
    "2-Dimensional Array": LinguistLanguage(type: "data", color: "#38761D", aliases: []),
    "4D": LinguistLanguage(type: "programming", color: "#004289", aliases: []),
    "ABAP": LinguistLanguage(type: "programming", color: "#E8274B", aliases: []),
    "ABAP CDS": LinguistLanguage(type: "programming", color: "#555e25", aliases: []),
    "ABNF": LinguistLanguage(type: "data", color: nil, aliases: []),
    "AGS Script": LinguistLanguage(type: "programming", color: "#B9D9FF", aliases: ['ags']),
    "AIDL": LinguistLanguage(type: "programming", color: "#34EB6B", aliases: []),
    "AL": LinguistLanguage(type: "programming", color: "#3AA2B5", aliases: []),
    "ALGOL": LinguistLanguage(type: "programming", color: "#D1E0DB", aliases: []),
    "AMPL": LinguistLanguage(type: "programming", color: "#E6EFBB", aliases: []),
    "ANTLR": LinguistLanguage(type: "programming", color: "#9DC3FF", aliases: []),
    "API Blueprint": LinguistLanguage(type: "markup", color: "#2ACCA8", aliases: []),
    "APL": LinguistLanguage(type: "programming", color: "#5A8164", aliases: []),
    "ASL": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "ASN.1": LinguistLanguage(type: "data", color: nil, aliases: []),
    "ASP.NET": LinguistLanguage(type: "programming", color: "#9400ff", aliases: ['aspx', 'aspx-vb']),
    "ATS": LinguistLanguage(type: "programming", color: "#1ac620", aliases: ['ats2']),
    "ActionScript": LinguistLanguage(type: "programming", color: "#882B0F", aliases: ['actionscript 3', 'actionscript3', 'as3']),
    "Ada": LinguistLanguage(type: "programming", color: "#02f88c", aliases: ['ada95', 'ada2005']),
    "Adblock Filter List": LinguistLanguage(type: "data", color: "#800000", aliases: ['ad block filters', 'ad block', 'adb', 'adblock']),
    "Adobe Font Metrics": LinguistLanguage(type: "data", color: "#fa0f00", aliases: ['acfm', 'adobe composite font metrics', 'adobe multiple font metrics', 'amfm']),
    "Agda": LinguistLanguage(type: "programming", color: "#315665", aliases: []),
    "Aiken": LinguistLanguage(type: "programming", color: "#640ff8", aliases: []),
    "Alloy": LinguistLanguage(type: "programming", color: "#64C800", aliases: []),
    "Alpine Abuild": LinguistLanguage(type: "programming", color: "#0D597F", aliases: ['abuild', 'apkbuild']),
    "Altium Designer": LinguistLanguage(type: "data", color: "#A89663", aliases: ['altium']),
    "AngelScript": LinguistLanguage(type: "programming", color: "#C7D7DC", aliases: []),
    "Answer Set Programming": LinguistLanguage(type: "programming", color: "#A9CC29", aliases: []),
    "Ant Build System": LinguistLanguage(type: "data", color: "#A9157E", aliases: []),
    "Antlers": LinguistLanguage(type: "markup", color: "#ff269e", aliases: []),
    "ApacheConf": LinguistLanguage(type: "data", color: "#d12127", aliases: ['aconf', 'apache']),
    "Apex": LinguistLanguage(type: "programming", color: "#1797c0", aliases: []),
    "Apollo Guidance Computer": LinguistLanguage(type: "programming", color: "#0B3D91", aliases: []),
    "AppleScript": LinguistLanguage(type: "programming", color: "#101F1F", aliases: ['apples', 'osascript']),
    "Arc": LinguistLanguage(type: "programming", color: "#aa2afe", aliases: []),
    "AsciiDoc": LinguistLanguage(type: "prose", color: "#73a0c5", aliases: []),
    "AspectJ": LinguistLanguage(type: "programming", color: "#a957b0", aliases: []),
    "Assembly": LinguistLanguage(type: "programming", color: "#6E4C13", aliases: ['asm', 'nasm']),
    "Astro": LinguistLanguage(type: "markup", color: "#ff5a03", aliases: []),
    "Asymptote": LinguistLanguage(type: "programming", color: "#ff0000", aliases: []),
    "Augeas": LinguistLanguage(type: "programming", color: "#9CC134", aliases: []),
    "AutoHotkey": LinguistLanguage(type: "programming", color: "#6594b9", aliases: ['ahk']),
    "AutoIt": LinguistLanguage(type: "programming", color: "#1C3552", aliases: ['au3', 'AutoIt3', 'AutoItScript']),
    "Avro IDL": LinguistLanguage(type: "data", color: "#0040FF", aliases: []),
    "Awk": LinguistLanguage(type: "programming", color: "#c30e9b", aliases: []),
    "B (Formal Method)": LinguistLanguage(type: "programming", color: "#8aa8c5", aliases: []),
    "B4X": LinguistLanguage(type: "programming", color: "#00e4ff", aliases: ['basic for android']),
    "BASIC": LinguistLanguage(type: "programming", color: "#ff0000", aliases: []),
    "BQN": LinguistLanguage(type: "programming", color: "#2b7067", aliases: []),
    "Ballerina": LinguistLanguage(type: "programming", color: "#FF5000", aliases: []),
    "Batchfile": LinguistLanguage(type: "programming", color: "#C1F12E", aliases: ['bat', 'batch', 'dosbatch', 'winbatch']),
    "Beef": LinguistLanguage(type: "programming", color: "#a52f4e", aliases: []),
    "Befunge": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Berry": LinguistLanguage(type: "programming", color: "#15A13C", aliases: ['be']),
    "BibTeX": LinguistLanguage(type: "markup", color: "#778899", aliases: []),
    "BibTeX Style": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Bicep": LinguistLanguage(type: "programming", color: "#519aba", aliases: []),
    "Bikeshed": LinguistLanguage(type: "markup", color: "#5562ac", aliases: []),
    "Bison": LinguistLanguage(type: "programming", color: "#6A463F", aliases: []),
    "BitBake": LinguistLanguage(type: "programming", color: "#00bce4", aliases: []),
    "Blade": LinguistLanguage(type: "markup", color: "#f7523f", aliases: []),
    "BlitzBasic": LinguistLanguage(type: "programming", color: "#00FFAE", aliases: ['b3d', 'blitz3d', 'blitzplus', 'bplus']),
    "BlitzMax": LinguistLanguage(type: "programming", color: "#cd6400", aliases: ['bmax']),
    "Bluespec": LinguistLanguage(type: "programming", color: "#12223c", aliases: ['bluespec bsv', 'bsv']),
    "Bluespec BH": LinguistLanguage(type: "programming", color: "#12223c", aliases: ['bh', 'bluespec classic']),
    "Boo": LinguistLanguage(type: "programming", color: "#d4bec1", aliases: []),
    "Boogie": LinguistLanguage(type: "programming", color: "#c80fa0", aliases: []),
    "Brainfuck": LinguistLanguage(type: "programming", color: "#2F2530", aliases: []),
    "BrighterScript": LinguistLanguage(type: "programming", color: "#66AABB", aliases: []),
    "Brightscript": LinguistLanguage(type: "programming", color: "#662D91", aliases: []),
    "Browserslist": LinguistLanguage(type: "data", color: "#ffd539", aliases: []),
    "Bru": LinguistLanguage(type: "markup", color: "#F4AA41", aliases: []),
    "BuildStream": LinguistLanguage(type: "data", color: "#006bff", aliases: []),
    "C": LinguistLanguage(type: "programming", color: "#555555", aliases: []),
    "C#": LinguistLanguage(type: "programming", color: "#178600", aliases: ['csharp', 'cake', 'cakescript']),
    "C++": LinguistLanguage(type: "programming", color: "#f34b7d", aliases: ['cpp']),
    "C-ObjDump": LinguistLanguage(type: "data", color: nil, aliases: []),
    "C2hs Haskell": LinguistLanguage(type: "programming", color: nil, aliases: ['c2hs']),
    "C3": LinguistLanguage(type: "programming", color: "#2563eb", aliases: []),
    "CAP CDS": LinguistLanguage(type: "programming", color: "#0092d1", aliases: ['cds']),
    "CIL": LinguistLanguage(type: "data", color: nil, aliases: []),
    "CLIPS": LinguistLanguage(type: "programming", color: "#00A300", aliases: []),
    "CMake": LinguistLanguage(type: "programming", color: "#DA3434", aliases: []),
    "COBOL": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "CODEOWNERS": LinguistLanguage(type: "data", color: nil, aliases: []),
    "COLLADA": LinguistLanguage(type: "data", color: "#F1A42B", aliases: []),
    "CQL": LinguistLanguage(type: "programming", color: "#006091", aliases: []),
    "CSON": LinguistLanguage(type: "data", color: "#244776", aliases: []),
    "CSS": LinguistLanguage(type: "markup", color: "#663399", aliases: []),
    "CSV": LinguistLanguage(type: "data", color: "#237346", aliases: []),
    "CUE": LinguistLanguage(type: "programming", color: "#5886E1", aliases: []),
    "CWeb": LinguistLanguage(type: "programming", color: "#00007a", aliases: []),
    "Cabal Config": LinguistLanguage(type: "data", color: "#483465", aliases: ['Cabal']),
    "Caddyfile": LinguistLanguage(type: "data", color: "#22b638", aliases: ['Caddy']),
    "Cadence": LinguistLanguage(type: "programming", color: "#00ef8b", aliases: []),
    "Cairo": LinguistLanguage(type: "programming", color: "#ff4a48", aliases: []),
    "Cairo Zero": LinguistLanguage(type: "programming", color: "#ff4a48", aliases: []),
    "CameLIGO": LinguistLanguage(type: "programming", color: "#3be133", aliases: []),
    "Cangjie": LinguistLanguage(type: "programming", color: "#00868B", aliases: []),
    "Cap'n Proto": LinguistLanguage(type: "programming", color: "#c42727", aliases: []),
    "Carbon": LinguistLanguage(type: "programming", color: "#222222", aliases: []),
    "CartoCSS": LinguistLanguage(type: "programming", color: nil, aliases: ['Carto']),
    "Ceylon": LinguistLanguage(type: "programming", color: "#dfa535", aliases: []),
    "Chapel": LinguistLanguage(type: "programming", color: "#8dc63f", aliases: ['chpl']),
    "Charity": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Checksums": LinguistLanguage(type: "data", color: nil, aliases: ['checksum', 'hash', 'hashes', 'sum', 'sums']),
    "ChucK": LinguistLanguage(type: "programming", color: "#3f8000", aliases: []),
    "Circom": LinguistLanguage(type: "programming", color: "#707575", aliases: []),
    "Cirru": LinguistLanguage(type: "programming", color: "#ccccff", aliases: []),
    "Clarion": LinguistLanguage(type: "programming", color: "#db901e", aliases: []),
    "Clarity": LinguistLanguage(type: "programming", color: "#5546ff", aliases: []),
    "Classic ASP": LinguistLanguage(type: "programming", color: "#6a40fd", aliases: ['asp']),
    "Clean": LinguistLanguage(type: "programming", color: "#3F85AF", aliases: []),
    "Click": LinguistLanguage(type: "programming", color: "#E4E6F3", aliases: []),
    "Clojure": LinguistLanguage(type: "programming", color: "#db5855", aliases: []),
    "Closure Templates": LinguistLanguage(type: "markup", color: "#0d948f", aliases: ['soy']),
    "Cloud Firestore Security Rules": LinguistLanguage(type: "data", color: "#FFA000", aliases: []),
    "Clue": LinguistLanguage(type: "programming", color: "#0009b5", aliases: []),
    "CoNLL-U": LinguistLanguage(type: "data", color: nil, aliases: ['CoNLL', 'CoNLL-X']),
    "CodeQL": LinguistLanguage(type: "programming", color: "#140f46", aliases: ['ql']),
    "CoffeeScript": LinguistLanguage(type: "programming", color: "#244776", aliases: ['coffee', 'coffee-script']),
    "ColdFusion": LinguistLanguage(type: "programming", color: "#ed2cd6", aliases: ['cfm', 'cfml', 'coldfusion html']),
    "ColdFusion CFC": LinguistLanguage(type: "programming", color: "#ed2cd6", aliases: ['cfc']),
    "Common Lisp": LinguistLanguage(type: "programming", color: "#3fb68b", aliases: ['lisp']),
    "Common Workflow Language": LinguistLanguage(type: "programming", color: "#B5314C", aliases: ['cwl']),
    "Component Pascal": LinguistLanguage(type: "programming", color: "#B0CE4E", aliases: []),
    "Cooklang": LinguistLanguage(type: "markup", color: "#E15A29", aliases: []),
    "Cool": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Cpp-ObjDump": LinguistLanguage(type: "data", color: nil, aliases: ['c++-objdump']),
    "Creole": LinguistLanguage(type: "prose", color: nil, aliases: []),
    "Crystal": LinguistLanguage(type: "programming", color: "#000100", aliases: []),
    "Csound": LinguistLanguage(type: "programming", color: "#1a1a1a", aliases: ['csound-orc']),
    "Csound Document": LinguistLanguage(type: "programming", color: "#1a1a1a", aliases: ['csound-csd']),
    "Csound Score": LinguistLanguage(type: "programming", color: "#1a1a1a", aliases: ['csound-sco']),
    "Cuda": LinguistLanguage(type: "programming", color: "#3A4E3A", aliases: []),
    "Cue Sheet": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Curry": LinguistLanguage(type: "programming", color: "#531242", aliases: []),
    "Cycript": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Cylc": LinguistLanguage(type: "data", color: "#00b3fd", aliases: []),
    "Cypher": LinguistLanguage(type: "programming", color: "#34c0eb", aliases: []),
    "Cython": LinguistLanguage(type: "programming", color: "#fedf5b", aliases: ['pyrex']),
    "D": LinguistLanguage(type: "programming", color: "#ba595e", aliases: ['Dlang']),
    "D-ObjDump": LinguistLanguage(type: "data", color: nil, aliases: []),
    "D2": LinguistLanguage(type: "markup", color: "#526ee8", aliases: ['d2lang']),
    "DIGITAL Command Language": LinguistLanguage(type: "programming", color: nil, aliases: ['dcl']),
    "DM": LinguistLanguage(type: "programming", color: "#447265", aliases: ['byond']),
    "DNS Zone": LinguistLanguage(type: "data", color: nil, aliases: []),
    "DTrace": LinguistLanguage(type: "programming", color: nil, aliases: ['dtrace-script']),
    "Dafny": LinguistLanguage(type: "programming", color: "#FFEC25", aliases: []),
    "Darcs Patch": LinguistLanguage(type: "data", color: "#8eff23", aliases: ['dpatch']),
    "Dart": LinguistLanguage(type: "programming", color: "#00B4AB", aliases: []),
    "Daslang": LinguistLanguage(type: "programming", color: "#d3d3d3", aliases: []),
    "DataWeave": LinguistLanguage(type: "programming", color: "#003a52", aliases: []),
    "Debian Package Control File": LinguistLanguage(type: "data", color: "#D70751", aliases: []),
    "DenizenScript": LinguistLanguage(type: "programming", color: "#FBEE96", aliases: []),
    "Dhall": LinguistLanguage(type: "programming", color: "#dfafff", aliases: []),
    "Diff": LinguistLanguage(type: "data", color: nil, aliases: ['udiff']),
    "DirectX 3D File": LinguistLanguage(type: "data", color: "#aace60", aliases: []),
    "Dockerfile": LinguistLanguage(type: "programming", color: "#384d54", aliases: ['Containerfile']),
    "Dogescript": LinguistLanguage(type: "programming", color: "#cca760", aliases: []),
    "Dotenv": LinguistLanguage(type: "data", color: "#e5d559", aliases: []),
    "Dune": LinguistLanguage(type: "programming", color: "#89421e", aliases: []),
    "Dylan": LinguistLanguage(type: "programming", color: "#6c616e", aliases: []),
    "E": LinguistLanguage(type: "programming", color: "#ccce35", aliases: []),
    "E-mail": LinguistLanguage(type: "data", color: nil, aliases: ['email', 'eml', 'mail', 'mbox']),
    "EBNF": LinguistLanguage(type: "data", color: nil, aliases: []),
    "ECL": LinguistLanguage(type: "programming", color: "#8a1267", aliases: []),
    "ECLiPSe": LinguistLanguage(type: "programming", color: "#001d9d", aliases: []),
    "EJS": LinguistLanguage(type: "markup", color: "#a91e50", aliases: []),
    "EQ": LinguistLanguage(type: "programming", color: "#a78649", aliases: []),
    "Eagle": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Earthly": LinguistLanguage(type: "programming", color: "#2af0ff", aliases: ['Earthfile']),
    "Easybuild": LinguistLanguage(type: "data", color: "#069406", aliases: []),
    "Ecere Projects": LinguistLanguage(type: "data", color: "#913960", aliases: []),
    "Ecmarkup": LinguistLanguage(type: "markup", color: "#eb8131", aliases: ['ecmarkdown']),
    "Edge": LinguistLanguage(type: "markup", color: "#0dffe0", aliases: []),
    "EdgeQL": LinguistLanguage(type: "programming", color: "#31A7FF", aliases: ['esdl']),
    "EditorConfig": LinguistLanguage(type: "data", color: "#fff1f2", aliases: ['editor-config']),
    "Edje Data Collection": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Eiffel": LinguistLanguage(type: "programming", color: "#4d6977", aliases: []),
    "Elixir": LinguistLanguage(type: "programming", color: "#6e4a7e", aliases: []),
    "Elm": LinguistLanguage(type: "programming", color: "#60B5CC", aliases: []),
    "Elvish": LinguistLanguage(type: "programming", color: "#55BB55", aliases: []),
    "Elvish Transcript": LinguistLanguage(type: "programming", color: "#55BB55", aliases: []),
    "Emacs Lisp": LinguistLanguage(type: "programming", color: "#c065db", aliases: ['cask', 'eask', 'elisp', 'emacs']),
    "EmberScript": LinguistLanguage(type: "programming", color: "#FFF4F3", aliases: []),
    "Erlang": LinguistLanguage(type: "programming", color: "#B83998", aliases: []),
    "Euphoria": LinguistLanguage(type: "programming", color: "#FF790B", aliases: []),
    "F#": LinguistLanguage(type: "programming", color: "#b845fc", aliases: ['fsharp']),
    "F*": LinguistLanguage(type: "programming", color: "#572e30", aliases: ['fstar']),
    "FIGlet Font": LinguistLanguage(type: "data", color: "#FFDDBB", aliases: ['FIGfont']),
    "FIRRTL": LinguistLanguage(type: "programming", color: "#2f632f", aliases: []),
    "FLUX": LinguistLanguage(type: "programming", color: "#88ccff", aliases: []),
    "Factor": LinguistLanguage(type: "programming", color: "#636746", aliases: []),
    "Fancy": LinguistLanguage(type: "programming", color: "#7b9db4", aliases: []),
    "Fantom": LinguistLanguage(type: "programming", color: "#14253c", aliases: []),
    "Faust": LinguistLanguage(type: "programming", color: "#c37240", aliases: []),
    "Fennel": LinguistLanguage(type: "programming", color: "#fff3d7", aliases: []),
    "Filebench WML": LinguistLanguage(type: "programming", color: "#F6B900", aliases: []),
    "Filterscript": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "FlatBuffers": LinguistLanguage(type: "data", color: "#ed284a", aliases: []),
    "Flix": LinguistLanguage(type: "programming", color: "#d44a45", aliases: []),
    "Fluent": LinguistLanguage(type: "programming", color: "#ffcc33", aliases: []),
    "Formatted": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Forth": LinguistLanguage(type: "programming", color: "#341708", aliases: []),
    "Fortran": LinguistLanguage(type: "programming", color: "#4d41b1", aliases: []),
    "Fortran Free Form": LinguistLanguage(type: "programming", color: "#4d41b1", aliases: []),
    "FreeBASIC": LinguistLanguage(type: "programming", color: "#141AC9", aliases: ['fb']),
    "FreeMarker": LinguistLanguage(type: "programming", color: "#0050b2", aliases: ['ftl']),
    "Frege": LinguistLanguage(type: "programming", color: "#00cafe", aliases: []),
    "Futhark": LinguistLanguage(type: "programming", color: "#5f021f", aliases: []),
    "G-code": LinguistLanguage(type: "programming", color: "#D08CF2", aliases: []),
    "GAML": LinguistLanguage(type: "programming", color: "#FFC766", aliases: []),
    "GAMS": LinguistLanguage(type: "programming", color: "#f49a22", aliases: []),
    "GAP": LinguistLanguage(type: "programming", color: "#0000cc", aliases: []),
    "GCC Machine Description": LinguistLanguage(type: "programming", color: "#FFCFAB", aliases: []),
    "GDB": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "GDScript": LinguistLanguage(type: "programming", color: "#355570", aliases: []),
    "GDShader": LinguistLanguage(type: "programming", color: "#478CBF", aliases: []),
    "GEDCOM": LinguistLanguage(type: "data", color: "#003058", aliases: []),
    "GLSL": LinguistLanguage(type: "programming", color: "#5686a5", aliases: []),
    "GN": LinguistLanguage(type: "data", color: nil, aliases: []),
    "GSC": LinguistLanguage(type: "programming", color: "#FF6800", aliases: []),
    "Game Maker Language": LinguistLanguage(type: "programming", color: "#71b417", aliases: []),
    "Gemfile.lock": LinguistLanguage(type: "data", color: "#701516", aliases: []),
    "Gemini": LinguistLanguage(type: "prose", color: "#ff6900", aliases: ['gemtext']),
    "Genero 4gl": LinguistLanguage(type: "programming", color: "#63408e", aliases: []),
    "Genero per": LinguistLanguage(type: "markup", color: "#d8df39", aliases: []),
    "Genie": LinguistLanguage(type: "programming", color: "#fb855d", aliases: []),
    "Genshi": LinguistLanguage(type: "programming", color: "#951531", aliases: ['xml+genshi', 'xml+kid']),
    "Gentoo Ebuild": LinguistLanguage(type: "programming", color: "#9400ff", aliases: []),
    "Gentoo Eclass": LinguistLanguage(type: "programming", color: "#9400ff", aliases: []),
    "Gerber Image": LinguistLanguage(type: "data", color: "#d20b00", aliases: ['rs-274x']),
    "Gettext Catalog": LinguistLanguage(type: "prose", color: nil, aliases: ['pot']),
    "Gherkin": LinguistLanguage(type: "programming", color: "#5B2063", aliases: ['cucumber']),
    "Git Attributes": LinguistLanguage(type: "data", color: "#F44D27", aliases: ['gitattributes']),
    "Git Commit": LinguistLanguage(type: "data", color: "#F44D27", aliases: ['commit']),
    "Git Config": LinguistLanguage(type: "data", color: "#F44D27", aliases: ['gitconfig', 'gitmodules']),
    "Git Revision List": LinguistLanguage(type: "data", color: "#F44D27", aliases: ['Git Blame Ignore Revs']),
    "Gleam": LinguistLanguage(type: "programming", color: "#ffaff3", aliases: []),
    "Glimmer JS": LinguistLanguage(type: "programming", color: "#F5835F", aliases: ['gjs']),
    "Glimmer TS": LinguistLanguage(type: "programming", color: "#3178c6", aliases: ['gts']),
    "Glyph": LinguistLanguage(type: "programming", color: "#c1ac7f", aliases: []),
    "Glyph Bitmap Distribution Format": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Gnuplot": LinguistLanguage(type: "programming", color: "#f0a9f0", aliases: []),
    "Go": LinguistLanguage(type: "programming", color: "#00ADD8", aliases: ['golang']),
    "Go Checksums": LinguistLanguage(type: "data", color: "#00ADD8", aliases: ['go.sum', 'go sum', 'go.work.sum', 'go work sum']),
    "Go Module": LinguistLanguage(type: "data", color: "#00ADD8", aliases: ['go.mod', 'go mod']),
    "Go Template": LinguistLanguage(type: "markup", color: "#00ADD8", aliases: ['gotmpl']),
    "Go Workspace": LinguistLanguage(type: "data", color: "#00ADD8", aliases: ['go.work', 'go work']),
    "Godot Resource": LinguistLanguage(type: "data", color: "#355570", aliases: []),
    "Golo": LinguistLanguage(type: "programming", color: "#88562A", aliases: []),
    "Gosu": LinguistLanguage(type: "programming", color: "#82937f", aliases: []),
    "Grace": LinguistLanguage(type: "programming", color: "#615f8b", aliases: []),
    "Gradle": LinguistLanguage(type: "data", color: "#02303a", aliases: []),
    "Gradle Kotlin DSL": LinguistLanguage(type: "data", color: "#02303a", aliases: []),
    "Grammatical Framework": LinguistLanguage(type: "programming", color: "#ff0000", aliases: ['gf']),
    "Graph Modeling Language": LinguistLanguage(type: "data", color: nil, aliases: []),
    "GraphQL": LinguistLanguage(type: "data", color: "#e10098", aliases: []),
    "Graphviz (DOT)": LinguistLanguage(type: "data", color: "#2596be", aliases: []),
    "Groovy": LinguistLanguage(type: "programming", color: "#4298b8", aliases: []),
    "Groovy Server Pages": LinguistLanguage(type: "programming", color: "#4298b8", aliases: ['gsp', 'java server page']),
    "HAProxy": LinguistLanguage(type: "data", color: "#106da9", aliases: []),
    "HCL": LinguistLanguage(type: "programming", color: "#844FBA", aliases: ['HashiCorp Configuration Language', 'opentofu', 'terraform']),
    "HIP": LinguistLanguage(type: "programming", color: "#4F3A4F", aliases: []),
    "HLSL": LinguistLanguage(type: "programming", color: "#aace60", aliases: []),
    "HOCON": LinguistLanguage(type: "data", color: "#9ff8ee", aliases: []),
    "HTML": LinguistLanguage(type: "markup", color: "#e34c26", aliases: ['xhtml']),
    "HTML+ECR": LinguistLanguage(type: "markup", color: "#2e1052", aliases: ['ecr']),
    "HTML+EEX": LinguistLanguage(type: "markup", color: "#6e4a7e", aliases: ['eex', 'heex', 'leex']),
    "HTML+ERB": LinguistLanguage(type: "markup", color: "#701516", aliases: ['erb', 'rhtml', 'html+ruby']),
    "HTML+PHP": LinguistLanguage(type: "markup", color: "#4f5d95", aliases: []),
    "HTML+Razor": LinguistLanguage(type: "markup", color: "#512be4", aliases: ['razor']),
    "HTTP": LinguistLanguage(type: "data", color: "#005C9C", aliases: []),
    "HXML": LinguistLanguage(type: "data", color: "#f68712", aliases: []),
    "Hack": LinguistLanguage(type: "programming", color: "#878787", aliases: []),
    "Haml": LinguistLanguage(type: "markup", color: "#ece2a9", aliases: []),
    "Handlebars": LinguistLanguage(type: "markup", color: "#f7931e", aliases: ['hbs', 'htmlbars']),
    "Harbour": LinguistLanguage(type: "programming", color: "#0e60e3", aliases: []),
    "Hare": LinguistLanguage(type: "programming", color: "#9d7424", aliases: []),
    "Haskell": LinguistLanguage(type: "programming", color: "#5e5086", aliases: []),
    "Haxe": LinguistLanguage(type: "programming", color: "#df7900", aliases: []),
    "HiveQL": LinguistLanguage(type: "programming", color: "#dce200", aliases: []),
    "HolyC": LinguistLanguage(type: "programming", color: "#ffefaf", aliases: []),
    "Hosts File": LinguistLanguage(type: "data", color: "#308888", aliases: ['hosts']),
    "Hurl": LinguistLanguage(type: "programming", color: "#FF0288", aliases: []),
    "Hy": LinguistLanguage(type: "programming", color: "#7790B2", aliases: ['hylang']),
    "HyPhy": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "IDL": LinguistLanguage(type: "programming", color: "#a3522f", aliases: []),
    "IGOR Pro": LinguistLanguage(type: "programming", color: "#0000cc", aliases: ['igor', 'igorpro']),
    "IL Assembly": LinguistLanguage(type: "programming", color: "#512BD4", aliases: ['ilasm', 'msil']),
    "INI": LinguistLanguage(type: "data", color: "#d1dbe0", aliases: ['dosini']),
    "IRC log": LinguistLanguage(type: "data", color: nil, aliases: ['irc', 'irc logs']),
    "ISPC": LinguistLanguage(type: "programming", color: "#2D68B1", aliases: []),
    "Idris": LinguistLanguage(type: "programming", color: "#b30000", aliases: []),
    "Ignore List": LinguistLanguage(type: "data", color: "#000000", aliases: ['ignore', 'gitignore', 'git-ignore']),
    "ImageJ Macro": LinguistLanguage(type: "programming", color: "#99AAFF", aliases: ['ijm']),
    "Imba": LinguistLanguage(type: "programming", color: "#16cec6", aliases: []),
    "Inform 7": LinguistLanguage(type: "programming", color: nil, aliases: ['i7', 'inform7']),
    "Ink": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Inno Setup": LinguistLanguage(type: "programming", color: "#264b99", aliases: []),
    "Io": LinguistLanguage(type: "programming", color: "#a9188d", aliases: []),
    "Ioke": LinguistLanguage(type: "programming", color: "#078193", aliases: []),
    "Isabelle": LinguistLanguage(type: "programming", color: "#FEFE00", aliases: []),
    "Isabelle ROOT": LinguistLanguage(type: "programming", color: "#FEFE00", aliases: []),
    "J": LinguistLanguage(type: "programming", color: "#9EEDFF", aliases: []),
    "JAR Manifest": LinguistLanguage(type: "data", color: "#b07219", aliases: []),
    "JCL": LinguistLanguage(type: "programming", color: "#d90e09", aliases: []),
    "JFlex": LinguistLanguage(type: "programming", color: "#DBCA00", aliases: []),
    "JSON": LinguistLanguage(type: "data", color: "#292929", aliases: ['geojson', 'jsonl', 'sarif', 'topojson']),
    "JSON with Comments": LinguistLanguage(type: "data", color: "#292929", aliases: ['jsonc']),
    "JSON5": LinguistLanguage(type: "data", color: "#267CB9", aliases: []),
    "JSONLD": LinguistLanguage(type: "data", color: "#0c479c", aliases: []),
    "JSONiq": LinguistLanguage(type: "programming", color: "#40d47e", aliases: []),
    "Jac": LinguistLanguage(type: "programming", color: "#FC792D", aliases: []),
    "Jai": LinguistLanguage(type: "programming", color: "#ab8b4b", aliases: []),
    "Janet": LinguistLanguage(type: "programming", color: "#0886a5", aliases: []),
    "Jasmin": LinguistLanguage(type: "programming", color: "#d03600", aliases: []),
    "Java": LinguistLanguage(type: "programming", color: "#b07219", aliases: []),
    "Java Properties": LinguistLanguage(type: "data", color: "#2A6277", aliases: []),
    "Java Server Pages": LinguistLanguage(type: "programming", color: "#2A6277", aliases: ['jsp']),
    "Java Template Engine": LinguistLanguage(type: "programming", color: "#2A6277", aliases: ['jte']),
    "JavaScript": LinguistLanguage(type: "programming", color: "#f1e05a", aliases: ['js', 'node']),
    "JavaScript+ERB": LinguistLanguage(type: "programming", color: "#f1e05a", aliases: []),
    "Jest Snapshot": LinguistLanguage(type: "data", color: "#15c213", aliases: []),
    "JetBrains MPS": LinguistLanguage(type: "programming", color: "#21D789", aliases: ['mps']),
    "Jinja": LinguistLanguage(type: "markup", color: "#a52a22", aliases: ['django', 'html+django', 'html+jinja', 'htmldjango']),
    "Jison": LinguistLanguage(type: "programming", color: "#56b3cb", aliases: []),
    "Jison Lex": LinguistLanguage(type: "programming", color: "#56b3cb", aliases: []),
    "Jolie": LinguistLanguage(type: "programming", color: "#843179", aliases: []),
    "Jsonnet": LinguistLanguage(type: "programming", color: "#0064bd", aliases: []),
    "Julia": LinguistLanguage(type: "programming", color: "#a270ba", aliases: []),
    "Julia REPL": LinguistLanguage(type: "programming", color: "#a270ba", aliases: []),
    "Jupyter Notebook": LinguistLanguage(type: "markup", color: "#DA5B0B", aliases: ['IPython Notebook']),
    "Just": LinguistLanguage(type: "programming", color: "#384d54", aliases: ['Justfile']),
    "KCL": LinguistLanguage(type: "programming", color: "#7ABABF", aliases: []),
    "KDL": LinguistLanguage(type: "data", color: "#ffb3b3", aliases: []),
    "KFramework": LinguistLanguage(type: "programming", color: "#4195c5", aliases: []),
    "KRL": LinguistLanguage(type: "programming", color: "#28430A", aliases: []),
    "Kaitai Struct": LinguistLanguage(type: "programming", color: "#773b37", aliases: ['ksy']),
    "KakouneScript": LinguistLanguage(type: "programming", color: "#6f8042", aliases: ['kak', 'kakscript']),
    "KerboScript": LinguistLanguage(type: "programming", color: "#41adf0", aliases: []),
    "KiCad Layout": LinguistLanguage(type: "data", color: "#2f4aab", aliases: ['pcbnew']),
    "KiCad Legacy Layout": LinguistLanguage(type: "data", color: "#2f4aab", aliases: []),
    "KiCad Schematic": LinguistLanguage(type: "data", color: "#2f4aab", aliases: ['eeschema schematic']),
    "Kickstart": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Kit": LinguistLanguage(type: "markup", color: nil, aliases: []),
    "KoLmafia ASH": LinguistLanguage(type: "programming", color: "#B9D9B9", aliases: []),
    "Koka": LinguistLanguage(type: "programming", color: "#215166", aliases: []),
    "Kotlin": LinguistLanguage(type: "programming", color: "#A97BFF", aliases: []),
    "Kusto": LinguistLanguage(type: "data", color: nil, aliases: []),
    "LFE": LinguistLanguage(type: "programming", color: "#4C3023", aliases: []),
    "LLVM": LinguistLanguage(type: "programming", color: "#185619", aliases: []),
    "LOLCODE": LinguistLanguage(type: "programming", color: "#cc9900", aliases: []),
    "LSL": LinguistLanguage(type: "programming", color: "#3d9970", aliases: []),
    "LTspice Symbol": LinguistLanguage(type: "data", color: nil, aliases: []),
    "LabVIEW": LinguistLanguage(type: "programming", color: "#fede06", aliases: []),
    "Lambdapi": LinguistLanguage(type: "programming", color: "#8027a3", aliases: []),
    "Langium": LinguistLanguage(type: "programming", color: "#2c8c87", aliases: []),
    "Lark": LinguistLanguage(type: "data", color: "#2980B9", aliases: []),
    "Lasso": LinguistLanguage(type: "programming", color: "#999999", aliases: ['lassoscript']),
    "Latte": LinguistLanguage(type: "markup", color: "#f2a542", aliases: []),
    "Lean": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Lean 4": LinguistLanguage(type: "programming", color: nil, aliases: ['lean4']),
    "Leo": LinguistLanguage(type: "programming", color: "#C4FFC2", aliases: []),
    "Less": LinguistLanguage(type: "markup", color: "#1d365d", aliases: ['less-css']),
    "Lex": LinguistLanguage(type: "programming", color: "#DBCA00", aliases: ['flex']),
    "LigoLANG": LinguistLanguage(type: "programming", color: "#0e74ff", aliases: []),
    "LilyPond": LinguistLanguage(type: "programming", color: "#9ccc7c", aliases: []),
    "Limbo": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Linear Programming": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Linker Script": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Linux Kernel Module": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Liquid": LinguistLanguage(type: "markup", color: "#67b8de", aliases: []),
    "Liquidsoap": LinguistLanguage(type: "programming", color: "#990066", aliases: []),
    "Literate Agda": LinguistLanguage(type: "programming", color: "#315665", aliases: []),
    "Literate CoffeeScript": LinguistLanguage(type: "programming", color: "#244776", aliases: ['litcoffee']),
    "Literate Haskell": LinguistLanguage(type: "programming", color: "#5e5086", aliases: ['lhaskell', 'lhs']),
    "LiveCode Script": LinguistLanguage(type: "programming", color: "#0c5ba5", aliases: []),
    "LiveScript": LinguistLanguage(type: "programming", color: "#499886", aliases: ['live-script', 'ls']),
    "Logos": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Logtalk": LinguistLanguage(type: "programming", color: "#295b9a", aliases: []),
    "LookML": LinguistLanguage(type: "programming", color: "#652B81", aliases: []),
    "LoomScript": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Lua": LinguistLanguage(type: "programming", color: "#000080", aliases: []),
    "Luau": LinguistLanguage(type: "programming", color: "#00A2FF", aliases: []),
    "M": LinguistLanguage(type: "programming", color: nil, aliases: ['mumps']),
    "M3U": LinguistLanguage(type: "data", color: "#179C7D", aliases: ['hls playlist', 'm3u playlist']),
    "M4": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "M4Sugar": LinguistLanguage(type: "programming", color: nil, aliases: ['autoconf']),
    "MATLAB": LinguistLanguage(type: "programming", color: "#e16737", aliases: ['octave']),
    "MAXScript": LinguistLanguage(type: "programming", color: "#00a6a6", aliases: []),
    "MDX": LinguistLanguage(type: "markup", color: "#fcb32c", aliases: []),
    "MLIR": LinguistLanguage(type: "programming", color: "#5EC8DB", aliases: []),
    "MQL4": LinguistLanguage(type: "programming", color: "#62A8D6", aliases: []),
    "MQL5": LinguistLanguage(type: "programming", color: "#4A76B8", aliases: []),
    "MTML": LinguistLanguage(type: "markup", color: "#b7e1f4", aliases: []),
    "MUF": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Macaulay2": LinguistLanguage(type: "programming", color: "#d8ffff", aliases: ['m2']),
    "Makefile": LinguistLanguage(type: "programming", color: "#427819", aliases: ['bsdmake', 'make', 'mf']),
    "Mako": LinguistLanguage(type: "programming", color: "#7e858d", aliases: []),
    "Markdown": LinguistLanguage(type: "prose", color: "#083fa1", aliases: ['md', 'pandoc']),
    "Marko": LinguistLanguage(type: "markup", color: "#42bff2", aliases: ['markojs']),
    "Mask": LinguistLanguage(type: "markup", color: "#f97732", aliases: []),
    "Mathematical Programming System": LinguistLanguage(type: "programming", color: "#0530ad", aliases: []),
    "Maven POM": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Max": LinguistLanguage(type: "programming", color: "#c4a79c", aliases: ['max/msp', 'maxmsp']),
    "MeTTa": LinguistLanguage(type: "programming", color: "#6a5acd", aliases: []),
    "Mercury": LinguistLanguage(type: "programming", color: "#ff2b2b", aliases: []),
    "Mermaid": LinguistLanguage(type: "markup", color: "#ff3670", aliases: ['mermaid example']),
    "Meson": LinguistLanguage(type: "programming", color: "#007800", aliases: []),
    "Metal": LinguistLanguage(type: "programming", color: "#8f14e9", aliases: []),
    "Microsoft Developer Studio Project": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Microsoft Visual Studio Solution": LinguistLanguage(type: "data", color: nil, aliases: []),
    "MiniD": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "MiniYAML": LinguistLanguage(type: "data", color: "#ff1111", aliases: []),
    "MiniZinc": LinguistLanguage(type: "programming", color: "#06a9e6", aliases: []),
    "MiniZinc Data": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Mint": LinguistLanguage(type: "programming", color: "#02b046", aliases: []),
    "Mirah": LinguistLanguage(type: "programming", color: "#c7a938", aliases: []),
    "Modelica": LinguistLanguage(type: "programming", color: "#de1d31", aliases: []),
    "Modula-2": LinguistLanguage(type: "programming", color: "#10253f", aliases: []),
    "Modula-3": LinguistLanguage(type: "programming", color: "#223388", aliases: []),
    "Module Management System": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Mojo": LinguistLanguage(type: "programming", color: "#ff4c1f", aliases: []),
    "Monkey": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Monkey C": LinguistLanguage(type: "programming", color: "#8D6747", aliases: []),
    "Moocode": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "MoonBit": LinguistLanguage(type: "programming", color: "#b92381", aliases: []),
    "MoonScript": LinguistLanguage(type: "programming", color: "#ff4585", aliases: []),
    "Motoko": LinguistLanguage(type: "programming", color: "#fbb03b", aliases: []),
    "Motorola 68K Assembly": LinguistLanguage(type: "programming", color: "#005daa", aliases: ['m68k']),
    "Move": LinguistLanguage(type: "programming", color: "#4a137a", aliases: []),
    "Muse": LinguistLanguage(type: "prose", color: nil, aliases: ['amusewiki', 'emacs muse']),
    "Mustache": LinguistLanguage(type: "markup", color: "#724b3b", aliases: []),
    "Myghty": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "NASL": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "NCL": LinguistLanguage(type: "programming", color: "#28431f", aliases: []),
    "NEON": LinguistLanguage(type: "data", color: nil, aliases: ['nette object notation', 'ne-on']),
    "NL": LinguistLanguage(type: "data", color: nil, aliases: []),
    "NMODL": LinguistLanguage(type: "programming", color: "#00356B", aliases: []),
    "NPM Config": LinguistLanguage(type: "data", color: "#cb3837", aliases: ['npmrc']),
    "NSIS": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "NWScript": LinguistLanguage(type: "programming", color: "#111522", aliases: []),
    "Nasal": LinguistLanguage(type: "programming", color: "#1d2c4e", aliases: []),
    "Nearley": LinguistLanguage(type: "programming", color: "#990000", aliases: []),
    "Nemerle": LinguistLanguage(type: "programming", color: "#3d3c6e", aliases: []),
    "NetLinx": LinguistLanguage(type: "programming", color: "#0aa0ff", aliases: []),
    "NetLinx+ERB": LinguistLanguage(type: "programming", color: "#747faa", aliases: []),
    "NetLogo": LinguistLanguage(type: "programming", color: "#ff6375", aliases: []),
    "NewLisp": LinguistLanguage(type: "programming", color: "#87AED7", aliases: []),
    "Nextflow": LinguistLanguage(type: "programming", color: "#3ac486", aliases: []),
    "Nginx": LinguistLanguage(type: "data", color: "#009639", aliases: ['nginx configuration file']),
    "Nickel": LinguistLanguage(type: "programming", color: "#E0C3FC", aliases: []),
    "Nim": LinguistLanguage(type: "programming", color: "#ffc200", aliases: []),
    "Ninja": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Nit": LinguistLanguage(type: "programming", color: "#009917", aliases: []),
    "Nix": LinguistLanguage(type: "programming", color: "#7e7eff", aliases: ['nixos']),
    "Noir": LinguistLanguage(type: "programming", color: "#2f1f49", aliases: ['nargo']),
    "Nu": LinguistLanguage(type: "programming", color: "#c9df40", aliases: ['nush']),
    "NumPy": LinguistLanguage(type: "programming", color: "#9C8AF9", aliases: []),
    "Nunjucks": LinguistLanguage(type: "markup", color: "#3d8137", aliases: ['njk']),
    "Nushell": LinguistLanguage(type: "programming", color: "#4E9906", aliases: ['nu-script', 'nushell-script']),
    "OASv2-json": LinguistLanguage(type: "data", color: "#85ea2d", aliases: []),
    "OASv2-yaml": LinguistLanguage(type: "data", color: "#85ea2d", aliases: []),
    "OASv3-json": LinguistLanguage(type: "data", color: "#85ea2d", aliases: []),
    "OASv3-yaml": LinguistLanguage(type: "data", color: "#85ea2d", aliases: []),
    "OCaml": LinguistLanguage(type: "programming", color: "#ef7a08", aliases: []),
    "OMNeT++ MSG": LinguistLanguage(type: "programming", color: "#a0e0a0", aliases: ['omnetpp-msg']),
    "OMNeT++ NED": LinguistLanguage(type: "programming", color: "#08607c", aliases: ['omnetpp-ned']),
    "Oberon": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "ObjDump": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Object Data Instance Notation": LinguistLanguage(type: "data", color: nil, aliases: []),
    "ObjectScript": LinguistLanguage(type: "programming", color: "#424893", aliases: []),
    "Objective-C": LinguistLanguage(type: "programming", color: "#438eff", aliases: ['obj-c', 'objc', 'objectivec']),
    "Objective-C++": LinguistLanguage(type: "programming", color: "#6866fb", aliases: ['obj-c++', 'objc++', 'objectivec++']),
    "Objective-J": LinguistLanguage(type: "programming", color: "#ff0c5a", aliases: ['obj-j', 'objectivej', 'objj']),
    "Odin": LinguistLanguage(type: "programming", color: "#60AFFE", aliases: ['odinlang', 'odin-lang']),
    "Omgrofl": LinguistLanguage(type: "programming", color: "#cabbff", aliases: []),
    "Opa": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Opal": LinguistLanguage(type: "programming", color: "#f7ede0", aliases: []),
    "Open Policy Agent": LinguistLanguage(type: "programming", color: "#7d9199", aliases: []),
    "OpenAPI Specification v2": LinguistLanguage(type: "data", color: "#85ea2d", aliases: ['oasv2']),
    "OpenAPI Specification v3": LinguistLanguage(type: "data", color: "#85ea2d", aliases: ['oasv3']),
    "OpenCL": LinguistLanguage(type: "programming", color: "#ed2e2d", aliases: []),
    "OpenEdge ABL": LinguistLanguage(type: "programming", color: "#5ce600", aliases: ['progress', 'openedge', 'abl']),
    "OpenQASM": LinguistLanguage(type: "programming", color: "#AA70FF", aliases: []),
    "OpenRC runscript": LinguistLanguage(type: "programming", color: nil, aliases: ['openrc']),
    "OpenSCAD": LinguistLanguage(type: "programming", color: "#e5cd45", aliases: []),
    "OpenStep Property List": LinguistLanguage(type: "data", color: nil, aliases: []),
    "OpenType Feature File": LinguistLanguage(type: "data", color: nil, aliases: ['AFDKO']),
    "Option List": LinguistLanguage(type: "data", color: "#476732", aliases: ['opts', 'ackrc']),
    "Org": LinguistLanguage(type: "prose", color: "#77aa99", aliases: []),
    "OverpassQL": LinguistLanguage(type: "programming", color: "#cce2aa", aliases: []),
    "Ox": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Oxygene": LinguistLanguage(type: "programming", color: "#cdd0e3", aliases: []),
    "Oz": LinguistLanguage(type: "programming", color: "#fab738", aliases: []),
    "P4": LinguistLanguage(type: "programming", color: "#7055b5", aliases: []),
    "PDDL": LinguistLanguage(type: "programming", color: "#0d00ff", aliases: []),
    "PEG.js": LinguistLanguage(type: "programming", color: "#234d6b", aliases: []),
    "PHP": LinguistLanguage(type: "programming", color: "#4F5D95", aliases: ['inc']),
    "PLSQL": LinguistLanguage(type: "programming", color: "#dad8d8", aliases: []),
    "PLpgSQL": LinguistLanguage(type: "programming", color: "#336790", aliases: []),
    "POV-Ray SDL": LinguistLanguage(type: "programming", color: "#6bac65", aliases: ['pov-ray', 'povray']),
    "Pact": LinguistLanguage(type: "programming", color: "#F7A8B8", aliases: []),
    "Pan": LinguistLanguage(type: "programming", color: "#cc0000", aliases: []),
    "Papyrus": LinguistLanguage(type: "programming", color: "#6600cc", aliases: []),
    "Parrot": LinguistLanguage(type: "programming", color: "#f3ca0a", aliases: []),
    "Parrot Assembly": LinguistLanguage(type: "programming", color: nil, aliases: ['pasm']),
    "Parrot Internal Representation": LinguistLanguage(type: "programming", color: nil, aliases: ['pir']),
    "Pascal": LinguistLanguage(type: "programming", color: "#E3F171", aliases: ['delphi', 'objectpascal']),
    "Pawn": LinguistLanguage(type: "programming", color: "#dbb284", aliases: []),
    "Pep8": LinguistLanguage(type: "programming", color: "#C76F5B", aliases: []),
    "Perl": LinguistLanguage(type: "programming", color: "#0298c3", aliases: ['cperl']),
    "Pic": LinguistLanguage(type: "markup", color: nil, aliases: ['pikchr']),
    "Pickle": LinguistLanguage(type: "data", color: nil, aliases: []),
    "PicoLisp": LinguistLanguage(type: "programming", color: "#6067af", aliases: []),
    "PigLatin": LinguistLanguage(type: "programming", color: "#fcd7de", aliases: []),
    "Pike": LinguistLanguage(type: "programming", color: "#005390", aliases: []),
    "Pip Requirements": LinguistLanguage(type: "data", color: "#FFD343", aliases: []),
    "Pkl": LinguistLanguage(type: "programming", color: "#6b9543", aliases: []),
    "PlantUML": LinguistLanguage(type: "data", color: "#fbbd16", aliases: []),
    "Pod": LinguistLanguage(type: "prose", color: nil, aliases: []),
    "Pod 6": LinguistLanguage(type: "prose", color: nil, aliases: []),
    "PogoScript": LinguistLanguage(type: "programming", color: "#d80074", aliases: []),
    "Polar": LinguistLanguage(type: "programming", color: "#ae81ff", aliases: []),
    "Pony": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Portugol": LinguistLanguage(type: "programming", color: "#f8bd00", aliases: []),
    "PostCSS": LinguistLanguage(type: "markup", color: "#dc3a0c", aliases: []),
    "PostScript": LinguistLanguage(type: "markup", color: "#da291c", aliases: ['postscr']),
    "PowerBuilder": LinguistLanguage(type: "programming", color: "#8f0f8d", aliases: []),
    "PowerShell": LinguistLanguage(type: "programming", color: "#012456", aliases: ['posh', 'pwsh']),
    "Praat": LinguistLanguage(type: "programming", color: "#c8506d", aliases: []),
    "Prisma": LinguistLanguage(type: "data", color: "#0c344b", aliases: []),
    "Processing": LinguistLanguage(type: "programming", color: "#0096D8", aliases: []),
    "Procfile": LinguistLanguage(type: "programming", color: "#3B2F63", aliases: []),
    "Proguard": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Prolog": LinguistLanguage(type: "programming", color: "#74283c", aliases: []),
    "Promela": LinguistLanguage(type: "programming", color: "#de0000", aliases: []),
    "Propeller Spin": LinguistLanguage(type: "programming", color: "#7fa2a7", aliases: []),
    "Protocol Buffer": LinguistLanguage(type: "data", color: nil, aliases: ['proto', 'protobuf', 'Protocol Buffers']),
    "Protocol Buffer Text Format": LinguistLanguage(type: "data", color: nil, aliases: ['text proto', 'protobuf text format']),
    "Public Key": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Pug": LinguistLanguage(type: "markup", color: "#a86454", aliases: []),
    "Puppet": LinguistLanguage(type: "programming", color: "#302B6D", aliases: []),
    "Pure Data": LinguistLanguage(type: "data", color: nil, aliases: []),
    "PureBasic": LinguistLanguage(type: "programming", color: "#5a6986", aliases: []),
    "PureScript": LinguistLanguage(type: "programming", color: "#1D222D", aliases: []),
    "Pyret": LinguistLanguage(type: "programming", color: "#ee1e10", aliases: []),
    "Python": LinguistLanguage(type: "programming", color: "#3572A5", aliases: ['py', 'py3', 'python3', 'rusthon']),
    "Python console": LinguistLanguage(type: "programming", color: "#3572A5", aliases: ['pycon']),
    "Python traceback": LinguistLanguage(type: "data", color: "#3572A5", aliases: []),
    "Q#": LinguistLanguage(type: "programming", color: "#fed659", aliases: ['qsharp']),
    "QML": LinguistLanguage(type: "programming", color: "#44a51c", aliases: []),
    "QMake": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Qt Script": LinguistLanguage(type: "programming", color: "#00b841", aliases: []),
    "Quake": LinguistLanguage(type: "programming", color: "#882233", aliases: []),
    "QuakeC": LinguistLanguage(type: "programming", color: "#975777", aliases: []),
    "QuickBASIC": LinguistLanguage(type: "programming", color: "#008080", aliases: ['qb', 'qbasic', 'qb64', 'classic qbasic', 'classic quickbasic']),
    "Quint": LinguistLanguage(type: "programming", color: "#9d6ce5", aliases: []),
    "R": LinguistLanguage(type: "programming", color: "#198CE7", aliases: ['Rscript', 'splus']),
    "RAML": LinguistLanguage(type: "markup", color: "#77d9fb", aliases: []),
    "RAScript": LinguistLanguage(type: "programming", color: "#2C97FA", aliases: []),
    "RBS": LinguistLanguage(type: "data", color: "#701516", aliases: []),
    "RDoc": LinguistLanguage(type: "prose", color: "#701516", aliases: []),
    "REALbasic": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "REXX": LinguistLanguage(type: "programming", color: "#d90e09", aliases: ['arexx']),
    "RMarkdown": LinguistLanguage(type: "prose", color: "#198ce7", aliases: []),
    "RON": LinguistLanguage(type: "data", color: "#a62c00", aliases: []),
    "ROS Interface": LinguistLanguage(type: "data", color: "#22314e", aliases: ['rosmsg']),
    "RPC": LinguistLanguage(type: "programming", color: nil, aliases: ['rpcgen', 'oncrpc', 'xdr']),
    "RPGLE": LinguistLanguage(type: "programming", color: "#2BDE21", aliases: ['ile rpg', 'sqlrpgle']),
    "RPM Spec": LinguistLanguage(type: "data", color: nil, aliases: ['specfile']),
    "RUNOFF": LinguistLanguage(type: "markup", color: "#665a4e", aliases: []),
    "Racket": LinguistLanguage(type: "programming", color: "#3c5caa", aliases: []),
    "Ragel": LinguistLanguage(type: "programming", color: "#9d5200", aliases: ['ragel-rb', 'ragel-ruby']),
    "Raku": LinguistLanguage(type: "programming", color: "#0000fb", aliases: ['perl6', 'perl-6']),
    "Rascal": LinguistLanguage(type: "programming", color: "#fffaa0", aliases: []),
    "Raw token data": LinguistLanguage(type: "data", color: nil, aliases: ['raw']),
    "ReScript": LinguistLanguage(type: "programming", color: "#ed5051", aliases: []),
    "Readline Config": LinguistLanguage(type: "data", color: nil, aliases: ['inputrc', 'readline']),
    "Reason": LinguistLanguage(type: "programming", color: "#ff5847", aliases: []),
    "ReasonLIGO": LinguistLanguage(type: "programming", color: "#ff5847", aliases: []),
    "Rebol": LinguistLanguage(type: "programming", color: "#358a5b", aliases: []),
    "Record Jar": LinguistLanguage(type: "data", color: "#0673ba", aliases: []),
    "Red": LinguistLanguage(type: "programming", color: "#f50000", aliases: ['red/system']),
    "Redcode": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Redirect Rules": LinguistLanguage(type: "data", color: nil, aliases: ['redirects']),
    "Regular Expression": LinguistLanguage(type: "data", color: "#009a00", aliases: ['regexp', 'regex']),
    "Ren'Py": LinguistLanguage(type: "programming", color: "#ff7f7f", aliases: ['renpy']),
    "RenderScript": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Rez": LinguistLanguage(type: "programming", color: "#FFDAB3", aliases: []),
    "Rich Text Format": LinguistLanguage(type: "markup", color: nil, aliases: []),
    "Ring": LinguistLanguage(type: "programming", color: "#2D54CB", aliases: []),
    "Riot": LinguistLanguage(type: "markup", color: "#A71E49", aliases: []),
    "RobotFramework": LinguistLanguage(type: "programming", color: "#00c0b5", aliases: []),
    "Roc": LinguistLanguage(type: "programming", color: "#7c38f5", aliases: []),
    "Rocq Prover": LinguistLanguage(type: "programming", color: "#d0b68c", aliases: ['coq', 'rocq']),
    "Roff": LinguistLanguage(type: "markup", color: "#ecdebe", aliases: ['groff', 'man', 'manpage', 'man page', 'man-page', 'mdoc', 'nroff', 'troff']),
    "Roff Manpage": LinguistLanguage(type: "markup", color: "#ecdebe", aliases: []),
    "Rouge": LinguistLanguage(type: "programming", color: "#cc0088", aliases: []),
    "RouterOS Script": LinguistLanguage(type: "programming", color: "#DE3941", aliases: []),
    "Ruby": LinguistLanguage(type: "programming", color: "#701516", aliases: ['jruby', 'macruby', 'rake', 'rb', 'rbx']),
    "Rust": LinguistLanguage(type: "programming", color: "#dea584", aliases: ['rs']),
    "SAS": LinguistLanguage(type: "programming", color: "#B34936", aliases: []),
    "SCSS": LinguistLanguage(type: "markup", color: "#c6538c", aliases: []),
    "SELinux Policy": LinguistLanguage(type: "data", color: nil, aliases: ['SELinux Kernel Policy Language', 'sepolicy']),
    "SMT": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "SPARQL": LinguistLanguage(type: "data", color: "#0C4597", aliases: []),
    "SQF": LinguistLanguage(type: "programming", color: "#3F3F3F", aliases: []),
    "SQL": LinguistLanguage(type: "data", color: "#e38c00", aliases: []),
    "SQLPL": LinguistLanguage(type: "programming", color: "#e38c00", aliases: []),
    "SRecode Template": LinguistLanguage(type: "markup", color: "#348a34", aliases: []),
    "SSH Config": LinguistLanguage(type: "data", color: nil, aliases: ['sshconfig', 'sshdconfig', 'ssh_config', 'sshd_config']),
    "STAR": LinguistLanguage(type: "data", color: nil, aliases: []),
    "STL": LinguistLanguage(type: "data", color: "#373b5e", aliases: ['ascii stl', 'stla']),
    "STON": LinguistLanguage(type: "data", color: nil, aliases: []),
    "SVG": LinguistLanguage(type: "data", color: "#ff9900", aliases: []),
    "SWIG": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Sage": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Sail": LinguistLanguage(type: "programming", color: "#259dd5", aliases: []),
    "SaltStack": LinguistLanguage(type: "programming", color: "#646464", aliases: ['saltstate', 'salt']),
    "Sass": LinguistLanguage(type: "markup", color: "#a53b70", aliases: []),
    "Scala": LinguistLanguage(type: "programming", color: "#c22d40", aliases: []),
    "Scaml": LinguistLanguage(type: "markup", color: "#bd181a", aliases: []),
    "Scenic": LinguistLanguage(type: "programming", color: "#fdc700", aliases: []),
    "Scheme": LinguistLanguage(type: "programming", color: "#1e4aec", aliases: []),
    "Scilab": LinguistLanguage(type: "programming", color: "#ca0f21", aliases: []),
    "Self": LinguistLanguage(type: "programming", color: "#0579aa", aliases: []),
    "ShaderLab": LinguistLanguage(type: "programming", color: "#222c37", aliases: []),
    "Shell": LinguistLanguage(type: "programming", color: "#89e051", aliases: ['sh', 'shell-script', 'bash', 'zsh', 'envrc']),
    "ShellCheck Config": LinguistLanguage(type: "data", color: "#cecfcb", aliases: ['shellcheckrc']),
    "ShellSession": LinguistLanguage(type: "programming", color: nil, aliases: ['bash session', 'console']),
    "Shen": LinguistLanguage(type: "programming", color: "#120F14", aliases: []),
    "Sieve": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Simple File Verification": LinguistLanguage(type: "data", color: "#C9BFED", aliases: ['sfv']),
    "Singularity": LinguistLanguage(type: "programming", color: "#64E6AD", aliases: []),
    "Slang": LinguistLanguage(type: "programming", color: "#1fbec9", aliases: []),
    "Slash": LinguistLanguage(type: "programming", color: "#007eff", aliases: []),
    "Slice": LinguistLanguage(type: "programming", color: "#003fa2", aliases: []),
    "Slim": LinguistLanguage(type: "markup", color: "#2b2b2b", aliases: []),
    "Slint": LinguistLanguage(type: "markup", color: "#2379F4", aliases: []),
    "SmPL": LinguistLanguage(type: "programming", color: "#c94949", aliases: ['coccinelle']),
    "Smali": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "Smalltalk": LinguistLanguage(type: "programming", color: "#596706", aliases: ['squeak']),
    "Smarty": LinguistLanguage(type: "programming", color: "#f0c040", aliases: []),
    "Smithy": LinguistLanguage(type: "programming", color: "#c44536", aliases: []),
    "Snakemake": LinguistLanguage(type: "programming", color: "#419179", aliases: ['snakefile']),
    "Solidity": LinguistLanguage(type: "programming", color: "#AA6746", aliases: []),
    "Soong": LinguistLanguage(type: "data", color: nil, aliases: []),
    "SourcePawn": LinguistLanguage(type: "programming", color: "#f69e1d", aliases: ['sourcemod']),
    "SpiceDB Schema": LinguistLanguage(type: "data", color: "#a5318a", aliases: []),
    "Spline Font Database": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Squirrel": LinguistLanguage(type: "programming", color: "#800000", aliases: []),
    "Stan": LinguistLanguage(type: "programming", color: "#b2011d", aliases: []),
    "Standard ML": LinguistLanguage(type: "programming", color: "#dc566d", aliases: ['sml']),
    "Starlark": LinguistLanguage(type: "programming", color: "#76d275", aliases: ['bazel', 'bzl']),
    "Stata": LinguistLanguage(type: "programming", color: "#1a5f91", aliases: []),
    "StringTemplate": LinguistLanguage(type: "markup", color: "#3fb34f", aliases: []),
    "Stylus": LinguistLanguage(type: "markup", color: "#ff6347", aliases: []),
    "SubRip Text": LinguistLanguage(type: "data", color: "#9e0101", aliases: []),
    "SugarSS": LinguistLanguage(type: "markup", color: "#2fcc9f", aliases: []),
    "SuperCollider": LinguistLanguage(type: "programming", color: "#46390b", aliases: []),
    "SurrealQL": LinguistLanguage(type: "programming", color: "#ff00a0", aliases: ['surql']),
    "Survex data": LinguistLanguage(type: "data", color: "#ffcc99", aliases: []),
    "Svelte": LinguistLanguage(type: "markup", color: "#ff3e00", aliases: []),
    "Sway": LinguistLanguage(type: "programming", color: "#00F58C", aliases: []),
    "Sweave": LinguistLanguage(type: "prose", color: "#198ce7", aliases: []),
    "Swift": LinguistLanguage(type: "programming", color: "#F05138", aliases: []),
    "SystemVerilog": LinguistLanguage(type: "programming", color: "#DAE1C2", aliases: []),
    "TI Program": LinguistLanguage(type: "programming", color: "#A0AA87", aliases: []),
    "TL-Verilog": LinguistLanguage(type: "programming", color: "#C40023", aliases: []),
    "TLA": LinguistLanguage(type: "programming", color: "#4b0079", aliases: []),
    "TMDL": LinguistLanguage(type: "data", color: "#f0c913", aliases: ['Tabular Model Definition Language']),
    "TOML": LinguistLanguage(type: "data", color: "#9c4221", aliases: []),
    "TSPLIB data": LinguistLanguage(type: "data", color: nil, aliases: ['travelling salesman problem', 'traveling salesman problem']),
    "TSQL": LinguistLanguage(type: "programming", color: "#e38c00", aliases: []),
    "TSV": LinguistLanguage(type: "data", color: "#237346", aliases: ['tab-seperated values']),
    "TSX": LinguistLanguage(type: "programming", color: "#3178c6", aliases: ['typescriptreact']),
    "TXL": LinguistLanguage(type: "programming", color: "#0178b8", aliases: []),
    "Tact": LinguistLanguage(type: "programming", color: "#48b5ff", aliases: []),
    "Talon": LinguistLanguage(type: "programming", color: "#333333", aliases: []),
    "Tcl": LinguistLanguage(type: "programming", color: "#e4cc98", aliases: ['sdc', 'xdc']),
    "Tcsh": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "TeX": LinguistLanguage(type: "markup", color: "#3D6117", aliases: ['latex']),
    "Tea": LinguistLanguage(type: "markup", color: nil, aliases: []),
    "Teal": LinguistLanguage(type: "programming", color: "#00B1BC", aliases: []),
    "Terra": LinguistLanguage(type: "programming", color: "#00004c", aliases: []),
    "Terraform Template": LinguistLanguage(type: "markup", color: "#7b42bb", aliases: []),
    "Texinfo": LinguistLanguage(type: "prose", color: nil, aliases: []),
    "Text": LinguistLanguage(type: "prose", color: nil, aliases: ['fundamental', 'plain text']),
    "TextGrid": LinguistLanguage(type: "data", color: "#c8506d", aliases: []),
    "TextMate Properties": LinguistLanguage(type: "data", color: "#df66e4", aliases: ['tm-properties']),
    "Textile": LinguistLanguage(type: "prose", color: "#ffe7ac", aliases: []),
    "Thrift": LinguistLanguage(type: "programming", color: "#D12127", aliases: []),
    "Toit": LinguistLanguage(type: "programming", color: "#c2c9fb", aliases: []),
    "Tor Config": LinguistLanguage(type: "data", color: "#59316b", aliases: ['torrc']),
    "Tree-sitter Query": LinguistLanguage(type: "programming", color: "#8ea64c", aliases: ['tsq']),
    "Turing": LinguistLanguage(type: "programming", color: "#cf142b", aliases: []),
    "Turtle": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Twig": LinguistLanguage(type: "markup", color: "#c1d026", aliases: []),
    "Type Language": LinguistLanguage(type: "data", color: nil, aliases: ['tl']),
    "TypeScript": LinguistLanguage(type: "programming", color: "#3178c6", aliases: ['ts']),
    "TypeSpec": LinguistLanguage(type: "programming", color: "#4A3665", aliases: ['tsp']),
    "Typst": LinguistLanguage(type: "programming", color: "#239dad", aliases: ['typ']),
    "Unified Parallel C": LinguistLanguage(type: "programming", color: "#4e3617", aliases: []),
    "Unity3D Asset": LinguistLanguage(type: "data", color: "#222c37", aliases: []),
    "Unix Assembly": LinguistLanguage(type: "programming", color: nil, aliases: ['gas', 'gnu asm', 'unix asm']),
    "Uno": LinguistLanguage(type: "programming", color: "#9933cc", aliases: []),
    "UnrealScript": LinguistLanguage(type: "programming", color: "#a54c4d", aliases: []),
    "Untyped Plutus Core": LinguistLanguage(type: "programming", color: "#36adbd", aliases: []),
    "UrWeb": LinguistLanguage(type: "programming", color: "#ccccee", aliases: ['Ur/Web', 'Ur']),
    "V": LinguistLanguage(type: "programming", color: "#4f87c4", aliases: ['vlang']),
    "VBA": LinguistLanguage(type: "programming", color: "#867db1", aliases: ['visual basic for applications']),
    "VBScript": LinguistLanguage(type: "programming", color: "#15dcdc", aliases: []),
    "VCL": LinguistLanguage(type: "programming", color: "#148AA8", aliases: []),
    "VHDL": LinguistLanguage(type: "programming", color: "#adb2cb", aliases: []),
    "Vala": LinguistLanguage(type: "programming", color: "#a56de2", aliases: []),
    "Valve Data Format": LinguistLanguage(type: "data", color: "#f26025", aliases: ['keyvalues', 'vdf']),
    "Velocity Template Language": LinguistLanguage(type: "markup", color: "#507cff", aliases: ['vtl', 'velocity']),
    "Vento": LinguistLanguage(type: "markup", color: "#ff0080", aliases: []),
    "Verilog": LinguistLanguage(type: "programming", color: "#b2b7f8", aliases: []),
    "Vim Help File": LinguistLanguage(type: "prose", color: "#199f4b", aliases: ['help', 'vimhelp']),
    "Vim Script": LinguistLanguage(type: "programming", color: "#199f4b", aliases: ['vim', 'viml', 'nvim', 'vimscript']),
    "Vim Snippet": LinguistLanguage(type: "markup", color: "#199f4b", aliases: ['SnipMate', 'UltiSnip', 'UltiSnips', 'NeoSnippet']),
    "Visual Basic .NET": LinguistLanguage(type: "programming", color: "#945db7", aliases: ['visual basic', 'vbnet', 'vb .net', 'vb.net']),
    "Visual Basic 6.0": LinguistLanguage(type: "programming", color: "#2c6353", aliases: ['vb6', 'vb 6', 'visual basic 6', 'visual basic classic', 'classic visual basic']),
    "Volt": LinguistLanguage(type: "programming", color: "#1F1F1F", aliases: []),
    "Vue": LinguistLanguage(type: "markup", color: "#41b883", aliases: []),
    "Vyper": LinguistLanguage(type: "programming", color: "#9F4CF2", aliases: []),
    "WDL": LinguistLanguage(type: "programming", color: "#42f1f4", aliases: ['Workflow Description Language']),
    "WGSL": LinguistLanguage(type: "programming", color: "#1a5e9a", aliases: []),
    "Wavefront Material": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Wavefront Object": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Web Ontology Language": LinguistLanguage(type: "data", color: "#5b70bd", aliases: []),
    "WebAssembly": LinguistLanguage(type: "programming", color: "#04133b", aliases: ['wast', 'wasm']),
    "WebAssembly Interface Type": LinguistLanguage(type: "data", color: "#6250e7", aliases: ['wit']),
    "WebIDL": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "WebVTT": LinguistLanguage(type: "data", color: nil, aliases: ['vtt']),
    "Wget Config": LinguistLanguage(type: "data", color: nil, aliases: ['wgetrc']),
    "Whiley": LinguistLanguage(type: "programming", color: "#d5c397", aliases: []),
    "Wikitext": LinguistLanguage(type: "prose", color: "#fc5757", aliases: ['mediawiki', 'wiki']),
    "Win32 Message File": LinguistLanguage(type: "data", color: nil, aliases: []),
    "Windows Registry Entries": LinguistLanguage(type: "data", color: "#52d5ff", aliases: []),
    "Witcher Script": LinguistLanguage(type: "programming", color: "#ff0000", aliases: []),
    "Wolfram Language": LinguistLanguage(type: "programming", color: "#dd1100", aliases: ['mathematica', 'mma', 'wolfram', 'wolfram lang', 'wl']),
    "Wollok": LinguistLanguage(type: "programming", color: "#a23738", aliases: []),
    "World of Warcraft Addon Data": LinguistLanguage(type: "data", color: "#f7e43f", aliases: []),
    "Wren": LinguistLanguage(type: "programming", color: "#383838", aliases: ['wrenlang']),
    "X BitMap": LinguistLanguage(type: "data", color: nil, aliases: ['xbm']),
    "X Font Directory Index": LinguistLanguage(type: "data", color: nil, aliases: []),
    "X PixMap": LinguistLanguage(type: "data", color: nil, aliases: ['xpm']),
    "X10": LinguistLanguage(type: "programming", color: "#4B6BEF", aliases: ['xten']),
    "XC": LinguistLanguage(type: "programming", color: "#99DA07", aliases: []),
    "XCompose": LinguistLanguage(type: "data", color: nil, aliases: []),
    "XML": LinguistLanguage(type: "data", color: "#0060ac", aliases: ['rss', 'xsd', 'wsdl']),
    "XML Property List": LinguistLanguage(type: "data", color: "#0060ac", aliases: []),
    "XPages": LinguistLanguage(type: "data", color: nil, aliases: []),
    "XProc": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "XQuery": LinguistLanguage(type: "programming", color: "#5232e7", aliases: []),
    "XS": LinguistLanguage(type: "programming", color: nil, aliases: []),
    "XSLT": LinguistLanguage(type: "programming", color: "#EB8CEB", aliases: ['xsl']),
    "Xmake": LinguistLanguage(type: "programming", color: "#22a079", aliases: []),
    "Xojo": LinguistLanguage(type: "programming", color: "#81bd41", aliases: []),
    "Xonsh": LinguistLanguage(type: "programming", color: "#285EEF", aliases: []),
    "Xtend": LinguistLanguage(type: "programming", color: "#24255d", aliases: []),
    "YAML": LinguistLanguage(type: "data", color: "#cb171e", aliases: ['yml']),
    "YANG": LinguistLanguage(type: "data", color: nil, aliases: []),
    "YARA": LinguistLanguage(type: "programming", color: "#220000", aliases: []),
    "YASnippet": LinguistLanguage(type: "markup", color: "#32AB90", aliases: ['snippet', 'yas']),
    "Yacc": LinguistLanguage(type: "programming", color: "#4B6C4B", aliases: []),
    "Yul": LinguistLanguage(type: "programming", color: "#794932", aliases: []),
    "ZAP": LinguistLanguage(type: "programming", color: "#0d665e", aliases: []),
    "ZIL": LinguistLanguage(type: "programming", color: "#dc75e5", aliases: []),
    "Zeek": LinguistLanguage(type: "programming", color: nil, aliases: ['bro']),
    "ZenScript": LinguistLanguage(type: "programming", color: "#00BCD1", aliases: []),
    "Zephir": LinguistLanguage(type: "programming", color: "#118f9e", aliases: []),
    "Zig": LinguistLanguage(type: "programming", color: "#ec915c", aliases: []),
    "Zimpl": LinguistLanguage(type: "programming", color: "#d67711", aliases: []),
    "Zmodel": LinguistLanguage(type: "data", color: "#ff7100", aliases: []),
    "cURL Config": LinguistLanguage(type: "data", color: nil, aliases: ['curlrc']),
    "crontab": LinguistLanguage(type: "data", color: "#ead7ac", aliases: ['cron', 'cron table']),
    "desktop": LinguistLanguage(type: "data", color: nil, aliases: []),
    "dircolors": LinguistLanguage(type: "data", color: nil, aliases: []),
    "eC": LinguistLanguage(type: "programming", color: "#913960", aliases: []),
    "edn": LinguistLanguage(type: "data", color: nil, aliases: []),
    "fish": LinguistLanguage(type: "programming", color: "#4aae47", aliases: []),
    "hoon": LinguistLanguage(type: "programming", color: "#00b171", aliases: []),
    "iCalendar": LinguistLanguage(type: "data", color: "#ec564c", aliases: ['iCal']),
    "jq": LinguistLanguage(type: "programming", color: "#c7254e", aliases: []),
    "kvlang": LinguistLanguage(type: "markup", color: "#1da6e0", aliases: []),
    "mIRC Script": LinguistLanguage(type: "programming", color: "#3d57c3", aliases: []),
    "mcfunction": LinguistLanguage(type: "programming", color: "#E22837", aliases: []),
    "mdsvex": LinguistLanguage(type: "markup", color: "#5f9ea0", aliases: []),
    "mupad": LinguistLanguage(type: "programming", color: "#244963", aliases: []),
    "nanorc": LinguistLanguage(type: "data", color: "#2d004d", aliases: []),
    "nesC": LinguistLanguage(type: "programming", color: "#94B0C7", aliases: []),
    "ooc": LinguistLanguage(type: "programming", color: "#b0b77e", aliases: []),
    "q": LinguistLanguage(type: "programming", color: "#0040cd", aliases: []),
    "reStructuredText": LinguistLanguage(type: "prose", color: "#141414", aliases: ['rst']),
    "robots.txt": LinguistLanguage(type: "data", color: nil, aliases: ['robots', 'robots txt']),
    "sed": LinguistLanguage(type: "programming", color: "#64b970", aliases: []),
    "templ": LinguistLanguage(type: "markup", color: "#66D0DD", aliases: []),
    "vCard": LinguistLanguage(type: "data", color: "#ee2647", aliases: ['virtual contact file', 'electronic business card']),
    "wisp": LinguistLanguage(type: "programming", color: "#7582D1", aliases: []),
    "xBase": LinguistLanguage(type: "programming", color: "#403a40", aliases: ['advpl', 'clipper', 'foxpro']),
]

/// 根据语言名获取元数据
public func linguistLanguage(for name: String) -> LinguistLanguage? {
    return linguistLanguages[name]
}